### ISSUE TITLE
设置平均码率无效

### ISSUE THREAD

**Issue by zxcec** [SmallPeaches/DanmakuRender#100]
我在default.yml和replay.yml都设置和添加了平均码率6m但是最后视频出来是15m

![屏幕截图 2023-08-31 015129](https://github.com/SmallPeaches/DanmakuRender/assets/51906392/6ce43d7a-906e-4cdb-bc2f-e0524e8b49bb)

zip文件是两个yml文件
[Downloads.zip](https://github.com/SmallPeaches/DanmakuRender/files/12478820/Downloads.zip)

**Comment by Ms213s** [comment]
使用新方法指定录制配置请保证原有replay.yml中的replay项为空。

**Comment by zxcec** [comment]
> 使用新方法指定录制配置请保证原有replay.yml中的replay项为空。

能具体说一下么？我找不到replay项

**Comment by SmallPeaches** [comment]
> 我在default.yml和replay.yml都设置和添加了平均码率6m但是最后视频出来是15m
> 
> ![屏幕截图 2023-08-31 015129](https://user-images.githubusercontent.com/51906392/264430080-6ce43d7a-906e-4cdb-bc2f-e0524e8b49bb.png)
> 
> zip文件是两个yml文件 [Downloads.zip](https://github.com/SmallPeaches/DanmakuRender/files/12478820/Downloads.zip)

新版本不应该改default.yml，如果需要设置全局渲染参数应该改主文件夹里的replay.yml，如果想单独每个主播设置不同的渲染参数应该在单独的replay-cc.yml里面改

**Comment by zxcec** [comment]
搞定了，感谢帮助
