### ISSUE TITLE
新手 想詢問哪裡出問題了能幫幫忙嗎 謝謝

### ISSUE THREAD

**Issue by Bao0224** [SmallPeaches/DanmakuRender#102]
不好意思
新手剛接觸 已經試過好多次了可是還是一直出問題
這是最成功的一次...
原本還沒開播前 是不會跳錯誤的 還以為終於成功了
結果等到開播後就變成這樣了

![螢幕擷取畫面 2023-09-02 184446](https://github.com/SmallPeaches/DanmakuRender/assets/143877306/21bb6656-46ce-4284-913d-1e6224bab4fc)
![螢幕擷取畫面 2023-09-02 184509](https://github.com/SmallPeaches/DanmakuRender/assets/143877306/8f04170a-49cc-4680-9484-d4d1f59f5c59)

我的使用環境是 用Primo Ramdisk 程式弄了一個Y槽出來
把PYTHON安裝在裡面 DanmakuRender也放在這
有大大有空能幫忙看看 要怎麼解決嗎 謝謝你們 謝謝作者

**Comment by SmallPeaches** [comment]
你检查一下ffmpeg.exe和ffprobe.exe有没有正确的放在tools文件夹里面？

**Comment by Bao0224** [comment]
你好 先謝謝作者的回覆 
請問我放在這裡 應該是沒錯的吧?

![螢幕擷取畫面 2023-09-03 002817](https://github.com/SmallPeaches/DanmakuRender/assets/143877306/c090d87d-37a7-4f22-a8d9-d09b7b69e8a4)

補充一下 我複製example.yml後 自己修改的TEST裡面我有刪除 
![螢幕擷取畫面 2023-09-03 003429](https://github.com/SmallPeaches/DanmakuRender/assets/143877306/7ac06dad-27cd-4491-a228-806b793dc6fa)

# 上传参数，如果不需要上传就把下面的都删了
upload:
  # 原视频
  src_video: 
以及
# 弹幕视频
  dm_video:

因為用不到自動上傳 我打算自己手動上傳
所以刪除這兩大列內的程式碼有關係嗎 謝謝妳

**Comment by SmallPeaches** [comment]
嗯，这样应该没问题了，你不放心的话可以运行dryrun.py做测试，如果你不上传的话是不会要求你登录的

**Comment by Bao0224** [comment]
> 嗯，這樣應該沒問題了，你不放心的話可以運行 dryrun.py 做測試，如果你不上傳的話是不會要求你登錄的

你好 可能誤會了我沒說清楚 抱歉
我第二次回覆的內容是指 我是放在這裡應該沒錯 或是有刪除錯程式碼嗎

====
就是我第一次發文說的最成功的一次
ffmpeg.exe和ffprobe.exe 原本就放在這了 
然後失敗了找不出問題 才上來發文求助的.. 抱歉

我很放心的 就是一直無法成功使用 很苦惱
你的程式感覺很強大 還能錄製彈幕內容 很需要這個

我雙擊這個dryrun.py 還是一樣錯誤
跟main.py同樣的問題 

![螢幕擷取畫面 2023-09-03 171936](https://github.com/SmallPeaches/DanmakuRender/assets/143877306/84fbed4b-fbca-4662-a7d4-5953db8ade95)

請問還有辦法可以提供給我嗎 謝謝你 我真的很想使用
或是我只能在重新安裝 先不刪除重新上傳的程式碼試試?
謝謝你

我的程式碼附在這裡 有那裡是錯誤嗎
還是我把資料夾的截圖都給你看看 有沒有少什麼
謝謝你



`# 本文件一个代表一个录制任务，这里的设置基本上包含了所有可用的参数
# 配置文件编写请参考 https://github.com/SmallPeaches/DanmakuRender 

# 直播间链接
url: 'https://www.douyu.com/88890'

# 录制输出文件夹，设置为空则使用主播名称作为文件夹
output_dir: ./直播回放

# 录制文件名称格式，可使用关键字替换，默认效果：飞天狙想要努力变胖-2023年3月1日20点30分，注意这里不能含有冒号，斜杠等非法字符！！
output_name: '{STREAMER}-{YEAR}年{MONTH}月{DAY}日{HOUR}点{MINUTE}分'

# 录制程序引擎，可选ffmpeg（由ffmpeg提供拉流服务）或者streamgears（使用streamgears提供拉流服务，此功能正在测试）
# 在使用streamgears作为录制引擎时，录制视频格式只能是flv
engine: ffmpeg

# 录播分段时间（秒），默认一个小时
segment: 3600

# 是否录制弹幕
danmaku: True

# 是否录制直播流
video: True

# 启动自动渲染
auto_render: True

# 延迟下播计时（分钟）
end_cnt: 10

# 默认分辨率，如果程序无法正常判断流的分辨率可以使用以下参数强行指定
resolution: [1920,1080]

# 录制视频的格式，默认flv
# 使用streamgears作为录制引擎应该使用flv
vid_format: flv

# 直播流CDN选项
# 对于虎牙直播，此项可选al, tx, hw等cdn服务器的缩写，默认al
# 对于B站，此项可选0-n表示不同的cdn服务器，默认为0，也可以输入特定的CDN域名前缀，例如 c1--cn-gotcha208
# 斗鱼和抖音暂时没用
flow_cdn: ~

# ffmpeg http参数
# 使用streamgears作为录制引擎时不生效
ffmpeg_stream_args: [-fflags,+discardcorrupt,-reconnect,'1',-rw_timeout,'10000000',
                      '-analyzeduration','15000000',
                      '-probesize','50000000',
                      '-thread_queue_size', '16']

# 关闭下载过慢自动重启功能，默认false
# 使用streamgears作为录制引擎时不生效
disable_lowspeed_interrupt: False

# 检测流变化，在推流信息变化时立即分段，建议录制手机直播时开启，PC直播时关闭，默认false
# 使用streamgears作为录制引擎时不生效
check_stream_changes: False

# 以下是弹幕录制参数

# 弹幕录制格式，只能选择ass
dm_format: ass 

# 弹幕上下间距（行距），设置为0-1的表示为视频宽度的倍数，设置为大于1的数表示像素，默认6
margin_h: 6

# 弹幕左右间距，设置为-1表示允许弹幕叠加，设置为0-1的表示间距为视频宽度的倍数，设置为大于1的数表示像素，默认0.05
margin_w: 0.05

# 指定弹幕占屏幕的最大比例（即屏幕上半部分有多少可以用来显示弹幕），默认为0.4
dmrate: 0.4

# 指定弹幕字体，默认为微软雅黑字体(Microsoft YaHei)
font: Microsoft YaHei

# 指定弹幕字体大小，默认为36
fontsize: 36

# Distance from Screen Top 弹幕距离屏幕顶端的距离（像素，例如20，表示距离屏幕顶端20px）
dst: 20

# 指定单条弹幕持续时间（秒），默认为16
dmduration: 16

# 指定弹幕不透明度，默认为0.8
opacity: 0.8

# 使用自适应弹幕大小（会让把设置的弹幕大小按1080P标准缩放）
auto_fontsize: True

# 弹幕描边颜色(6位十六进制)
outlinecolor: 000000

# 弹幕描边宽度
outlinesize: 1.0

# 弹幕延迟补偿（秒），一般情况下弹幕比视频慢，设置这个强行把弹幕提前，不同直播间不一样
dm_delay_fixed: 3.0

# 弹幕录制程序自动重启间隔（在没人发弹幕的时候会定时重启，保证录制正常，默认300秒，0关闭）
dm_auto_restart: 300

# 弹幕过滤规则，一个正则表达式数组（也可以直接输入关键字），满足其中任意条件的弹幕将被过滤，默认为空（不过滤弹幕）
dm_filter: []

# 自动清理
clean:
  # 清理方法，可选copy（复制），move（移动），delete（删除），默认不清理
  # 请注意：清理过程不可逆！最好还是自己手动清理！
  method: ~

  # 目标文件夹，文件夹不存在会自动创建，可以使用关键字替换
  dest: ~

  # 清理延迟（秒），在上传完成后会过一段时间再清理，默认172800（48小时）
  delay: 172800
`


麻煩你了 謝謝

**Comment by SmallPeaches** [comment]
我大概懂是怎么回事了，你应该是电脑里面已经自带FFmpeg了，但是没有ffprobe，然后程序默认调用了系统自带的程序。
你可以试一下右键打开Windows terminal控制台，分别输入`ffmpeg -version`和`ffprobe -version`，第一个应该会返回正常，第二个应该会提示错误。
如果是这样的话，你只需要在程序所在文件夹的replay.yml最前面加上
```yaml
ffmpeg: tools/ffmpeg.exe
ffprobe: tools/ffprobe.exe
```
应该就可以了

**Comment by Bao0224** [comment]
> 

你好 
不好意思麻煩你了
先謝謝你的回覆
我剛剛測試了
那兩段程式碼 結果是這樣
ffm
![螢幕擷取畫面 2023-09-03 175355](https://github.com/SmallPeaches/DanmakuRender/assets/143877306/8bedf121-3ddb-4f88-bf20-7f87494055ed)
![螢幕擷取畫面 2023-09-03 175429](https://github.com/SmallPeaches/DanmakuRender/assets/143877306/e2d143fb-8b0f-4ef2-8acd-bd4b2a57d4f7)
peg -version和ffprobe -version

然後你說的加在最前面 因為我不確定是哪個replay.yml 所以我兩個資料夾內的最前面都加了
是這樣子對吧
 
![螢幕擷取畫面 2023-09-03 180601](https://github.com/SmallPeaches/DanmakuRender/assets/143877306/04268edf-ad0a-4c95-a234-bde7774d9de6)
![螢幕擷取畫面 2023-09-03 180650](https://github.com/SmallPeaches/DanmakuRender/assets/143877306/8f5f4f96-d34f-47df-a9dc-8c09db27e8cc)

結果還是無法成功錄製
還有辦法嗎QQ  我是WIN11的還是得需要重灌呢..
謝謝

**Comment by SmallPeaches** [comment]
那我之前的猜想是正确的了，就是单纯因为ffprobe的路径错了
如果放 replay.yml 里面不行的话就直接改 default.yml 吧，把里面的ffmpeg和ffprobe的值改了（就第二个图里面的那个文件）
