### ISSUE TITLE
抖音无法检测房间号

### ISSUE THREAD

**Issue by zxcec** [SmallPeaches/DanmakuRender#104]
房间号：https://live.douyin.com/298500345349

log文件
[DMR-20230904-5.log](https://github.com/SmallPeaches/DanmakuRender/files/12513272/DMR-20230904-5.log)

开启直接闪退，使用cmd显示无法
![屏幕截图 2023-09-04 191705](https://github.com/SmallPeaches/DanmakuRender/assets/51906392/b141072c-d979-432a-b7e3-d2483ab9442c)

**Comment by SmallPeaches** [comment]
应该是抖音改api了，我有时间修复一下
