### ISSUE TITLE
B站录制无法正常获取应有的弹幕量

### ISSUE THREAD

**Issue by BEIJUUUUU** [SmallPeaches/DanmakuRender#105]
![QQ截图20230904171116](https://github.com/SmallPeaches/DanmakuRender/assets/113653343/c06e4f32-ad66-4ac6-920c-c0221b7a08ba)
[DMR-20230904.log](https://github.com/SmallPeaches/DanmakuRender/files/12514898/DMR-20230904.log)

**Comment by SmallPeaches** [comment]
昨天发现这个问题了，应该是叔叔又给弹幕加强风控了，现在正在测试新版的录制方法
