### ISSUE TITLE
抖音無法錄製

### ISSUE THREAD

**Issue by alfredt999** [SmallPeaches/DanmakuRender#107]
在web browser沒問題但程序錄的時候報錯
[DMR-20230906-7.log](https://github.com/SmallPeaches/DanmakuRender/files/12538393/DMR-20230906-7.log)

**Comment by SmallPeaches** [comment]
控制台有报错什么吗？这里没看出来什么问题

**Comment by alfredt999** [comment]
就是提示房間號錯誤, 但用web browser打開url是正常的

**Comment by SmallPeaches** [comment]
你是不是没更新最新版本，最新的推送修复了这个问题。

**Comment by alfredt999** [comment]
是的. 更新到最新的就沒問題了. 謝謝.
