### ISSUE TITLE
有關彈幕內容問題

### ISSUE THREAD

**Issue by alfredt999** [SmallPeaches/DanmakuRender#108]
訊息裏沒觀眾名字

[V4+ Styles]
Format: Name, Fontname, Fontsize, PrimaryColour, SecondaryColour, OutlineColour, BackColour, Bold, Italic, Underline, StrikeOut, ScaleX, ScaleY, Spacing, Angle, BorderStyle, Outline, Shadow, Alignment, MarginL, MarginR, MarginV, Encoding
Style: R2L,Microsoft YaHei,36,&H33ffffff,,&H33000000,,-1,0,0,0,100,100,0,0,1,1.0,0,1,0,0,0,0

[Events]
Format: Layer, Start, End, Style, Name, MarginL, MarginR, MarginV, Effect, Text
Dialogue: 0,00:00:23.64,00:00:39.64,R2L,,0,0,0,,{\move(1920,56,-54,56)}{\alpha&H33\1cffffff&}q区
Dialogue: 0,00:00:28.92,00:00:44.92,R2L,,0,0,0,,{\move(1920,56,-144,56)}{\alpha&H33\1cffffff&}都是死区
Dialogue: 0,00:01:25.12,00:01:41.12,R2L,,0,0,0,,{\move(1920,56,-468,56)}{\alpha&H33\1cffffff&}不是吧………小龙没人打吗？
Dialogue: 0,00:01:33.72,00:01:49.72,R2L,,0,0,0,,{\move(1920,56,-792,56)}{\alpha&H33\1cffffff&}你能打这么多，别的区也能打这么多，等于没发育
Dialogue: 0,00:01:42.96,00:01:58.96,R2L,,0,0,0,,{\move(1920,56,-72,56)}{\alpha&H33\1cffffff&}好爽

**Comment by alfredt999** [comment]
再看了一下這不是觀眾名字 \alpha&H33\1cffffff&
那可以加發言者的名字嗎?

**Comment by alfredt999** [comment]
Ok. 找到了. 在asswriter.py的content裏加上danmu.uname就好了. 想問一下如果想加上進出直播間和進禮物訊息該怎麼改呢?

**Comment by SmallPeaches** [comment]
我这个的设计本来是类似B站主站的弹幕效果，所以说并没有设计显示礼物的功能
