### ISSUE TITLE
录制到后面依然断流

### ISSUE THREAD

**Issue by BEIJUUUUU** [SmallPeaches/DanmakuRender#11]
有可能是我网络的问题，但是我家是中国移动宽带
[6655-20221222-152704.log](https://github.com/SmallPeaches/DanmakuRender/files/10291437/6655-20221222-152704.log)

**Comment by SmallPeaches** [comment]
这个好像是你WiFi的问题？我看里面有一个Cannot reuse HTTP connection for different host: miwifi.com:-1 != d1--cn-gotcha208.bilivideo.com:-1，正常情况下不应该有miwifi的，是不是你路由器这个时候定期重启了？

**Comment by BEIJUUUUU** [comment]
> 这个好像是你WiFi的问题？我看里面有一个Cannot reuse HTTP connection for different host: miwifi.com:-1 != d1--cn-gotcha208.bilivideo.com:-1，正常情况下不应该有miwifi的，是不是你路由器这个时候定期重启了？

感觉应该不是。。。我将路由器恢复出厂设置并为我的主机设置DHCP静态IP再试试吧
