### ISSUE TITLE
网络问题导致的弹幕不同步有没有解决思路

### ISSUE THREAD

**Issue by zy55769068** [SmallPeaches/DanmakuRender#111]
偶发遇到的，网络波动导致弹幕提前或者延后了，有没有什么解决的思路？
能否做到半自动：渲染时只渲染成mp4，用Aegisub调整字幕时间轴，最后用MKVToolNix把ass压进去

**Comment by SmallPeaches** [comment]
你这个是怎么个网络波动？视频少了一段导致弹幕延后了？
半自动的话你都不用渲染啊，flv（想录制成mp4也行）+ass弹幕你自己对齐就行了

**Comment by zy55769068** [comment]
视频内容没少，弹幕本身也没少，但是最后压出来的视频，弹幕有的时候会延迟，有的时候会提前。
现在就是没定位到根本问题，不确定是网络波动引起的，还是录制的时候电脑在跑耗资源的程序引起的。

**Comment by SmallPeaches** [comment]
这个提前和延后大概有多久？如果是5-10秒内应该都是正常的。因为发弹幕的人那边的网络情况你是没法预料的。

**Comment by zy55769068** [comment]
时间差不多是这个范围，那我明白原因了，三方只要有一个不够稳的就会出现对不上，谢谢

**Comment by Mallknow** [comment]
如果使用的是FFmpeg作为录制引擎的话，延后时间会比较随机，因为FFmpeg刚开始下载的时候下载速度会非常快，可能在1秒的时间内下载了10秒的视频内容，但是弹幕写入会从连接上弹幕wss服务器的时间开始从0开始计时，因此就会造成不可准确预测的延迟。

**Comment by zy55769068** [comment]
> 如果使用的是FFmpeg作为录制引擎的话，延后时间会比较随机，因为FFmpeg刚开始下载的时候下载速度会非常快，可能在1秒的时间内下载了10秒的视频内容，但是弹幕写入会从连接上弹幕wss服务器的时间开始从0开始计时，因此就会造成不可准确预测的延迟。

我换成streamgears再观察下
