### ISSUE TITLE
录制失败

### ISSUE THREAD

**Issue by BEIJUUUUU** [SmallPeaches/DanmakuRender#113]
其他直播间应该是没问题，我觉得可能是我的网络问题因为在直播平台也无法正常观看，人在海外挂国内的梯子就可以，换了线路不用梯子也行了。希望能有办法解决
[DMR-20230928-1.log](https://github.com/SmallPeaches/DanmakuRender/files/12751009/DMR-20230928-1.log)

**Comment by SmallPeaches** [comment]
这个好像是B站的限制，部分直播间在国外是没法获取到流的。你在网页是怎么换线路的，就主线路可以备用线路不行？

**Comment by Genteure** [comment]
昨天开始又有好几个分区被划入“特殊处理”的分区里了，据说是有 1 分钟左右的直播延迟，防炸弹人狙击主播炸直播间。最初是只有 Apex 区，后来加了 Overwatch、雀魂、Minecraft 之类的。
这些分区里的直播间只有国内有 HLS 流，没有 FLV 流，海外完全不提供直播流。

**Comment by SmallPeaches** [comment]
这个海外不提供直播流，那我国内的流地址放海外能不能用呢？
实在不知道叔叔怎么想的，其他平台都没问题就它事情多。有延迟我能理解，但是国内能看国外不能看是在干什么？国外也没所谓的屏蔽词，而且也就是海外华人看B站吧...

**Comment by Genteure** [comment]
按我的理解，海外没直播流是个技术问题。海外就没部署 HLS，FLV 做延迟不方便，要实现直播延迟最简单的方法就是只提供延迟了的 HLS 不提供 FLV。海外没部署 HLS 所以就啥直播流都没有了。
从国内获取B站自建的 CDN 直播流地址，在海外应该是可以请求的。

**Comment by SmallPeaches** [comment]
这个感觉还是说不通。有没有地址是一回事，能不能流畅访问又是另外一回事了，我觉得国外没有CDN，那么直接返回国内流地址不就好了，很多地方的网络访问国内CDN也不会很差吧。
另外，弄一个HLS也不是很难的事情，至少对于一个大的上市公司来说不应该是问题。感觉就是叔叔不想弄直播了，也许是想转型升级了，毕竟直播这个东西烧钱又不赚钱。
