### ISSUE TITLE
请教下大佬 弹幕过滤的正则表达式应该怎么写呢

### ISSUE THREAD

**Issue by NoColorPiggg** [SmallPeaches/DanmakuRender#115]
例如我想过滤掉包含 抢福袋 这三个字的弹幕，不知道应该在 dm_filter: 后写什么

**Comment by SmallPeaches** [comment]
就直接填 抢福袋 就行，上面应该有例子吧

**Comment by NoColorPiggg** [comment]
看到了大佬， 原来example里有参考，我用的还是老版通过replay录制的方式，看的网页上的教程说明。
