### ISSUE TITLE
没搞明白哪个配置文件是有效的。

### ISSUE THREAD

**Issue by ddd-zero** [SmallPeaches/DanmakuRender#116]
DanmakuRender\configs里example.yml这个我明白是录制某个主播的配置文件。
DanmakuRender\configs\default.yml这个文件是干嘛用的？怎么改也没效果，这个文件写了`此文件非必要不用修改` 但我要改编码器。
DanmakuRender\replay.yml这里又有一个配置文件，还是重复的。

然后DanmakuRender\DMR\Config 这里又有两个配置文件 已经晕了

**Comment by zxcec** [comment]
改压制设置选择DanmakuRender\replay.yml
现在default基本完全没用了

**Comment by ddd-zero** [comment]
白天有时间对了一下参数。DanmakuRender\configs\default.yml里的参数被拆分为了DanmakuRender\configs里example.yml和DanmakuRender\replay.yml。应该只用这俩就行
