### ISSUE TITLE
投稿TAG这里好像有问题

### ISSUE THREAD

**Issue by ddd-zero** [SmallPeaches/DanmakuRender#118]
# 标签（一定要有！多个标签逗号分割）
    tag: '直播回放''TEST'
说是用逗号分割，但是英文逗号会报错。只能像我上面那样写才能过

**Comment by SmallPeaches** [comment]
如果只是一次投稿有问题的话应该是b站的问题，我第一次投稿的时候也是显示tag错误，但是第二次就没问题了
你这样写的话在Python里面应该算是连在一起吧？

**Comment by ddd-zero** [comment]
> 如果只是一次投稿有问题的话应该是b站的问题，我第一次投稿的时候也是显示tag错误，但是第二次就没问题了 你这样写的话在Python里面应该算是连在一起吧？
```
# 标签（一定要有！多个标签逗号分割）
tag: '直播回放','TEST'
```

如果这样的话，在运行python main.py 会报错。

```
配置文件读取错误: while parsing a block mapping
  in "configs\replay-test.yml", line 115, column 5
expected <block end>, but found ','
  in "configs\replay-test.yml", line 163, column 16
```

```
yml
第115行
    account: bilibili
第163行
    tag: '直播回放','TEST'

```

**Comment by ddd-zero** [comment]
还有一个问题就是。我下的9.23号的版本。还会提示我更新，点完更新版本还是15号的，依旧提示有更新

**Comment by SmallPeaches** [comment]
> > 如果只是一次投稿有问题的话应该是b站的问题，我第一次投稿的时候也是显示tag错误，但是第二次就没问题了 你这样写的话在Python里面应该算是连在一起吧？
> 
> ```
> # 标签（一定要有！多个标签逗号分割）
> tag: '直播回放','TEST'
> ```
> 
> 如果这样的话，在运行python main.py 会报错。
> 
> ```
> 配置文件读取错误: while parsing a block mapping
>   in "configs\replay-test.yml", line 115, column 5
> expected <block end>, but found ','
>   in "configs\replay-test.yml", line 163, column 16
> ```
> 
> ```
> yml
> 第115行
>     account: bilibili
> 第163行
>     tag: '直播回放','TEST'
> ```

逗号要在引号里面，例如`tag: '直播回放,TEST'`

**Comment by SmallPeaches** [comment]
> 还有一个问题就是。我下的9.23号的版本。还会提示我更新，点完更新版本还是15号的，依旧提示有更新

这个是更新的bug，不影响使用的

**Comment by ddd-zero** [comment]
> > > 如果只是一次投稿有问题的话应该是b站的问题，我第一次投稿的时候也是显示tag错误，但是第二次就没问题了 你这样写的话在Python里面应该算是连在一起吧？
> > 
> > 
> > ```
> > # 标签（一定要有！多个标签逗号分割）
> > tag: '直播回放','TEST'
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 如果这样的话，在运行python main.py 会报错。
> > ```
> > 配置文件读取错误: while parsing a block mapping
> >   in "configs\replay-test.yml", line 115, column 5
> > expected <block end>, but found ','
> >   in "configs\replay-test.yml", line 163, column 16
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > ```
> > yml
> > 第115行
> >     account: bilibili
> > 第163行
> >     tag: '直播回放','TEST'
> > ```
> 
> 逗号要在引号里面，例如`tag: '直播回放,TEST'`

好的。
