### ISSUE TITLE
编码器额外参数怎么写。

### ISSUE THREAD

**Issue by ddd-zero** [SmallPeaches/DanmakuRender#119]
是改DanmakuRender\replay.yml里的vencoder_args值吗？
我尝试了几种写法都报错。
我想改一下输出帧率，还有预设值，或者是x264编码的一些额外参数。
能否给个格式例子，我尝试一下

**Comment by SmallPeaches** [comment]
就改成字符串数组的形式，在执行时会传递给FFmpeg，位置在vencoder的后面。
比如说默认是`vencoder_args: [-b:v, 15M]`，你可以改成`vencoder_args: [-preset, fast, -b:v, 15M]` （使用预设fast）
最后传递给FFmpeg的参数数组就会是`ffmpeg -i xxx -c:v libx264 -preset fast -b:v 15M output`
