### ISSUE TITLE
断流后写入的视频文件就完全没用了吗？

### ISSUE THREAD

**Issue by BEIJUUUUU** [SmallPeaches/DanmakuRender#12]
![QQ截图20230104095311](https://user-images.githubusercontent.com/113653343/210471493-bfc86a9d-2b11-4d84-8f50-f681389ee9f4.png)

视频文件应该是有数据写入的，有没有办法补救？
下面是log

[6655-20230102-095914.log](https://github.com/SmallPeaches/DanmakuRender/files/10340957/6655-20230102-095914.log)

**Comment by SmallPeaches** [comment]
你可以试试用mp4修复的工具试试，我看网上好像用Digital Video Repair可以修

**Comment by BEIJUUUUU** [comment]
> 你可以试试用mp4修复的工具试试，我看网上好像用Digital Video Repair可以修

我试了试，有些视频修复之后依然损坏，有些视频修复了之后基本上无法观看（画面撕裂花屏）
