### ISSUE TITLE
FFmpeg字幕渲染帧率

### ISSUE THREAD

**Issue by ddd-zero** [SmallPeaches/DanmakuRender#120]
麻烦在replay.yml加一个强制弹幕渲染帧率为60帧的参数。
FFmpeg下为`fps=fps=60`
```
-vf fps=fps=60,scale=1920:1080,subtitles=XXX.ass 
```

当主播推出来的流是30帧的时候，弹幕压制出来的视频默认为30fps。弹幕看起来特别卡。
我指定输出的视频为60帧后`-r 60`，输出的视频元数据确实是60帧了，但渲染进去的弹幕仍然是30帧，看起来还是卡。

FFmpeg中加参数，强制让弹幕以60帧渲染后，就完全不卡了。

目前不能在replay.yml中添加 `vencoder_args: -vf fps=fps=60` ，日志显示vf被替换，无法正常渲染入字幕

我在 DanmakuRender/DMR/Render/ffmpegrender.py 修改后，可以临时使用。
```
            '-vf', 'subtitles=filename=%s' % danmaku,
```
```
            '-vf', 'fps=fps=60,subtitles=filename=%s' % danmaku,
```
附件为测试用的30帧视频源文件，及压制完成后30帧60帧对比

http://72.18.81.94:5050/zip.zip

服务器垃圾，直接用多线程拉或者挂节点

**Comment by ddd-zero** [comment]
或者直接强制锁60得了。反正现在主播基本上都是60，30的都是自己瞎搞推出来的。

**Comment by SmallPeaches** [comment]
这个可以考虑一下，把-vf也暴露出来给用户自定义。但是锁60就不好说了，很多户外主播或者颜值主播都是30的，很少见到60帧的

**Comment by ddd-zero** [comment]
> 这个可以考虑一下，把-vf也暴露出来给用户自定义。但是锁60就不好说了，很多户外主播或者颜值主播都是30的，很少见到60帧的

好的
