### ISSUE TITLE
ffmpeg錯誤退出

### ISSUE THREAD

**Issue by alfredt999** [SmallPeaches/DanmakuRender#123]
ffmpeg錯誤退出後就沒有重試錄製了. 關掉重開後正常錄. 請問是甚麼原因呢?

[DMR-20230925.log](https://github.com/SmallPeaches/DanmakuRender/files/12788894/DMR-20230925.log)

**Comment by SmallPeaches** [comment]
这个看起来像是卡在请求直播流地址了，但是没有报超时？你更新一下再观察几天看看？

**Comment by alfredt999** [comment]
更新了, 暫時沒出現同樣問題. 但還到另一問題. 不過錯誤出現後還沒開播就被我發現然後重開了. 不知道這個錯誤不管的話會不會影響錄製
error from callback <bound method Douyin._onError of <DMR.LiveAPI.danmaku.douyin.Douyin object at 0xffff87c94550>>: Connection to remote host was lost.
[2023-10-05 12:45:10,888][INFO]: tearing down on exception Connection to remote host was lost.
