### ISSUE TITLE
抖音解析房间号错误

### ISSUE THREAD

**Issue by Hertz221** [SmallPeaches/DanmakuRender#124]
其他房间都可以，就这个解析错误，这是为啥啊？
<img src="https://tu.wnflb2023.com/i/2023/10/04/173350.png" alt="屏幕截图 2023-10-04 173023" />

**Comment by Hertz221** [comment]
从电脑上获取了真实的房间地址解决了，可以录了。大佬我还想问个问题，就是如果我不想分段的话配置文件里的 segment 填“0”还是“~”呢，谢谢

**Comment by zxcec** [comment]
我之前设置的是99999，也可以不分段

**Comment by SmallPeaches** [comment]
0或者是~都行，但是强烈建议分段，不然主播断流一下没检测出来的话之后的视频都坏了

**Comment by Hertz221** [comment]
> 0或者是~都行，但是强烈建议分段，不然主播断流一下没检测出来的话之后的视频都坏了

好的，我倒没想过这个问题，感谢
