### ISSUE TITLE
建议将自动清理和上传功能分开

### ISSUE THREAD

**Issue by zxcec** [SmallPeaches/DanmakuRender#125]
我做录播一般只上传弹幕版，百度云自动备份原视频，额外上传一份到acfun。
现在是只能自动清理上传完的视频，不能连未上传的一起清理。
如果把两个功能分开就可以做到百度云自动备份

**Comment by SmallPeaches** [comment]
嗯，可以考虑设计一个上传完弹幕视频连带清理原视频的功能
