### ISSUE TITLE
渲染弹幕时的码率问题

### ISSUE THREAD

**Issue by Vae0514wzq** [SmallPeaches/DanmakuRender#127]
我在yml文件中设置了录制弹幕然后不启用自动渲染，在录制视频完成后，点开render_only.py手动渲染弹幕。我在default.yml中设置的渲染视频码率为5M，实际渲染过程中还是按照原来初始设定的15M来渲染的，这个没生效，想问下怎么生效
![Snipaste_2023-10-07_10-05-19](https://github.com/SmallPeaches/DanmakuRender/assets/65432819/448e62d3-08f4-4fc3-8166-4b3c71408f7a)
![Snipaste_2023-10-07_10-04-58](https://github.com/SmallPeaches/DanmakuRender/assets/65432819/49d0ef7e-5667-4753-abaa-75ea7428f4f0)

**Comment by SmallPeaches** [comment]
新版本应该改replay.yml里面的，default.yml里面的一般情况下不用改
