### ISSUE TITLE
弹幕引擎重启后直接卡死

### ISSUE THREAD

**Issue by zxcec** [SmallPeaches/DanmakuRender#128]
[Desktop.zip](https://github.com/SmallPeaches/DanmakuRender/files/12840491/Desktop.zip)
38分钟只有5分钟弹幕，我设置的是90秒重启

**Comment by SmallPeaches** [comment]
你是今天才出问题的吗？我看这里并没有报错，感觉像是远程没返回数据

**Comment by zxcec** [comment]
复现了，使用的是10月3日的这个版本，还是Cancel the future.

**Comment by zxcec** [comment]
[Desktop.zip](https://github.com/SmallPeaches/DanmakuRender/files/12845637/Desktop.zip)

**Comment by SmallPeaches** [comment]
> [Desktop.zip](https://github.com/SmallPeaches/DanmakuRender/files/12845637/Desktop.zip)

你这里面没有日志啊

**Comment by zxcec** [comment]
[DMR-20231009-2.log](https://github.com/SmallPeaches/DanmakuRender/files/12857952/DMR-20231009-2.log)
和之前一样，没有后续

**Comment by SmallPeaches** [comment]
那我在我这边复现一下看看

**Comment by SmallPeaches** [comment]
我看了下感觉像是弹幕重启的bug，你把获取弹幕超时自动重启关了试试？之后重启这里我再更新一下。
