### ISSUE TITLE
直播流读取错误

### ISSUE THREAD

**Issue by BEIJUUUUU** [SmallPeaches/DanmakuRender#13]
[6655-20230105-100947.log](https://github.com/SmallPeaches/DanmakuRender/files/10356806/6655-20230105-100947.log)

**Comment by SmallPeaches** [comment]
这个看起来没问题啊？也是程序也是正常结束退出的，是录制出来的视频有问题吗？

**Comment by BEIJUUUUU** [comment]
> 这个看起来没问题啊？也是程序也是正常结束退出的，是录制出来的视频有问题吗？

录制的个别视频无法正常播放，使用修复工具修复完成后画面撕裂到几乎不可用

**Comment by SmallPeaches** [comment]
你是什么时候开始有这个问题的？就这两天还是说一直有？

**Comment by BEIJUUUUU** [comment]
> 你是什么时候开始有这个问题的？就这两天还是说一直有？
> 

可以说是一直有，有些天就完全没问题，有些天就会有个一两P视频文件损坏无法打开，之前我一直以为是我的网络问题，但是最近换了电信的宽带依旧如此

**Comment by SmallPeaches** [comment]
那我研究一下看看是怎么回事，因为我看其他人并没有报告这样的问题

**Comment by SmallPeaches** [comment]
对了，你之前说403 forbidden之前的录制有这样的问题吗？然后录制出来有问题的是不是一般是最后一P？

**Comment by BEIJUUUUU** [comment]
> 对了，你之前说403 forbidden之前的录制有这样的问题吗？然后录制出来有问题的是不是一般是最后一P？

一般来说并不是最后一P有问题，是中间某一P有数据写入但是有问题无法打开，修复工具也救不回来。弹幕却是有完全正常记录和写入的，很怪

**Comment by SmallPeaches** [comment]
弹幕和视频本来就是分离的，弹幕正常也很正常。
你在两个星期前给我报告403 forbidden的问题之前录制有出过问题吗？

**Comment by BEIJUUUUU** [comment]
> 弹幕和视频本来就是分离的，弹幕正常也很正常。
> 你在两个星期前给我报告403 forbidden的问题之前录制有出过问题吗？

没记错的话也有，另外目前只要一开代理就会直接报错停止监控

**Comment by BEIJUUUUU** [comment]
> 弹幕和视频本来就是分离的，弹幕正常也很正常。 你在两个星期前给我报告403 forbidden的问题之前录制有出过问题吗？

今天依旧如此
![QQ截图20230107094741](https://user-images.githubusercontent.com/113653343/211125921-7ddb158c-10ed-419a-ae78-347d3c3256e4.png)

下面是log数据
[6655-20230106-191137.log](https://github.com/SmallPeaches/DanmakuRender/files/10365286/6655-20230106-191137.log)

**Comment by BEIJUUUUU** [comment]
这是开了代理后的情况
![QQ截图20230107095534](https://user-images.githubusercontent.com/113653343/211126215-3caed2cf-99a6-4912-94f1-bf796692ae7c.png)

**Comment by SmallPeaches** [comment]
你如果要用代理的话要在powershell里设置好，比如说用clash的话要在clash里面打开powershell
