### ISSUE TITLE
test-20231009-203533-Part000（带弹幕版）

### ISSUE THREAD

**Issue by Canda15** [SmallPeaches/DanmakuRender#130]
```
[2023-10-09 20:54:17,857][__init__][ERROR]: [WinError 183] 当文件已存在时，无法创建该文件。: './直播回放\\test-20231009-203533-Part000.flv' -> './直播回放\\冰凡丶bbg-2023年10月09日20点35分.flv'
```
![图片](https://github.com/SmallPeaches/DanmakuRender/assets/124772373/b8064eee-eb9e-4679-92a9-69b50952c176)

因为在20点35分 视频网络波动分了2次段。导致视频名称重复，出现报错。
小概率问题，就算出现了也不会影响正常上传。发个issue报告一下问题，如果开发者认为无需修复，直接关闭这个issue就行

[log.log](https://github.com/SmallPeaches/DanmakuRender/files/12849434/log.log)

**Comment by SmallPeaches** [comment]
喔，这个是预料之中的问题，因为你命名的时候时间是按分钟计算的嘛，所以说同一分钟肯定就冲突了（因为很自然的想法是不应该有两个不同的视频在同一分钟）。
你可以仿照传统录播软件那样命名精确到秒来表示就没问题了。

**Comment by Canda15** [comment]
好的
