### ISSUE TITLE
请问在哪里可以指定解码器？

### ISSUE THREAD

**Issue by lu621543** [SmallPeaches/DanmakuRender#131]
大佬，我遇到了和这个图片的相同情况，显卡是tesla p4
![2](https://github.com/SmallPeaches/DanmakuRender/assets/104936479/ad49d9b2-5f1f-4f66-9467-d6e84549039a)
就是CPU和编码器没用到，而解码器使用率很高，导致转码速度极慢
请问在代码哪里修改可以像这个博客一样的操作方式
原链接：https://blog.csdn.net/ramondq/article/details/127803494

**Comment by lu621543** [comment]
这里填空格都比填[-hwaccel, cuda]的转码速度快
![捕获](https://github.com/SmallPeaches/DanmakuRender/assets/104936479/a780b6d5-4b02-4010-88bf-50cb29704936)

**Comment by SmallPeaches** [comment]
按这篇文章的话应该是可以把解码器参数直接写在hwaccel_args上的

**Comment by lu621543** [comment]
好家伙，确实可以，提升了不少转码速度感谢大佬！！！
![捕获](https://github.com/SmallPeaches/DanmakuRender/assets/104936479/00d34190-ac1c-4a16-9d36-93332555b0c5)

**Comment by ddd-zero** [comment]
以前intel核显压视频的时候，感觉用d3d9好点,速度要快点，资源压力也低。
```
hwaccel_args: [-hwaccel,dxva2]
```

**Comment by itgoyo** [comment]
@lu621543 小伙伴，请问你P4用的什么散热？这边有个闲鱼DIY风扇散热，但是温度还是能跑到80-90多度

**Comment by lu621543** [comment]
> @lu621543 小伙伴，请问你P4用的什么散热？这边有个闲鱼DIY风扇散热，但是温度还是能跑到80-90多度

直接拿两个6025风扇再加上一个PWM温控开关，直接对着吹，我只用转解码，温度最高47度，声音也不大![IMG_20231016_182831.jpg](https://github.com/SmallPeaches/DanmakuRender/assets/104936479/92941f05-5c70-4c4c-ac48-f029d62c3c44)

**Comment by lu621543** [comment]
> 以前intel核显压视频的时候，感觉用d3d9好点,速度要快点，资源压力也低。
> ```
> hwaccel_args: [-hwaccel,dxva2]
> ```

等我重装群晖一定试试😂😂，我现在群晖刚换了套板U核显一直识别不了，只能用独显，等我有时间全部格式化后试试
