### ISSUE TITLE
请问可以在同一台电脑上一边直播一边录屏吗，对电脑的网络和性能要求高吗？

### ISSUE THREAD

**Issue by zihaoxingstudy1** [SmallPeaches/DanmakuRender#132]
请问可以在同一台电脑上一边直播一边录屏吗，对电脑的网络和性能要求高吗？

**Comment by SmallPeaches** [comment]
一边直播一边录屏为啥要用我这个？OBS应该是有边推流边保存的功能的吧

**Comment by zihaoxingstudy1** [comment]
> 一边直播一边录屏为啥要用我这个？OBS应该是有边推流边保存的功能的吧

1. 抖音现在有开发自己的直播伴侣直播客户端软件，我不清楚用obs推流的方式会不会被抖音允许和受限制影响。
2. 抖音的直播伴侣不能录制直播时候的弹幕和评论，我不清楚obs推流能不能录制抖音直播的弹幕评论

**Comment by SmallPeaches** [comment]
这样考虑的话也不是不行。我这个录制是不吃性能的，吃网络的量相当于你多开了个网页看直播。但是压制弹幕到视频会比较吃性能，如果你直播是游戏直播这种对性能要求高的话，建议是下播了之后手动渲染。

**Comment by zihaoxingstudy1** [comment]
> 这样考虑的话也不是不行。我这个录制是不吃性能的，吃网络的量相当于你多开了个网页看直播。但是压制弹幕到视频会比较吃性能，如果你直播是游戏直播这种对性能要求高的话，建议是下播了之后手动渲染。

嗯嗯，谢谢啊，下播了之后手动渲染弹幕到视频里这个软件可以完成吗，还是要到视频剪辑软件里去操作

**Comment by SmallPeaches** [comment]
可以，你看下使用文档有说

**Comment by zihaoxingstudy1** [comment]
> 可以，你看下使用文档有说

嗯嗯，好的，谢谢！
