### ISSUE TITLE
我想录制抖音的直播，但是默认要登陆b站的账号?

### ISSUE THREAD

**Issue by zihaoxingstudy1** [SmallPeaches/DanmakuRender#133]
![image](https://github.com/SmallPeaches/DanmakuRender/assets/58220227/0615402c-2757-421f-b30c-d1a31759bdf2)

**Comment by SmallPeaches** [comment]
你设置了自动上传B站的话就要，没有的话就不要，你应该是忘记改配置文件了

**Comment by zihaoxingstudy1** [comment]
> 你设置了自动上传B站的话就要，没有的话就不要，你应该是忘记改配置文件了

嗯嗯，谢谢，我把配置文件后面的上传b战的参数删掉后变好了
