### ISSUE TITLE
录制文件出错

### ISSUE THREAD

**Issue by BEIJUUUUU** [SmallPeaches/DanmakuRender#134]
[DMR-20231012.log](https://github.com/SmallPeaches/DanmakuRender/files/12883812/DMR-20231012.log)
前两小时录制文件正常，后面一个多小时的文件能打开有声音但是画面是花屏绿屏，试了试修复软件修复也不行，文件大小倒是正常。
或许是网络问题因为直播中断过。。。在海外用streamgears引擎会不会更好些？
![QQ截图20231012164833](https://github.com/SmallPeaches/DanmakuRender/assets/113653343/ead31ca8-ce96-4c67-b353-bdaf6bd455f3)

**Comment by SmallPeaches** [comment]
如果是断流的话的确会导致这种情况，目前也没找到很好的解决方法（所以说建议分段）
streamgears 应该会好一些。
