### ISSUE TITLE
检测开播的频率在哪里改

### ISSUE THREAD

**Issue by MAE5blog** [SmallPeaches/DanmakuRender#136]
都开播一分钟了才开始录制

**Comment by SmallPeaches** [comment]
这个目前改不了，太频繁请求容易被ban

**Comment by alfredt999** [comment]
之前用過biqiang和LyzenX的程式, 預設15秒或10秒檢測的. 幾個月沒被ban過. 不過我最多只是錄3個直播間. 多的話會不會ban就不知道了

**Comment by SmallPeaches** [comment]
那可以考虑一个这个选项
