### ISSUE TITLE
请问src_video和dm_video都上传的话，如何针对不同的投稿设置不同的封面呢？

### ISSUE THREAD

**Issue by itgoyo** [SmallPeaches/DanmakuRender#137]
![image](https://github.com/SmallPeaches/DanmakuRender/assets/23348551/e07eb742-f772-4e9f-9cfc-29a91122273a)

大佬，我看到教程的配置文件是这样子的，我也是这么用了

这边的需求是上传的时候如何指定有弹幕和无弹幕的封面呢？

```
replay:
  - url: https://www.douyu.com/123442
    segment: 3600
    danmaku: true
    upload:
      src_video:bilibili
		 cover:./1.png
      dm_video: bilibili
         cover:./2.png
```
可以这样子用么，虽然看到default.yml里面有设置cover的地方，但是好像对所有的上传都是同一个操作，我想要的效果是能不能区分开来，目前没有比较好的方法，我是启动两个脚本一个纯享版本，一个弹幕版本。或者说本来是可以的，这是用法不对。

**Comment by SmallPeaches** [comment]
别看B站教程，那个已经过时了。你看GitHub页面上的使用说明，有详细介绍的

**Comment by itgoyo** [comment]
好的感谢

**Comment by itgoyo** [comment]
@SmallPeaches  大佬，Github上面的usage也看了，但是还是没太懂具体有、无弹幕设置不同封面是如何设置的，如果您有时间话，可以简单的写一下事例代码么针对有弹幕的封面、无弹幕的封面，我这边看到了一个cover的入口，我这边没太懂python相关所谓的字典，自己也尝试了设置然后测试，但是没能出想要的效果，非常感谢！

**Comment by SmallPeaches** [comment]
你用新方法应该是复制的配置文件，而不是自己编写。那个复制的配置文件里面上传分为两个部分，一个是原视频，一个是弹幕视频，两个可以分别填cover的，你把两个不同的封面地址填上去就行了。

**Comment by itgoyo** [comment]
大概明白您的意思了，我这边晚点我这边再尝试一下，感谢
