### ISSUE TITLE
视频没有上传，在log文件夹下面有渲染字幕视频的日志，还有录制结束的日志，没开到上传相关的日志

### ISSUE THREAD

**Issue by itgoyo** [SmallPeaches/DanmakuRender#139]
如题，我怎么才能在项目里面知道我是否触发了上传的任务？（biliup-rs已经扫码.temp里面也有bilibili.json）我要怎么才能知道录制的状态，或者说是投稿的状态呢，里面的DMRxxx.log里面没有对应的信息，也不知道投稿是什么情况，账号没有稿件，但是直播回放和直播回放（带弹幕）是有视频文件的，或者说我需要手动再python3 main.py，这样子才会重新进入队列里面

**Comment by itgoyo** [comment]
不好意思，上传的日志在tmux attach过去之后看到了，是没找到封面的原因，这边还有一个问题，脚本重启之后本地视频文件好像没有触发上传，显示『直播结束，正在等待』，这样子是不是说昨晚的时候就没法触发上传了，只能自己去手动上传？

**Comment by SmallPeaches** [comment]
是的，目前上传还只能上传单次录制的，之前录制的不会自动上传

**Comment by itgoyo** [comment]
好的，感谢解答
