### ISSUE TITLE
错误报告

### ISSUE THREAD

**Issue by BEIJUUUUU** [SmallPeaches/DanmakuRender#14]
截图：
![QQ截图20230111232209](https://user-images.githubusercontent.com/113653343/211959927-e4dfcb7f-4512-4869-8070-69a69c3229aa.png)
![QQ截图20230112101335](https://user-images.githubusercontent.com/113653343/211959935-83d51fb4-26c5-4c86-81d3-4707104b18a4.png)

log文件：
[6655-20230111-232238.log](https://github.com/SmallPeaches/DanmakuRender/files/10397582/6655-20230111-232238.log)
[Render-20230111-232237.log](https://github.com/SmallPeaches/DanmakuRender/files/10397583/Render-20230111-232237.log)
[6655-20230111-133607.log](https://github.com/SmallPeaches/DanmakuRender/files/10397588/6655-20230111-133607.log)

控制台显示：
[控制台.txt](https://github.com/SmallPeaches/DanmakuRender/files/10397585/default.txt)

**Comment by SmallPeaches** [comment]
你可以试一下最新的v4分支，我把B站的直播流又改成了flv的，B站的hls流好像不太正常

**Comment by BEIJUUUUU** [comment]
> 你可以试一下最新的v4分支，我把B站的直播流又改成了flv的，B站的hls流好像不太正常

感谢！

**Comment by BEIJUUUUU** [comment]
> 你可以试一下最新的v4分支，我把B站的直播流又改成了flv的，B站的hls流好像不太正常

试了试，依旧有错误
Log：
[DMR-20230112.log](https://github.com/SmallPeaches/DanmakuRender/files/10398034/DMR-20230112.log)

然后控制台和log都显示录制结束正在等待，然后直播仍在继续
![QQ截图20230112115439](https://user-images.githubusercontent.com/113653343/211972336-f5849a4d-62d5-4923-bade-d0a9275e5c48.png)

**Comment by BEIJUUUUU** [comment]
> 你可以试一下最新的v4分支，我把B站的直播流又改成了flv的，B站的hls流好像不太正常

还有就是录制启动的时间异常长，大概要几分钟控制台才显示开始录制

**Comment by BEIJUUUUU** [comment]
刚重启了电脑，目前似乎就一切正常了

**Comment by SmallPeaches** [comment]
我这里好像没问题，你这里报直播结束应该是网络不太好，然后获取直播状态失败导致的
然后要开很久也是因为等服务器返回主播数据，等了8分钟

**Comment by SmallPeaches** [comment]
重启一下好了的话你先试着录一下看看

**Comment by BEIJUUUUU** [comment]
> 重启一下好了的话你先试着录一下看看

嗯，所以大概率还是网络问题吧
