### ISSUE TITLE
关于配置的问题请教

### ISSUE THREAD

**Issue by MoncozGC** [SmallPeaches/DanmakuRender#143]
很厉害的项目，佩服大佬！！！

在上传配置中有简介和标签两个参数。

我看默认提供的模板中关于简介有 **\n** 的符号，应该是换行的意思，但是实际上传后在B站中查看并没有换行是为什么呢？或者说有什么方式可以换行嘛

关于标签的参数，可不可以也用 {STREAMER}类似的参数，这样在配置多个主播时可以不用去具体改成主播的名称~

![image](https://github.com/SmallPeaches/DanmakuRender/assets/35448093/a2e7181e-05c2-4fdb-9725-60ffad101d6d)

**Comment by SmallPeaches** [comment]
应该是有换行的，你是不是打成/n了？然后新版的example.yml里面用了更友好的换行方式你可以看一下。
标签暂时还不能用自动替换。

**Comment by MoncozGC** [comment]
谢谢！用第二种方式确实可以
