### ISSUE TITLE
录制分辨率问题

### ISSUE THREAD

**Issue by BEIJUUUUU** [SmallPeaches/DanmakuRender#144]
[DMR-20231025.log](https://github.com/SmallPeaches/DanmakuRender/files/13168073/DMR-20231025.log)
![捕获](https://github.com/SmallPeaches/DanmakuRender/assets/113653343/4a9535ef-58f8-4625-b414-5f0fdb882bb4)

没记错的话大佬录制设置的是默认最高画质来着。
版本是最新的

**Comment by SmallPeaches** [comment]
应该是叔叔又加风控了，我研究一下。
