### ISSUE TITLE
最新代码录制B站直播出错

### ISSUE THREAD

**Issue by Vae0514wzq** [SmallPeaches/DanmakuRender#148]
![Snipaste_2023-10-26_17-54-11](https://github.com/SmallPeaches/DanmakuRender/assets/65432819/1e845818-6f32-4130-8e5f-9a593a0d6ebf)
如图，没有设置cookie，录制不了。

**Comment by SmallPeaches** [comment]
你如果愿意录480p的话就把bili force origin那个参数改成空。你如果要录制原画的话就得登录。

**Comment by chenfanz** [comment]
> 你如果愿意录480p的话就把bili force origin那个参数改成空。你如果要录制原画的话就得登录。

  我也是同样的报错，但是已经扫码登录了呀，.tmp文件里有cookie文件

**Comment by chenfanz** [comment]
def get_stream_url(self, 
                       flow_cdn=None, 
                       bili_watch_cookies=None,
                       account='bilibili',
                       bili_force_origin=('_1500',''), 
                       **kwargs,
        ) -> str:
        watch_cookies = {}
        bili_watch_cookies = f'./.temp/{account}.json'
        if bili_watch_cookies:
            try:
                with open(bili_watch_cookies, 'r') as f:
                    cookies = json.load(f)
                watch_cookies = {c['name']: c['value'] for c in cookies['cookie_info']['cookies']}
            except Exception as e:
                logging.warn(f'B站观看cookies设置错误:{e}，即将使用无登录模式')

**Comment by chenfanz** [comment]
> ```
> def get_stream_url(self, 
>                    flow_cdn=None, 
>                    bili_watch_cookies=None,
>                    account='bilibili',
>                    bili_force_origin=('_1500',''), 
>                    **kwargs,
>     ) -> str:
>     watch_cookies = {}
>     bili_watch_cookies = f'./.temp/{account}.json'
>     if bili_watch_cookies:
>         try:
>             with open(bili_watch_cookies, 'r') as f:
>                 cookies = json.load(f)
>             watch_cookies = {c['name']: c['value'] for c in cookies['cookie_info']['cookies']}
>         except Exception as e:
>             logging.warn(f'B站观看cookies设置错误:{e}，即将使用无登录模式')
> ```

这个方法调一下可以了
