### ISSUE TITLE
直播断流恢复后复读是否有办法解决？

### ISSUE THREAD

**Issue by BEIJUUUUU** [SmallPeaches/DanmakuRender#149]
录制的BiliBili直播间在断流之后就一直录制几秒内的相同画面复读，之后的所有分P都是直到直播间关闭停止录制。录制引擎是streamgears，大佬可否有办法解决？

**Comment by SmallPeaches** [comment]
控制台上有显示录制错误或者重启之类的字样吗？

**Comment by BEIJUUUUU** [comment]
![捕获](https://github.com/SmallPeaches/DanmakuRender/assets/113653343/fa52a1ee-7b5f-4add-b070-7b89be651cfe)
断流复读的位置是在画圈之间发生的，大概是5点08分，之后就都是复读断流前的几秒钟了

**Comment by SmallPeaches** [comment]
这样看起来streamgears根本没检测出来断流？你看看日志文件里面有显示什么吗？

**Comment by BEIJUUUUU** [comment]
[log.txt](https://github.com/SmallPeaches/DanmakuRender/files/13256661/log.txt)
这是断流发生中的10分钟的log，大概是在5点08分直播间开始断流，根据直播中弹幕推测大概三四分钟之后刷新就好了。断流的弹幕获取倒是正常

**Comment by BEIJUUUUU** [comment]
刚才又发生了同样的问题，应该就是streamgears没检测出来断流。直播间上应该是主播电脑直接关机了，然后几分钟之后重启了电脑重新开始推流，B站上刷新就好了，但是录制就一直重复断流前那几秒钟

**Comment by BEIJUUUUU** [comment]
顺便说下之前也有这种情况，如果是ffmpeg就几乎没有能重新恢复的机会，换用streamgears有时可以成功恢复正常录制

**Comment by SmallPeaches** [comment]
我这里没法修streamgears的问题，只能看看它那边有没有更新了。
你有没有用ffmpeg的日志，我看看它报错什么了？

**Comment by BEIJUUUUU** [comment]
暂时没有，之前ffmpeg录制引擎出问题之后就没用过了，我再试试看

**Comment by BEIJUUUUU** [comment]
终于又复现了一次，情况还是一样直播间断流恢复后录制的流复读断流前几秒一直持续好几P。下面是断流发生前十来分钟到直播结束的log文件，根据弹幕来看断流持续大概五六分钟，之后在网页端刷新就好了。大概断流时间是在18：34左右，弹幕提示恢复是在18：36左右。一共录制了大概两个小时的复读片段。在20：25时ffmpeg错误重启才恢复正常录制。此外复读片段的时间对不太上，指实际录制的文件显示持续1小时但是实际两P之间时间只过去半个小时（如图）。拜托大佬看看是什么问题，顺便说下另一台电脑上也出现同样问题但是引擎是streamgears。感谢！
![QQ截图20231128222033](https://github.com/SmallPeaches/DanmakuRender/assets/113653343/0e7a6a2b-bc29-42e7-a65a-6c56694f05da)

[log 2023-11-28.txt](https://github.com/SmallPeaches/DanmakuRender/files/13493285/log.2023-11-28.txt)

**Comment by SmallPeaches** [comment]
看日志文件的话应该是B站流的问题，主播断流但是B站不会断流，只会复读，所以说streamgears也没法检测。
这里唯一的异常只有一句`New subtitle stream 0:2 `，视频流里面多了个字幕流？你看看最前面刚刚开始录的时候ffmpeg对这个视频流的描述是怎么样的？

**Comment by BEIJUUUUU** [comment]
下面是昨天从开播到下播的全部日志。也就是说目前还无法通过ffmpeg和streamgears来检测出主播是否断流，有解决思路吗大佬？
[log.txt](https://github.com/SmallPeaches/DanmakuRender/files/13498836/log.txt)

**Comment by SmallPeaches** [comment]
目前来看是的，因为从ffmpeg的日志来看并没有任何异常，也没有报 Invalid NAL 之类的错误，唯一的区别就是多了个字幕流，如果下次再出现看看还会不会多这个字幕流？
还有一种解决思路是考虑换CDN，因为我自己之前也录过一段时间的B站直播，好像小主播没有这种问题，猜想有可能是B站的不同CDN或者是二压导致的问题。
