### ISSUE TITLE
错误报告  

### ISSUE THREAD

**Issue by BEIJUUUUU** [SmallPeaches/DanmakuRender#15]
后面几P无了
![QQ截图20230119064341](https://user-images.githubusercontent.com/113653343/213311623-56ab1efc-032f-4e31-8d48-e41c0f5736f5.png)

下面是log：
[DMR-20230118.log](https://github.com/SmallPeaches/DanmakuRender/files/10451774/DMR-20230118.log)

**Comment by SmallPeaches** [comment]
我想问问它是几点钟下播的，这里看log文件有很长一段时间是卡死没数据的
另外问问你的电脑在晚上3点半到四点半这段时间自动休眠了吗？

**Comment by BEIJUUUUU** [comment]
> 我想问问它是几点钟下播的，这里看log文件有很长一段时间是卡死没数据的
> 另外问问你的电脑在晚上3点半到四点半这段时间自动休眠了吗？

没记错是临晨5点半左右下播，电脑没自动休眠

**Comment by SmallPeaches** [comment]
那应该是程序卡住了，我研究一下
