### ISSUE TITLE
能不能直播创建个WIN版本

### ISSUE THREAD

**Issue by Tunny1985** [SmallPeaches/DanmakuRender#151]
能不能直播创建个WIN版本

**Comment by SmallPeaches** [comment]
直播创建个WIN版本是什么意思

**Comment by prettyby** [comment]
> 直播创建个WIN版本是什么意思

他的意思是 做一个可视化的软件界面
无需本地部署 开袋即食
当然了 我觉得哪怕收费都可以
前提是保证平台规则变动可以第一时间更新
因为同时支持多平台弹幕录制的软件 太少了
我看其他人那边有支持弹幕 礼物 直播间人数/人气/热度 的
可以考虑更新上来 ！感谢！

**Comment by SmallPeaches** [comment]
目前还没有可视化的计划，考虑到版权问题也不方便做收费软件，之后很长一段时间应该还是以Python程序的形式更新。
不过如果其他人有一些比较好的功能和想法可以考虑加进去，可以单独开个issue讨论一下。
