### ISSUE TITLE
linux ubuntu 搭建的没看懂啊 运行不起来 能不能来个 实战教学啊

### ISSUE THREAD

**Issue by cookrs** [SmallPeaches/DanmakuRender#155]

**Comment by ixjx** [comment]
linux需要自行下载ffmpeg和其他几个依赖工具

**Comment by cookrs** [comment]
> linux需要自行下载ffmpeg和其他几个依赖工具

我安装了  依旧不行

**Comment by ixjx** [comment]
看看报错，缺什么就装什么

**Comment by SmallPeaches** [comment]
所以说你到底报错什么呢？什么描述都没有怎么给你解决？

**Comment by cookrs** [comment]
> 所以说你到底报错什么呢？什么描述都没有怎么给你解决？

就是一换到Linux不知道该运行哪个程序才能让开始录制    整不会了

**Comment by cookrs** [comment]
> 看看报错，缺什么就装什么

就是一换到Linux不知道该运行哪个程序才能让开始录制 整不会了

**Comment by SmallPeaches** [comment]
和Windows一样啊，运行main.py就行了

**Comment by cookrs** [comment]
> 和Windows一样啊，运行main.py就行了

没整明白  运行不了
