### ISSUE TITLE
Oracle ARM ubuntu20.04  渲染的时候报错 

### ISSUE THREAD

**Issue by cookrs** [SmallPeaches/DanmakuRender#156]
[h264 @ 0xaaaaed1d7100] No start code is found.
[h264 @ 0xaaaaed1d7100] Error splitting the input into NAL units.
[NULL @ 0xaaaaed14c830] missing picture in access unit with size 21432
Error while decoding stream #0:0: Invalid data found when processing input
[h264 @ 0xaaaaed175930] Invalid NAL unit 4, skipping.
[h264 @ 0xaaaaed175930] no frame!
Too many packets buffered for output stream 0:1.
[aac @ 0xaaaaed174e20] Qavg: 49238.344
[aac @ 0xaaaaed174e20] 2 frames left in the queue on closing
Conversion failed!

这是咋回事啊  编码器选的libx264

**Comment by cookrs** [comment]
![微信图片_20231209175715](https://github.com/SmallPeaches/DanmakuRender/assets/94035608/2c230453-19f7-4c51-a44c-153b28c693e4)
渲染完弹幕是这个样子的

**Comment by systemtang** [comment]
看着像是字体缺失的样子

**Comment by cookrs** [comment]
> 看着像是字体缺失的样子

总是第一段视频渲染弹幕报错  很奇怪

**Comment by cookrs** [comment]
并且录制的时候设置了分段，渲染的时候不会分段？录制文件大小900mb，弹幕文件2m，渲染之后的文件跑到了1.3G大小还没停止

**Comment by systemtang** [comment]
> > 看着像是字体缺失的样子
> 
> 总是第一段视频渲染弹幕报错 很奇怪

如果只有第一段报错可能有几种原因，
首先检查配置文件里配置的字体设置（即**font**配置项），和录制的**ass**文件内的字体是否一致，应该在ass文件的[V4+ Styles]下，大概10行的位置

如果字体一样，渲染报错的话，首先应该贴出报错内容，盲猜的话有可能是录制第一段时出现bug，你可以下载你的flv文件到本地查看是否能正常播放，我这边有遇到在录制第一段时只有音频流，视频流全黑的情况。也有可能是ffmpeg的问题导致的，如果你所有录制作业都是第一段固定出现问题，最好重装环境和本项目。最极端的情况下，你可以下载你的视频和弹幕到本地，然后用其他工具实现整合。





> 并且录制的时候设置了分段，渲染的时候不会分段？录制文件大小900mb，弹幕文件2m，渲染之后的文件跑到了1.3G大小还没停止

不清楚你的具体录制配置，但我这边每个flv文件都会配一个ass文件，渲染时两两对应，所以理论上分段是正常进行的。你也可以用手动执行python脚本【**render_only.py**】并在提示下输入目录位置，程序会扫描出所有可以渲染的项目。
渲染后的文件大概会变成原本视频文件的1.5~2倍甚至更高，是正常情况，而且非常占用资源，如果你有NVIDIA显卡的话会有加速，否则只能CPU跑，速度会慢很多。

**Comment by cookrs** [comment]
> > > 看着像是字体缺失的样子
> > 
> > 
> > 总是第一段视频渲染弹幕报错 很奇怪
> 
> 如果只有第一段报错可能有几种原因， 首先检查配置文件里配置的字体设置（即**font**配置项），和录制的**ass**文件内的字体是否一致，应该在ass文件的[V4+ Styles]下，大概10行的位置
> 
> 如果字体一样，渲染报错的话，首先应该贴出报错内容，盲猜的话有可能是录制第一段时出现bug，你可以下载你的flv文件到本地查看是否能正常播放，我这边有遇到在录制第一段时只有音频流，视频流全黑的情况。也有可能是ffmpeg的问题导致的，如果你所有录制作业都是第一段固定出现问题，最好重装环境和本项目。最极端的情况下，你可以下载你的视频和弹幕到本地，然后用其他工具实现整合。
> 
> > 并且录制的时候设置了分段，渲染的时候不会分段？录制文件大小900mb，弹幕文件2m，渲染之后的文件跑到了1.3G大小还没停止
> 
> 不清楚你的具体录制配置，但我这边每个flv文件都会配一个ass文件，渲染时两两对应，所以理论上分段是正常进行的。你也可以用手动执行python脚本【**render_only.py**】并在提示下输入目录位置，程序会扫描出所有可以渲染的项目。 渲染后的文件大概会变成原本视频文件的1.5~2倍甚至更高，是正常情况，而且非常占用资源，如果你有NVIDIA显卡的话会有加速，否则只能CPU跑，速度会慢很多。

报错内容我上边发过了  第一个就是    还有我渲染完成之后  弹幕全成了上边发的那个图片的小方框，你所说的V4+ styles下只有三行  我看到有跟配置文件字体一样的  microsoft yahei
![0419D5D9-D52A-4A7B-AF07-5B9FDAC61F25](https://github.com/SmallPeaches/DanmakuRender/assets/94035608/cb7bc989-a886-4111-8c3f-b7ca988633fa)

**Comment by SmallPeaches** [comment]
> [h264 @ 0xaaaaed1d7100] No start code is found. [h264 @ 0xaaaaed1d7100] Error splitting the input into NAL units. [NULL @ 0xaaaaed14c830] missing picture in access unit with size 21432 Error while decoding stream #0:0: Invalid data found when processing input [h264 @ 0xaaaaed175930] Invalid NAL unit 4, skipping. [h264 @ 0xaaaaed175930] no frame! Too many packets buffered for output stream 0:1. [aac @ 0xaaaaed174e20] Qavg: 49238.344 [aac @ 0xaaaaed174e20] 2 frames left in the queue on closing Conversion failed!
> 
> 这是咋回事啊 编码器选的libx264

这个报错看起来像是视频文件本身损坏无法解码了，所以说报错了。

> 报错内容我上边发过了 第一个就是 还有我渲染完成之后 弹幕全成了上边发的那个图片的小方框，你所说的V4+ styles下只有三行 我看到有跟配置文件字体一样的 microsoft yahei ![0419D5D9-D52A-4A7B-AF07-5B9FDAC61F25](https://private-user-images.githubusercontent.com/94035608/289337065-cb7bc989-a886-4111-8c3f-b7ca988633fa.jpeg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDIxODQ3NzksIm5iZiI6MTcwMjE4NDQ3OSwicGF0aCI6Ii85NDAzNTYwOC8yODkzMzcwNjUtY2I3YmM5ODktYTg4Ni00MTExLThjM2YtYjdjYTk4ODYzM2ZhLmpwZWc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjEwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIxMFQwNTAxMTlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02YTU2NDZlYmQ4M2QzNWMxMjFkOTk2YTcwODhjZWY4MGQ0YTgwZGNiNjk0ZWE3YTVkZmY2MGE4ZThkYzY0NWU3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.uUEvzBFU0s6NJrfU30kQl4tQt9aqk_WkSyEGnIQkM-U)

这个结合你的图片来看应该就是字体没安装好（Linux没有微软雅黑字体），然后系统也没找到合适的可以替换的字体。你录制的时候换一个字体或者安装微软雅黑就好了。

**Comment by SmallPeaches** [comment]
> 并且录制的时候设置了分段，渲染的时候不会分段？录制文件大小900mb，弹幕文件2m，渲染之后的文件跑到了1.3G大小还没停止

然后这个渲染文件比较大是正常的，默认情况下得到的带弹幕视频一个小时大概会有5-6GB，你如果需要修改的话可以参考文档改一下。

**Comment by cookrs** [comment]
> > 并且录制的时候设置了分段，渲染的时候不会分段？录制文件大小900mb，弹幕文件2m，渲染之后的文件跑到了1.3G大小还没停止
> 
> 然后这个渲染文件比较大是正常的，默认情况下得到的带弹幕视频一个小时大概会有5-6GB，你如果需要修改的话可以参考文档改一下。

具体需要修改哪一项呢？有什么影响吗

**Comment by SmallPeaches** [comment]
> 具体需要修改哪一项呢？有什么影响吗

replay.yml里面的vencoder_args，改低码率画质会差一点，你自己平衡咯。
