### ISSUE TITLE
请教Intel® UHD Graphics应该如何选择硬件解码参数和编码器

### ISSUE THREAD

**Issue by ajiangstudy** [SmallPeaches/DanmakuRender#157]
以下是我的配置，我发现CPU已经跑满，但是GPU没有使用，如何能使用GPU编码，加快渲染速度
 硬件解码参数，默认由FFmpeg自动判断，如果出现问题可以设为空
  hwaccel_args: [ ]

  视频编码器，NVIDIA设置为h264_nvenc，AMD设置为h264_amf，CPU设置为libx264
  vencoder: libx264
![image](https://github.com/SmallPeaches/DanmakuRender/assets/32857102/9665b93d-60b4-410a-b54c-e7d9d5bccee9)

**Comment by ajiangstudy** [comment]
开发者您好，经过我一上午测试，我发现使用h264_qsv - h264_qsv是可以在命令行正常执行的，但是replay.yml中写h264_qsv会报错说硬件加速只有cuda,qsv,d3d11va,opencl,vulkan等。如果我replay中写qsv会进行报错。请问这个是代码限制不让写h264_qsv还是ffmpeg官方禁止使用。
ffmpeg -c:v h264_qsv -i .\a.flv -c:v h264_qsv output.mp4
![image](https://github.com/SmallPeaches/DanmakuRender/assets/32857102/5c28114d-8987-40d7-b14c-185e73d624d6)
***
replay.yml中写h264_qsv
[vist#0:0/h264 @ 000001e07f266480] Unrecognized hwaccel: h264_qsv.
[vist#0:0/h264 @ 000001e07f266480] Supported hwaccels: cuda qsv d3d11va opencl vulkan
Error opening input file ./.flv.
Error opening input files: Invalid argument

***
replay中写qsv
```
 hwaccel_args: [-hwaccel, qsv]
```
Impossible to convert between the formats supported by the filter 'graph 0 input from stream 0:0' and the filter 'auto_scale_0'
[vf#0:0 @ 0000019197f7cf00] Error reinitializing filters!
Failed to inject frame into filter network: Function not implemented
Error while filtering: Function not implemented
[out#0/mp4 @ 0000019197d80ec0] Nothing was written into output file, because at least one of its streams received no packets.

**Comment by SmallPeaches** [comment]
hwaccel_args的位置是在-i之前的，你应该直接写[-c:v, h264_qsv]就行了。

**Comment by ajiangstudy** [comment]
> hwaccel_args的位置是在-i之前的，你应该直接写[-c:v, h264_qsv]就行了。

感谢这样设置有效，额外问一句，stream 0:1 aac是否支持指定硬件加速

**Comment by SmallPeaches** [comment]
aac是音频流，好像没听说过有音频用硬件加速的（音频编码很快，应该没有硬件加速的必要）。
