### ISSUE TITLE
2个问题 虎牙 断流重启慢 抖音弹幕出界 的问题

### ISSUE THREAD

**Issue by prettyby** [SmallPeaches/DanmakuRender#158]
1.5年前的笔记本，1060显卡
2.添加了60多个主播 抖音 虎牙都有
3.虎牙录制一个主播5小时，其中断流差不多15分钟没有重新录制，导致缺失，抖音目前看没有断流
4.如图，抖音弹幕会出界，设置基本默认，只有两处小改 

![弹幕出界](https://github.com/SmallPeaches/DanmakuRender/assets/153463728/f32b265b-97d4-467c-8f44-ece15e80e8c2)
 
![弹幕设置](https://github.com/SmallPeaches/DanmakuRender/assets/153463728/a14b8236-7696-4b0a-b9bb-82bf830552c0)

**Comment by SmallPeaches** [comment]
1.如果这个主播经常断流（例如户外主播），建议是用streamgears来录制，FFmpeg检测不太灵敏。
2.这个越界是屏幕上方越界了？能否截图ass文件的内容来看看？（理论上不同平台录制的弹幕在处理的时候都是一样的，不会出现一个平台的弹幕大，一个平台弹幕小）

**Comment by prettyby** [comment]
> 1.如果这个主播经常断流（例如户外主播），建议是用streamgears来录制，FFmpeg检测不太灵敏。 2.这个越界是屏幕上方越界了？能否截图ass文件的内容来看看？（理论上不同平台录制的弹幕在处理的时候都是一样的，不会出现一个平台的弹幕大，一个平台弹幕小）

1.是户外主播，已经改了streamgears模式，观察下，另外抖音是否也改成streamgears这个模式？
2.那个主播的ASS删了，也不是很频繁，回头再看一下
3.打比方我在运行程序中图，添加了一个新主播.yml 如何在不关闭py.exe窗口的情况下，开始录制新主播？
4.有没有暂停录制的快捷键（目的是希望它在我需要的时间点渲染弹幕，并继续录制）
5.抖音有一段1小时录播，前25分钟有弹幕，后面没弹幕，图1是1小时的ASS 有2600多行，图2也是1小时视频但是只有960多条

![1](https://github.com/SmallPeaches/DanmakuRender/assets/153463728/55f4e34b-c1b7-4d08-98a5-174872f90e4a)

![2](https://github.com/SmallPeaches/DanmakuRender/assets/153463728/c2e7a86c-662e-4f12-a9ab-2d21de1e7f89)

**Comment by SmallPeaches** [comment]
1.理论上都可以用，但是推荐户外主播用streamgears，PC推流的主播用ffmpeg，因为streamgears有问题的话我解决不了。
3.4. 暂时还没这个功能。不过推荐你录超过5个主播的时候重新开一个。
5. 你这两个视频顺序是怎样的，第一个视频弹幕有一小时15分钟？你发日志来看看。

**Comment by prettyby** [comment]
> 1.理论上都可以用，但是推荐户外主播用streamgears，PC推流的主播用ffmpeg，因为streamgears有问题的话我解决不了。 3.4. 暂时还没这个功能。不过推荐你录超过5个主播的时候重新开一个。 5. 你这两个视频顺序是怎样的，第一个视频弹幕有一小时15分钟？你发日志来看看。

解析房间失败 main窗口闪退
重新解压缩 无法解决 

![2](https://github.com/SmallPeaches/DanmakuRender/assets/153463728/da63e5ab-303f-4196-9366-ac2dd4810f4a)

![3](https://github.com/SmallPeaches/DanmakuRender/assets/153463728/1e18994e-4d88-4576-8254-3588ea47de0e)

![1](https://github.com/SmallPeaches/DanmakuRender/assets/153463728/07d7be3d-3491-4ffa-84a1-743cf2bf9149)

**Comment by prettyby** [comment]
> 1.理论上都可以用，但是推荐户外主播用streamgears，PC推流的主播用ffmpeg，因为streamgears有问题的话我解决不了。 3.4. 暂时还没这个功能。不过推荐你录超过5个主播的时候重新开一个。 5. 你这两个视频顺序是怎样的，第一个视频弹幕有一小时15分钟？你发日志来看看。

ffmpeg模式花屏，有什么好办法可以修复么？

![5daf6804c3abb7b1ae214ba11e566faa](https://github.com/SmallPeaches/DanmakuRender/assets/153463728/f97fb127-6232-4ac8-af74-9efbdbd5df68)

**Comment by SmallPeaches** [comment]
你看下是不是因为主播断流导致的？如果是的话这种情况目前只能用streamgears解决。

**Comment by prettyby** [comment]
请问如何设置渲染弹幕 同时进行多个视频
目前排队没必要
有时候队列任务多 我都手动渲染 机器也不卡

上面花屏问题我观察了一下
两台机器分别录制 要花屏都花屏 但是渲染以后就好了
偶尔有一次渲染之后还是花 是streamgears模式
ffmpeg模式暂时没事

**Comment by SmallPeaches** [comment]
replay.yml里面有个选项叫nrenders，调高就行了

**Comment by prettyby** [comment]
> replay.yml里面有个选项叫nrenders，调高就行了

好的找到了
最近发现 有台机器5年前的配置 1060显卡的 
ffmpeg 模式，弹幕会异常，重试 然后要么漏掉很多 要么干脆就是1KB的弹幕文件
卡住以后，对着窗口鼠标右键点击一下，如图1 

![1](https://github.com/SmallPeaches/DanmakuRender/assets/153463728/1f754f56-0ec2-4175-ba7c-75e66feacd9c)

有一台今年的机器 4060的 很少出现这个问题 但也会有漏掉
我经常为了录制几个主播，两台机器跑一样的内容 
然后合并来用 

另外，微信视频号的录制可以加进去么？

**Comment by SmallPeaches** [comment]
> 好的找到了 最近发现 有台机器5年前的配置 1060显卡的 ffmpeg 模式，弹幕会异常，重试 然后要么漏掉很多 要么干脆就是1KB的弹幕文件 卡住以后，对着窗口鼠标右键点击一下，如图1
> 
> ![1](https://private-user-images.githubusercontent.com/153463728/291235184-1f754f56-0ec2-4175-ba7c-75e66feacd9c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI5OTA2NjEsIm5iZiI6MTcwMjk5MDM2MSwicGF0aCI6Ii8xNTM0NjM3MjgvMjkxMjM1MTg0LTFmNzU0ZjU2LTBlYzItNDE3NS1iYTdjLTc1ZTY2ZmVhY2Q5Yy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjE5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIxOVQxMjUyNDFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lY2M3ZTc2NDE0Y2RlYWE0MzlhNjM1MDJmM2JmMzk0ZGNmNzhhNWYyMWU3NGU4Mjc3OWQxNjIxNTdlMTA1MzY1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.paiirbmDm2X4uj4EfeGhhNbqPEdpUbILPKMEqrwv8wU)
> 
> 有一台今年的机器 4060的 很少出现这个问题 但也会有漏掉 我经常为了录制几个主播，两台机器跑一样的内容 然后合并来用
> 
> 另外，微信视频号的录制可以加进去么？

你这个看起来像是点到左键，程序暂停了（Windows的CMD和powershell都有这个问题，你不能在控制台点左键，这样会暂停程序让你在控制台上面复制东西。推荐使用Windows 11的Windows terminal）。

新平台的兼容暂时不考虑，没时间弄（当然你弄了的话也欢迎pull request）。

**Comment by prettyby** [comment]
> > 好的找到了 最近发现 有台机器5年前的配置 1060显卡的 ffmpeg 模式，弹幕会异常，重试 然后要么漏掉很多 要么干脆就是1KB的弹幕文件 卡住以后，对着窗口鼠标右键点击一下，如图1
> > ![1](https://private-user-images.githubusercontent.com/153463728/291235184-1f754f56-0ec2-4175-ba7c-75e66feacd9c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI5OTA2NjEsIm5iZiI6MTcwMjk5MDM2MSwicGF0aCI6Ii8xNTM0NjM3MjgvMjkxMjM1MTg0LTFmNzU0ZjU2LTBlYzItNDE3NS1iYTdjLTc1ZTY2ZmVhY2Q5Yy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjE5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIxOVQxMjUyNDFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lY2M3ZTc2NDE0Y2RlYWE0MzlhNjM1MDJmM2JmMzk0ZGNmNzhhNWYyMWU3NGU4Mjc3OWQxNjIxNTdlMTA1MzY1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.paiirbmDm2X4uj4EfeGhhNbqPEdpUbILPKMEqrwv8wU)
> > 有一台今年的机器 4060的 很少出现这个问题 但也会有漏掉 我经常为了录制几个主播，两台机器跑一样的内容 然后合并来用
> > 另外，微信视频号的录制可以加进去么？
> 
> 你这个看起来像是点到左键，程序暂停了（Windows的CMD和powershell都有这个问题，你不能在控制台点左键，这样会暂停程序让你在控制台上面复制东西。推荐使用Windows 11的Windows terminal）。
> 
> 新平台的兼容暂时不考虑，没时间弄（当然你弄了的话也欢迎pull request）。

1. 一般主播下播后，最后一个弹幕和视频文件会是不同的名字
有一半概率因为名字不同不会自动渲染
一般都是抖音会有这个问题

![73d85656a66513796179280dc774518f](https://github.com/SmallPeaches/DanmakuRender/assets/153463728/9a9e788d-c97d-4e8d-9af8-dd172066d4ad)

2. ffmpeg（1060机器）和streamgears（4060机器）模式分别两台机器，同一个主播FLV源文件，
一个804 MB 一个810 MB
渲染后 4.67G   4.06G
时长93分钟     87分钟    
ffmpeg（1060机器）时长多 5分钟
主播中间有下播一次
不太理解是为什么 

3.下面是抖音的语音直播间，录制出来是纯黑屏，渲染以后字幕基本看不清
如果加一个背景的话，就正常了

![要好好睡觉 好好戒酒 2023年12月11日0点（带弹幕版） 00-36-55 20231224-044643595](https://github.com/SmallPeaches/DanmakuRender/assets/153463728/25dfdcc5-d548-4cfc-8232-b35cd071b87e)

**Comment by SmallPeaches** [comment]
> 1. 一般主播下播后，最后一个弹幕和视频文件会是不同的名字
>    有一半概率因为名字不同不会自动渲染
>    一般都是抖音会有这个问题
> 
> ![73d85656a66513796179280dc774518f](https://private-user-images.githubusercontent.com/153463728/292614779-9a9e788d-c97d-4e8d-9af8-dd172066d4ad.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDM3NTE3NzYsIm5iZiI6MTcwMzc1MTQ3NiwicGF0aCI6Ii8xNTM0NjM3MjgvMjkyNjE0Nzc5LTlhOWU3ODhkLWM5N2QtNGU4ZC05YWY4LWRkMTcyMDY2ZDRhZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjI4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIyOFQwODE3NTZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hYjMzNTVhMjQ2ZGE2MTBmNDMwMDVjZjY4NmE2NTI4MTY3ZDBhNDdiZjg1MjAwYzk2ODkwOWY0Zjc5YjNlNzhmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.SUHkttNRbVgriPg1cxDV4gtl9zheRfJ11otf-QZfwWs)
> 
> 2. ffmpeg（1060机器）和streamgears（4060机器）模式分别两台机器，同一个主播FLV源文件，
>    一个804 MB 一个810 MB
>    渲染后 4.67G   4.06G
>    时长93分钟     87分钟
>    ffmpeg（1060机器）时长多 5分钟
>    主播中间有下播一次
>    不太理解是为什么
> 
> 3.下面是抖音的语音直播间，录制出来是纯黑屏，渲染以后字幕基本看不清 如果加一个背景的话，就正常了
> 
> ![要好好睡觉 好好戒酒 2023年12月11日0点（带弹幕版） 00-36-55 20231224-044643595](https://private-user-images.githubusercontent.com/153463728/292644846-25dfdcc5-d548-4cfc-8232-b35cd071b87e.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDM3NTE3NzYsIm5iZiI6MTcwMzc1MTQ3NiwicGF0aCI6Ii8xNTM0NjM3MjgvMjkyNjQ0ODQ2LTI1ZGZkY2M1LWQ1NDgtNGNmYy04MjMyLWIzNWNkMDcxYjg3ZS5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjI4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIyOFQwODE3NTZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03YTE0MTRiMDVmMDI3MGNhZDU0M2JlMGQyOGVjZDRkNmQ0YTdhODVlNTg0NDhmNGIyYmQ3Mzk4OWZhN2ZhZjljJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.guLqPtF7SAdcWVO2gsPse7Rrmq-4xDH8vwXVPh6Fv3k)

1. 这个问题好像没听有人汇报过？你要拿日志来看看才知道是怎么回事。
2. 有可能是可变帧率视频（VFR）的原因？ffmpeg录制时，视频是经过重新封装的，而streamgears具体我不清楚它内部实现，有可能VFR的视频直接当做固定帧率处理了。
3. 纯语音直播间说实话我也不知道会发生什么，图片上看应该是视频分辨率太低导致的？

**Comment by prettyby** [comment]
请问这些内容该如何更新呢？

![11](https://github.com/SmallPeaches/DanmakuRender/assets/153463728/428d800d-dea7-46b7-814d-e7c230718366)


KTV模式直播间无法录制

![22](https://github.com/SmallPeaches/DanmakuRender/assets/153463728/a7975bc5-89c0-4729-acba-e7b707581ddb)

**Comment by SmallPeaches** [comment]
这里已经推送更新了，KTV直播间是什么？是这个直播间专门做KTV还是说只是类似PK那样的一种活动？

**Comment by prettyby** [comment]
> 这里已经推送更新了，KTV直播间是什么？是这个直播间专门做KTV还是说只是类似PK那样的一种活动？

我用几个软件都尝试过
语音聊体室就是全黑屏
KTV模式都录制不下来

![66428d5670191e322a5638faf7be1720_720](https://github.com/SmallPeaches/DanmakuRender/assets/153463728/9dcefe97-7e22-41a0-ba66-a8f2d34aa920)

**Comment by SmallPeaches** [comment]
这样吧，你发几个直播间过来（要电脑端的），我在它直播的时候试一下研究一下
