### ISSUE TITLE
Websocket Closed 弹幕下载线程异常退出，正在重试

### ISSUE THREAD

**Issue by foeris** [SmallPeaches/DanmakuRender#160]
![微信截图_20231213081943](https://github.com/SmallPeaches/DanmakuRender/assets/50254365/bfb436b8-06df-4140-836e-edebc7781c91)

**Comment by SmallPeaches** [comment]
网络断了一下吧？同时也有getaddrinfo failed。

**Comment by foeris** [comment]
网络波动了一下随后并没有重新开始下载

**Comment by SmallPeaches** [comment]
抖音的吗？如果是抖音的话目前自动重试有点问题。

**Comment by foeris** [comment]
不是，是斗鱼

**Comment by SmallPeaches** [comment]
你发一下整个日志来看看？

**Comment by foeris** [comment]
[DMR-20231212-7.log](https://github.com/SmallPeaches/DanmakuRender/files/13776809/DMR-20231212-7.log)

辛苦了，另外想问一下，检测开播时间的那个参数加了好像没用？

**Comment by SmallPeaches** [comment]
我看了下日志的确是一直在重试，你看日志的6651行，一直重试到1:24都是getaddrinfo failed，也许是斗鱼有特别的限制？

**Comment by foeris** [comment]
应该是斗鱼有限制吧，其它的重试是能连上的
