### ISSUE TITLE
大佬 录制虎牙直播部分游戏卡顿

### ISSUE THREAD

**Issue by NoColorPiggg** [SmallPeaches/DanmakuRender#167]
其他游戏都没问题，一玩帝国时代2录制就会一卡一卡的，不知道是我电脑配置的问题还是什么
19：42那段，十分钟时候开始的帝国时代
[Uploading DMR-20231220.log…]()

**Comment by SmallPeaches** [comment]
你这个文件没传好，这里看不了。
你试下其他直播间播这个游戏的看看？感觉不会因为内容掉帧吧？
