### ISSUE TITLE
设置bili_watch_cookies为空在哪设置

### ISSUE THREAD

**Issue by Marshallwjz** [SmallPeaches/DanmakuRender#168]
![微信图片_20231221231707](https://github.com/SmallPeaches/DanmakuRender/assets/129115417/2ff7cba0-5e77-45b8-aa11-3cbdd068c575)
即将登录用于B站获取直播流的账号，如果不想登录请设置bili_watch_cookies为空。
录制B站直播间就会卡在这，登录账号也说存在风险没法成功登录，所以这个在哪个文件里面设置啊

**Comment by SmallPeaches** [comment]
改的方法使用文档里面有说，但是不登录没法录制原画直播喔（除非那个主播只有原画）。
登录按道理来说扫码登录是没问题的，密码登录可能不行。
