### ISSUE TITLE
录制虎牙时显示配置文件（已解决）

### ISSUE THREAD

**Issue by dream-bowen** [SmallPeaches/DanmakuRender#169]
配置文件读取错误: 'NoneType' object is not subscriptable，抖音/cc/b站都正常添加直播间，求救

**Comment by SmallPeaches** [comment]
我这里试虎牙是没问题的，你看看是不是填的链接有问题（要是`https://www.huya.com/xxxx`这种格式的），如果还不行的话过段时间再试试？

**Comment by dream-bowen** [comment]
#直播间
replay:
  - url: https://www.huya.com/28247675
    segment: 3600
  - url: https://live.douyin.com/638105403446
    segment: 3600
    danmaku: false   # 指定此任务不需要录制弹幕
一直是这样的格式，正常我也不会随便改，是忽然不能录了我一脸懵逼
