### ISSUE TITLE
压制完成的弹幕视频第一p会上传到前一日的视频中

### ISSUE THREAD

**Issue by Sora3QwQ** [SmallPeaches/DanmakuRender#170]
压制完成的弹幕视频第一p会上传到前一日的视频中，从第2p开始会正常新开一个视频
完整的log日志
[DMR-20231219(23号-24号中午).log](https://github.com/SmallPeaches/DanmakuRender/files/13761357/DMR-20231219.23.-24.log)
下面为故障的时间点
[2023-12-23 22:52:14,145]  第一分p上传完毕   上传到前一日视频中
[2023-12-23 23:54:21,178]  第二分p上传完毕    新开一个bv
另一个主播
[2023-12-24 14:25:08,067] 第一分p上传完毕    到前一日视频中
[2023-12-24 14:29:02,873] 第二分p上传完毕    新开一个bv

**Comment by Sora3QwQ** [comment]
延迟下播计时的设置是3分钟 
end_cnt: 3

**Comment by SmallPeaches** [comment]
有没有前一天视频的日志？我想看看上一个视频的终止信号被发到哪里去了。

**Comment by laomu61996** [comment]
[Uploading DMR-20231219.log…]()

**Comment by Sora3QwQ** [comment]
[DMR-20231219.log](https://github.com/SmallPeaches/DanmakuRender/files/13761822/DMR-20231219.log)
这个是完整的

**Comment by SmallPeaches** [comment]
有没有BV1rG411k7jD对应那天的日志？你现在给的这个来看看不出什么问题。

**Comment by laomu61996** [comment]
[Uploading 2023-12-22.log…]()

**Comment by laomu61996** [comment]
[Uploading 2023-12-22.log…]()

**Comment by laomu61996** [comment]
[Uploading 2023-12-22.log…]()

**Comment by laomu61996** [comment]
[Uploading 2023-12-22.log…]()
这个是前一天的

**Comment by Sora3QwQ** [comment]
[2023-12-22.log](https://github.com/SmallPeaches/DanmakuRender/files/13766925/2023-12-22.log)
