### ISSUE TITLE
自动清理逻辑问题

### ISSUE THREAD

**Issue by zxcec** [SmallPeaches/DanmakuRender#172]
建议自动清理可以像视频上传一样分成两个部分操作。

我想让原视频和弹幕视频分别到不同位置备份但是现在只能把两个一起处理

![屏幕截图 2023-12-26 223617](https://github.com/SmallPeaches/DanmakuRender/assets/51906392/8c918181-b193-437b-97cc-689aa481ae58)

**Comment by SmallPeaches** [comment]
喔，这里是个小bug，在你设置strict=false的时候它会把源视频当做弹幕视频一起清理，下个更新我修复一下。
