### ISSUE TITLE
斗鱼弹幕覆盖问题

### ISSUE THREAD

**Issue by anthle** [SmallPeaches/DanmakuRender#174]
渲染后长条的弹幕速度会过快覆盖同行的前方弹幕
![微信图片_20231229183153](https://github.com/SmallPeaches/DanmakuRender/assets/134090964/8b98ff7d-1f1d-4b63-af74-01d3684630d1)

**Comment by SmallPeaches** [comment]
这个设计之初就是这样的，也符合弹幕的逻辑，你用网页看也会发现这个情况，长弹幕速度快，短弹幕速度慢，这样才有弹幕的层次感而不是纯粹的平移。如果你完全不想让它重合可以考虑加大弹幕间隔。
