### ISSUE TITLE
渲染的视频会卡掉很多时长

### ISSUE THREAD

**Issue by MoncozGC** [SmallPeaches/DanmakuRender#175]
渲染一个小时的视频，有可能只能看几分钟，后面的就都没法观看了，这种情况会是什么问题呢？
下面是录制视频的部分日志，这个视频只能看7分钟。
[DMR-20230509.log](https://github.com/SmallPeaches/DanmakuRender/files/13815204/DMR-20230509.log)

**Comment by SmallPeaches** [comment]
你这个日志里面没有渲染的内容，暂时看不出来。
你先看看原视频能不能看？如果原视频正常的话你试下手动重新渲染，再看下正不正常？

**Comment by SmallPeaches** [comment]
另外你这个没法观看指的是什么，花屏？还是后面的内容直接没了？

**Comment by MoncozGC** [comment]
没法观看：后面的内容只有音频，假如这个有问题的视频上传到B站那么B站会直接删掉卡顿的时长

重新渲染后正常了，可能是当时渲染的时候GPU负载过高，导致渲染的有问题。

请问可以多一个功能嘛，比如在夜间12点后再去进行渲染视频并上传，这样可以提高资源不足机器的使用率。
比如：大部分主播会是在一个时间段内开播，如果开启录制、渲染、上传，那么机器压力会很大，甚至无法渲染成功，那么这时部分主播错开渲染的时间在之后再渲染会好一些。

**Comment by SmallPeaches** [comment]
实际上默认情况下渲染就是单线程的（每次只渲染一个视频，哪怕你录制多个主播也会按顺序渲染），你是不是调高了nrenders的值让多个渲染任务并行了？

**Comment by MoncozGC** [comment]
也不算调高，我是启动了两个程序（因为感觉这样看日志清晰一点），nrenders 参数都设置的 1，也可能是我边渲染还在使用电脑就导致使用率更高了。

那这样的话我应该将录制主播的信息都放在一个程序中，然后设置成 1就可以了

感谢~
