### ISSUE TITLE
录制遇到错误

### ISSUE THREAD

**Issue by BEIJUUUUU** [SmallPeaches/DanmakuRender#176]
应该是我的网络问题，我在电脑上也看不了这个直播间，但是同一WIFI下的手机又正常。下面是log和控制台截图。人在海外
[DMR-20240110.log](https://github.com/SmallPeaches/DanmakuRender/files/13893895/DMR-20240110.log)
![1](https://github.com/SmallPeaches/DanmakuRender/assets/113653343/2ee0d311-9052-4442-9fef-d14184f8b301)

**Comment by SmallPeaches** [comment]
感觉是B站限制导致的，B站现在有很多分区是不能在海外看的。至于手机客户端估计是它走的不是一条线路？
