### ISSUE TITLE
我把监测开播改成了三分钟，但还是被抖音锁了ip，录不了原画，有什么好的方法可以解除锁ip或者不被锁吗？

### ISSUE THREAD

**Issue by cms666** [SmallPeaches/DanmakuRender#179]

**Comment by SmallPeaches** [comment]
你确定是被锁IP了吗，按道理来说被锁IP会直接返回403才对，不应该是录不了原画。
另外家用网络的话过一两天IP会自动更新的，你可以再试试看看，我之前录一两个抖音直播没什么问题的。

**Comment by natgeoo** [comment]
请问怎么修改检测开播时间，我不知道具体怎么修改配置文件是正确的
