### ISSUE TITLE
大佬 请问用AMD的显卡的话渲染会差很多吗

### ISSUE THREAD

**Issue by NoColorPiggg** [SmallPeaches/DanmakuRender#180]
现在用的N卡，想换张A卡觉得性价比高一些。
但不知道渲染的话会不会比N卡差呢，或者有没有现在正在用A卡使用这个软件的伙伴能分享一下实际体验怎么样呢，感谢。

**Comment by SmallPeaches** [comment]
也许你可以先用云电脑看看性能？如果你只用来做录播的话也可以考虑那种专业渲染卡（好像之前的issue里面有人提过用Tesla的）。

**Comment by NoColorPiggg** [comment]
主要还是玩 哈哈发自我的 iPhone在 2024年1月24日，18:00，SmallPeaches ***@***.***> 写道：﻿
也许你可以先用云电脑看看性能？如果你只用来做录播的话也可以考虑那种专业渲染卡（好像之前的issue里面有人提过用Tesla的）。
