### ISSUE TITLE
已经完成了更新，但还是会提示有最新版本需要更新

### ISSUE THREAD

**Issue by prettyby** [SmallPeaches/DanmakuRender#182]
已经完成了更新，但还是会提示有最新版本需要更新
请问如何查看我当前版本的版本号呢？

![d510bf6b6a6574ce8ce24dba86e72a35](https://github.com/SmallPeaches/DanmakuRender/assets/153463728/6f7118ef-be35-4a9c-bba5-84e58cae61ea)

**Comment by SmallPeaches** [comment]
这个应该是我忘记改当前版本号了，你直接忽略就行，对运行没有影响的。
