### ISSUE TITLE
大佬考虑过加一个可以把每天的录播（以及上传完成后移动到一个文件夹里）放在一个文件夹里面吗？

### ISSUE THREAD

**Issue by lu621543** [SmallPeaches/DanmakuRender#186]
就是每天或者每次的录播放入一个文件夹，方便自己整理和观看。
就在脚本里面弄类似于这种就能自己识别几月几日然后创建文件夹
![1](https://github.com/SmallPeaches/DanmakuRender/assets/104936479/8f5f290e-3def-44bb-9160-92db43c1ff4b)
![2](https://github.com/SmallPeaches/DanmakuRender/assets/104936479/3fadcf51-f549-4fce-a7e0-3ea61c3af112)

**Comment by SmallPeaches** [comment]
实际上现在你第二个图的功能是有的，目标文件夹不存在时会自动创建。

**Comment by lu621543** [comment]
> 实际上现在你第二个图的功能是有的，目标文件夹不存在时会自动创建。

我的意思是文件夹可以弄一个像文件名一样可以识别月份和日期的吗😂，这样每天的录播都可以自己归纳好

**Comment by SmallPeaches** [comment]
现在清理的时候已经可以这样格式化字符串，只是录制的时候不行。

**Comment by lu621543** [comment]
哦哦我都没试过哈哈哈哈，我就试过录制的时候的文件夹，就和文件名一样的字符串是吧，感谢感谢🌹🌹🌹

**Comment by lu621543** [comment]
> 现在清理的时候已经可以这样格式化字符串，只是录制的时候不行。

哦哦我都没试过哈哈哈哈，我就试过录制的时候的文件夹，就和文件名一样的字符串是吧，感谢感谢🌹🌹🌹
