### ISSUE TITLE
项目经常运行一段时间之后bilibili.json值就变成0字节了

### ISSUE THREAD

**Issue by AZeC4** [SmallPeaches/DanmakuRender#188]
项目经常运行一段时间之后bilibili.json值就变成0字节了，中间也没断电，不知道是什么原因导致的，是文件在读写的过程中出错导致的么？还有请问有什么办法避免么？

**Comment by SmallPeaches** [comment]
这个问题我好像从来没出现过？你要不把这个文件改成只读的，别让它修改试试？

**Comment by itgoyo** [comment]
好嘞，感谢方案
