### ISSUE TITLE
渲染无法调用amd核显 GPU  

### ISSUE THREAD

**Issue by q1518001822** [SmallPeaches/DanmakuRender#189]
一直是cpu占用90% GPU占用只有1-2%

**Comment by SmallPeaches** [comment]
你设置了编码器为h264_amf吗？如果设置了的话GPU占用不应该那么低的。

**Comment by q1518001822** [comment]
改成 amf 后 GPU 也没啥变化 但 CPU 占用降低了

**Comment by SmallPeaches** [comment]
如果没有报错的话应该是已经调用了，你可以对比一下编码速度看看有没有明显提升。

**Comment by q1518001822** [comment]
我在用格式工厂 gpu 实际占 30%-40% 用你这个 一直占用 1%-3% 
用  CPU 占用 80%-100% 
用 amf CPU50%-60% GPU 还是 1%[IMG_20240225_164738.jpg](https://github.com/SmallPeaches/DanmakuRender/assets/143792420/4b92c6ae-3f18-4a26-b12a-84011730a31a)

但是吧我又能听见风扇转 感觉好像比 CPU 快 长视频还不知道

**Comment by q1518001822** [comment]
还有一个问题为啥每次开录 8 秒就会卡一下

**Comment by SmallPeaches** [comment]
> 我在用格式工厂 gpu 实际占 30%-40% 用你这个 一直占用 1%-3% 用 CPU 占用 80%-100% 用 amf CPU50%-60% GPU 还是 1%[IMG_20240225_164738.jpg](https://github.com/SmallPeaches/DanmakuRender/assets/143792420/4b92c6ae-3f18-4a26-b12a-84011730a31a)
> 
> 但是吧我又能听见风扇转 感觉好像比 CPU 快 长视频还不知道

你可以用render only试试只渲染，它可以直接显示出速度

**Comment by SmallPeaches** [comment]
> 还有一个问题为啥每次开录 8 秒就会卡一下

这是什么意思

**Comment by q1518001822** [comment]
就是每次录播到第 8-12 秒之间会卡画面不动然后跳过几秒恢复正常 每次测试都是在第 8-12 秒之间卡那么一下 后面就没事了

**Comment by SmallPeaches** [comment]
这个还真没听说过，如果只是每个小时前几秒卡一次那就不用管了。

**Comment by q1518001822** [comment]
不一样 如果你粉丝少怎么糊弄都行 粉丝多 让人有一点别扭看着不舒服就会被喷的体无完肤 建议多在稳定性上下下功夫 搞个成熟产品 即便收费也是有愿意的  现在又出一个问题录制一段时间 弹幕就获取失败了

**Comment by SmallPeaches** [comment]
> 不一样 如果你粉丝少怎么糊弄都行 粉丝多 让人有一点别扭看着不舒服就会被喷的体无完肤 建议多在稳定性上下下功夫 搞个成熟产品 即便收费也是有愿意的 现在又出一个问题录制一段时间 弹幕就获取失败了

如果是追求商用级别稳定性的话我这个肯定是保证不了的，我本来也不是什么专业开发者，也有自己的工作的。像这种一个小时或者几个小时卡一两秒钟，而且不是普遍问题的情况下我也没那么多精力修，或者说也没必要修。我认为只要视频内容基本上正常的话就不用管了。

**Comment by SecPhases** [comment]
> 我在用格式工厂 gpu 实际占 30%-40% 用你这个 一直占用 1%-3% 用 CPU 占用 80%-100% 用 amf CPU50%-60% GPU 还是 1%[IMG_20240225_164738.jpg](https://github.com/SmallPeaches/DanmakuRender/assets/143792420/4b92c6ae-3f18-4a26-b12a-84011730a31a)
> 
> 但是吧我又能听见风扇转 感觉好像比 CPU 快 长视频还不知道

因为你这显示的不是编码器的占用，你选一下那个3d改成video codec之类的再看看就有占用了
