### ISSUE TITLE
直播录制视频文件长度只有1分钟多几秒

### ISSUE THREAD

**Issue by BEIJUUUUU** [SmallPeaches/DanmakuRender#19]
开始是正常的，后面的Part都是只有1分多钟
![QQ截图20230212093040](https://user-images.githubusercontent.com/113653343/218288308-40f65513-8306-4500-b5b0-6473622a4c08.png)
![QQ截图20230212093017](https://user-images.githubusercontent.com/113653343/218288311-63c81683-7110-4ea0-b315-57d021d7b4bb.png)

下面是log：
[DMR-20230212.log](https://github.com/SmallPeaches/DanmakuRender/files/10715071/DMR-20230212.log)

**Comment by SmallPeaches** [comment]
好像是B站返回的流有问题，这个xy122x226x162x103xy.mcdn.bilivideo.cn的流有问题，我修一下让它不获取这个cdn的流吧
