### ISSUE TITLE
关于录制多人是否需要重新启动程序的疑问

### ISSUE THREAD

**Issue by itgoyo** [SmallPeaches/DanmakuRender#190]
请问添加新的主播是否需要重新启动程序？刚刚自己使用v5验证一下，在录制一个主播的过程中，新增了别的主播，然后在终端看等了几分钟还是没有看到新主播的录制信息(主播是在直播的)。

是不是每次新增主播都要重新启动主程序，还有之前如果录制意外中断了，后面再启动的时候只会上传重启之后的那部分，而昨天、前天这种日期的不会上传，现在新版本是不是也还存在这个问题呢？期待您的回复。

**Comment by SmallPeaches** [comment]
1. v5新建任务是不需要重启的，但是你要在global.yml里面把dynamic config设置为true才行。
2. 如果你重启了程序的话是会忽略之前的视频，v5也是一样的。

**Comment by itgoyo** [comment]
感谢解答
