### ISSUE TITLE
经过反复多家测试  该软件无法调用amd核显

### ISSUE THREAD

**Issue by q1518001822** [SmallPeaches/DanmakuRender#191]
在其他软件中 都能正藏启用AMD核显GPU硬件加速  gpu占用 40%-80%  而在这个程序里 gpu一直休息状态1% 我100%确定以及肯定程序有问题建议修复

**Comment by SmallPeaches** [comment]
你发下日志来看看？

**Comment by Sora3QwQ** [comment]
建议自查ffmpeg的问题
