### ISSUE TITLE
渲染出巨大体积视频的bug反馈

### ISSUE THREAD

**Issue by natgeoo** [SmallPeaches/DanmakuRender#195]
![f346d11e2dabad65cd70e01cd70cdc9](https://github.com/SmallPeaches/DanmakuRender/assets/140871577/bf5ee9d6-4103-4909-b5d7-b9e28942f006)
![fec03305b4ee7331ceb63a548a15b7e](https://github.com/SmallPeaches/DanmakuRender/assets/140871577/d1ae2de6-fba9-40c7-bc2d-f4eb64b9864f)
上图为原始ts流，大小101m
下图为渲染到半我手动中断渲染的视频，大小1.55g
很明显大小不对是有问题，近期遇到过两次
以下是log截图和文件，19524行：“2024-02-28 23:51:55,407] 完成对 梵谷 的全部视频渲染”，是我手动中断ffmpeg渲染的时间，开发者可定位前后
[Uploading DMR-20240228.log…]()

**Comment by natgeoo** [comment]
补：使用ffmpeg -c copy 转mp4封装后可正常渲染
![750c9e5d38e7cc6987cfa6b0169be97](https://github.com/SmallPeaches/DanmakuRender/assets/140871577/7b927032-36f7-4c80-aa74-91cf5ab0983b)

**Comment by SmallPeaches** [comment]
第一个1.55GB那个你设置的码率是多少，实际视频的码率又是多少？

**Comment by natgeoo** [comment]
> 第一个1.55GB那个你设置的码率是多少，实际视频的码率又是多少？

原1.55g视频删除了，刚刚使用今天修改后的replay.yml配置文件设置0.8m码率重新渲染后正常不会出现文件体积巨大的bug，下次如bug复现会记录好当时的配置文件
