### ISSUE TITLE
每次运行都会提示“Python 包未正确安装”，但回车后并不会安装任何新的包，而且程序可以正常运行

### ISSUE THREAD

**Issue by HexStan** [SmallPeaches/DanmakuRender#196]
![image](https://github.com/SmallPeaches/DanmakuRender/assets/34975883/a8e901df-1ec4-442c-b46f-4b4bc80e27f5)

**Comment by SmallPeaches** [comment]
看起来像是streamgears安装失败了，所以说每次都提醒你安装。能正常运行是因为你下载引擎用的FFmpeg，如果换成streamgears就报错了。

**Comment by HexStan** [comment]
> 看起来像是streamgears安装失败了，所以说每次都提醒你安装。能正常运行是因为你下载引擎用的FFmpeg，如果换成streamgears就报错了。

手动执行了pip install stream-gears后再运行也还是一样情况。

**Comment by HexStan** [comment]
> 看起来像是streamgears安装失败了，所以说每次都提醒你安装。能正常运行是因为你下载引擎用的FFmpeg，如果换成streamgears就报错了。

手动执行pip install stream-gears后已经解决。
