### ISSUE TITLE
关于弹幕过滤的疑问

### ISSUE THREAD

**Issue by Vae0514wzq** [SmallPeaches/DanmakuRender#197]
![Snipaste_2024-03-06_23-25-42](https://github.com/SmallPeaches/DanmakuRender/assets/65432819/7790c202-e1ed-4cfc-b6e7-52d73d562978)
想问下已经在弹幕过滤规则中填了关键字，但单独渲染出来的弹幕版视频还是有此弹幕，这个怎么配置的？

**Comment by chenfanz** [comment]
感叹号的原因吧，字符串识别不对

**Comment by SmallPeaches** [comment]
弹幕过滤要求在录制的时候填写，你如果录制的时候没写屏蔽词后面渲染的时候再加是没效果的。
