### ISSUE TITLE
douyin好像炸了 解析失败

### ISSUE THREAD

**Issue by prettyby** [SmallPeaches/DanmakuRender#198]
我没有放yml是为了截图
不然打开main就疯狂闪退
只有抖音闪退 虎牙没事
求修复！

![bd418713d315122cdc982137e34bca67](https://github.com/SmallPeaches/DanmakuRender/assets/153463728/c2a2c912-0b43-4e7b-bd6d-4367facdd98f)

另外我记得开始录制，最开始没有这么多debug信息啊
我就是最新1.30更新的版本
然后重启了一下机器，再打开就这样了

![2](https://github.com/SmallPeaches/DanmakuRender/assets/153463728/08dbb0f8-0213-40c5-8b6c-d752800acb47)

![3](https://github.com/SmallPeaches/DanmakuRender/assets/153463728/a4e8871b-597d-4094-8d47-f0ed7096663b)

**Comment by prettyby** [comment]
看了一下 又恢复正常了 凌晨的时候莫名其妙

**Comment by SmallPeaches** [comment]
猜想是重试次数太多了被暂时ban了，抖音反爬比较严，短时间重试多次会直接被ban。
