### ISSUE TITLE
[Question]关于使用winsw托管DMR时无法调用AMD硬件加速编码

### ISSUE THREAD

**Issue by SecPhases** [SmallPeaches/DanmakuRender#199]
如题，本来我以为是屏幕没有打开导致无法调用硬件加速，但是经测试即使屏幕打开也无法编码
使用[winsw](https://github.com/winsw/winsw)托管DMR防止出现电脑重启以后DMR不启动
用的是[v5](../tree/v5)
报错如下
```
[AVHWDeviceContext @ 000001b7937548c0] Failed to create Direct3D device
Device creation failed: -1313558101.
```
这里是完整的winsw（托管的DMR）的日志
[winsw.out.log](https://github.com/SmallPeaches/DanmakuRender/files/14575814/winsw.out.log)

使用的是AMD显卡，不知道是什么原因，搜也没搜出来，希望有办法解决

**Comment by SecPhases** [comment]
补一下DMR配置，yml传不了改txt了
[DMR-Quin.yml.txt](https://github.com/SmallPeaches/DanmakuRender/files/14575921/DMR-Quin.yml.txt)

[global.yml.txt](https://github.com/SmallPeaches/DanmakuRender/files/14575922/global.yml.txt)

**Comment by SecPhases** [comment]
补一下DMR配置，yml传不了改txt了
[DMR-Quin.yml.txt](https://github.com/SmallPeaches/DanmakuRender/files/14575921/DMR-Quin.yml.txt)

[global.yml.txt](https://github.com/SmallPeaches/DanmakuRender/files/14575922/global.yml.txt)

**Comment by SmallPeaches** [comment]
#184

**Comment by SecPhases** [comment]
> #184

好了，我还在纠结amd填什么，改成空就行了
