### ISSUE TITLE
虎牙新添加主播无法录制 

### ISSUE THREAD

**Issue by prettyby** [SmallPeaches/DanmakuRender#200]
直播间
https://www.huya.com/29819169

录制的虎牙主播有几个 都没事 
这个新添加的死活不成功

报错如下
![b4373f33258a5d4a51c0d12b5a004163](https://github.com/SmallPeaches/DanmakuRender/assets/153463728/d6d3f966-c04d-4601-9e94-497dfc5d3af3)

**Comment by SmallPeaches** [comment]
我这两天没看到他开播试不了，这里应该是获取的直播流出问题了，你看下日志文件它具体的报错是什么。
