### ISSUE TITLE
DanmakuRender-4 遇到报错代码

### ISSUE THREAD

**Issue by blackedxyz** [SmallPeaches/DanmakuRender#203]
[Parsed_subtitles_0 @ 000001bd85131940] libass API version: 0x1701000
[Parsed_subtitles_0 @ 000001bd85131940] libass source: commit: 0.17.0-71-g58a8f09cccb4829239855791a305d1336d8ee773
[Parsed_subtitles_0 @ 000001bd85131940] Shaper: FriBidi 1.0.13 (SIMPLE) HarfBuzz-ng 8.3.0 (COMPLEX)
[Parsed_subtitles_0 @ 000001bd85131940] Using font provider directwrite (with GDI)
[h264_nvenc @ 000001bd85106580] Driver does not support the required nvenc API version. Required: 12.1 Found: 7.0
[h264_nvenc @ 000001bd85106580] The minimum required Nvidia driver for nvenc is (unknown) or newer
[vost#0:0/h264_nvenc @ 000001bd857c4440] Error while opening encoder - maybe incorrect parameters such as bit_rate, rate, width or height.
[vf#0:0 @ 000001bd8513ee40] Error sending frames to consumers: Function not implemented
[vf#0:0 @ 000001bd8513ee40] Task finished with error code: -40 (Function not implemented)
[vf#0:0 @ 000001bd8513ee40] Terminating thread with return code -40 (Function not implemented)
[vost#0:0/h264_nvenc @ 000001bd857c4440] Could not open encoder before EOF
[vost#0:0/h264_nvenc @ 000001bd857c4440] Task finished with error code: -22 (Invalid argument)
[vost#0:0/h264_nvenc @ 000001bd857c4440] Terminating thread with return code -22 (Invalid argument)
[out#0/mp4 @ 000001bd8586ba00] Nothing was written into output file, because at least one of its streams received no packets.
frame=    0 fps=0.0 q=0.0 Lsize=       0KiB time=N/A bitrate=N/A dup=1 drop=0 speed=N/A
[aac @ 000001bd8584f6c0] Qavg: 64108.379
Conversion failed!

**Comment by SmallPeaches** [comment]
更新显卡驱动

**Comment by blackedxyz** [comment]
> 更新显卡驱动

只有集成显卡。。

**Comment by SmallPeaches** [comment]
那你就要参考使用文档改下配置文件。
