### ISSUE TITLE
使用RD远程桌面导致ffmpeg崩溃的问题反馈

### ISSUE THREAD

**Issue by natgeoo** [SmallPeaches/DanmakuRender#207]
电脑被RD远程桌面登录后程序报错log：`[AVHWDeviceContext @ 00000190ca1ca740] Failed to create Direct3D device`
![微信截图_20240407161108](https://github.com/SmallPeaches/DanmakuRender/assets/140871577/73df20a7-9ce4-4c32-829a-6e8600c7e6b6)
![微信截图_20240407161920](https://github.com/SmallPeaches/DanmakuRender/assets/140871577/190012b9-5e54-4609-a8ca-e68a12f904ea)

原始log：
[DMR-20240407.log](https://github.com/SmallPeaches/DanmakuRender/files/14896291/DMR-20240407.log)
报错在第2139行，程序可继续运行但是ffmpeg崩溃
猜测是因为RD远程桌面登录后电脑会自动适配分辨率并锁屏，图形界面被魔改导致的崩溃，之前启用n卡自带GeForce Experience录屏，也会导致RD远程桌面黑屏

**Comment by SmallPeaches** [comment]
#184
