### ISSUE TITLE
直播流下载速度过慢

### ISSUE THREAD

**Issue by a7606962** [SmallPeaches/DanmakuRender#209]
RT      请保证网络带宽充足     即将重试

**Comment by a7606962** [comment]
![replay-集梦小小小酷哥-组织.txt](https://github.com/SmallPeaches/DanmakuRender/files/14913845/replay-.-.txt)

还有帮忙给看看这个配置对不对   自动上传功能用不了

**Comment by SmallPeaches** [comment]
偶尔重试一次是正常的，这个自动上传显示什么错误？
