### ISSUE TITLE
怎么徐晓延时发布

### ISSUE THREAD

**Issue by q1518001822** [SmallPeaches/DanmakuRender#213]
写的最块4小时 但是是第二天 不是当天的
怎么取消掉延时发布 改为立即发布

**Comment by Mallknow** [comment]
B站目前定时发布的稿件审核通过后，无法修改、删除时间设定，只能重新投稿并设置新的时间。

**Comment by q1518001822** [comment]
不是修改 我是说自动上传时 怎么取消定时发布 取消不了吗

**Comment by q1518001822** [comment]
默认录播工具自动上传是定时的 我改不了

**Comment by Mallknow** [comment]
文档里面写的很清楚了
```
# 上传参数
upload_args:
...
# 延迟发布，单位秒，如果需要的话至少设置14400秒（4个小时）
    dtime: 0
...
```

**Comment by q1518001822** [comment]
对啊 我写14400 但是他发布后日期是明天的不是当天的

**Comment by q1518001822** [comment]
我是上午试的

**Comment by q1518001822** [comment]
20号发布 写4小时  发布时候却是21号  上午时候

**Comment by q1518001822** [comment]
现在不能立即发布也不能当天发布

**Comment by SmallPeaches** [comment]
我猜想是你那个视频上传花太多时间了？因为这里设置的时间是上传开始时间+4小时，但是B站的要求是上传完成的时间+4小时，如果上传太慢我也不知道会发生啥。如果可以的话你把日志文件拿来看看。

**Comment by q1518001822** [comment]
你在搞笑吧 这和上传时间有什么关系  我问的是定时发布的时间 我用的测试功能运行的 能看懂吗

**Comment by q1518001822** [comment]
我都怀疑你都没怎么用过b站 还搞什么

**Comment by q1518001822** [comment]
上传完审核完 才会显示定时发布的时间 自己去看你设置的定时时间 和哪天的是不是当天的

**Comment by q1518001822** [comment]
> 上传完审核完 才会显示定时发布的时间 自己去看你设置的定时时间 是哪天的是不是当天的

**Comment by Mallknow** [comment]
大佬，你要是这么厉害，欢迎PR！

**Comment by SmallPeaches** [comment]
> 你在搞笑吧 这和上传时间有什么关系 我问的是定时发布的时间 我用的测试功能运行的 能看懂吗

那我建议先把文档看明白了再来提问，别字还没认全就来提问😅

**Comment by q1518001822** [comment]
你看明白了吗 我20号早上8点上传完成  你给我21号发布是吗
