### ISSUE TITLE
怎么固定1080p录播画质

### ISSUE THREAD

**Issue by q1518001822** [SmallPeaches/DanmakuRender#217]
录出来是2k的用不到文件太大b站也不支持

**Comment by q1518001822** [comment]
斗鱼

**Comment by Sora3QwQ** [comment]
老馋 还过来找骂？快滚回去用格式工厂吧

**Comment by q1518001822** [comment]
这素质 问题解决不了就骂人

**Comment by q1518001822** [comment]
自己问题避而不答 不许别人提问题 提就是用户问题什么东西

**Comment by Sora3QwQ** [comment]
不是哥们 你给我讲上素质了？素质是给人讲的 不是给你这种狗讲的，顺便楼下溜条狗

[你在搞笑吧 这和上传时间有什么关系 我问的是定时发布的时间 我用的测试功能运行的 能看懂吗](https://github.com/SmallPeaches/DanmakuRender/issues/213#issuecomment-2067979608)

[确实只有我 别人都不用 这么明显自己做的东西自己不去试](https://github.com/WhiteMinds/LiveAutoRecord/issues/209#issuecomment-2056702065)

[不一样 如果你粉丝少怎么糊弄都行 粉丝多 让人有一点别扭看着不舒服就会被喷的体无完肤 建议多在稳定性上下下功夫 搞个成熟产品 即便收费也是有愿意的 现在又出一个问题录制一段时间 弹幕就获取失败了](https://github.com/SmallPeaches/DanmakuRender/issues/189#issuecomment-1962966449)

不是哥们，你真把自己当甲方了？白嫖东西也能大声叫啊，说你一句4000+了你真得忍着吧

**Comment by Sora3QwQ** [comment]
你这低能的脑子确实只配用用格式工厂这种东西了，指南写的这么详细也挡不住你这低能过来拉屎，你死妈了脑残，回家看看你妈尸体吧 有点冰冰凉了

**Comment by q1518001822** [comment]
怎么的 免费就不能提问题了？ 你也太高看你自己了 你就是个套壳组装的 还装起来了  真把自己当大佬了？

**Comment by Sora3QwQ** [comment]
脑瘫 你真吧自己当甲方了？你这是提问题的态度？草你死妈 你别来丢人现眼了

**Comment by q1518001822** [comment]
笑死 我一直正常提问 是你先不耐烦开始攻击人的现在我反攻你你还不乐意了 这么双标 谁先态度不好的自己看去

**Comment by Sora3QwQ** [comment]
你这么厉害，一定可以自己套壳组装吧 ，怎么没看见你组装一个呢  低能发言前先学习一下语言的艺术，别说话就暴露智商，你这么牛逼还在用套壳产品 属实是低能中的低能了

**Comment by q1518001822** [comment]
看把这就是说不过就阴阳 我不喷你喷谁

**Comment by Sora3QwQ** [comment]
太正常提问了吧哥们 ，那链接里面三个低能是谁提的你能告诉我一下吗，不知道真以为你是甲方呢 ，你这b态度还想让别人好好和你讲话啊，你妈是没教给你怎么和别人说话还是你和你妈说话也是这样的呢 ，我保持怀疑态度

**Comment by Sora3QwQ** [comment]
低能东西 你妈妈一定死的很早 所以导致你丧失了与别人交流的能力

**Comment by q1518001822** [comment]
你这句 说的好 我截图了  我看谁还问你

**Comment by Sora3QwQ** [comment]
你是这态度谁帮你解决问题呢，顺便提一嘴，以后也不会有其他录播项目主回答你问题了呀

**Comment by q1518001822** [comment]
莫人因无法解答问题 便说用户是低能儿 大佬都没有你牛逼  大佬都不敢这么说话

**Comment by q1518001822** [comment]
你爸爸来问你按你的说话也是低能儿

**Comment by Sora3QwQ** [comment]
低能别挂着自己的q号出来上网了

**Comment by q1518001822** [comment]
关你什么事呢

**Comment by SmallPeaches** [comment]
两个人都别吵了，我统一回复一下，这个问题会直接锁定。
1. 提issue之前先把安装文档和使用文档读完，很多问题我在文档里面都有详细解答，就算文档里面没有的问题现有的issue里面也基本上解答了，提问之前先自行搜索阅读，暂时没有的功能和没解决的问题一直提问也没有用。
2. 如果觉得我这个程序问题很多，不好用，纯纯套皮工作没含金量可以选择直接删除，程序不会在任何自身文件夹之外的地方保存数据文件（Python解释器需要手动在控制面板卸载）。
3. 无论是提问还是回答问题都应该友好交流，GitHub提供的是交流技术的平台，不是吵架的下水道，如果再出现骂人、引战甚至是到处攻击的话我会直接拉黑。
