### ISSUE TITLE
这是什么情况

### ISSUE THREAD

**Issue by a7606962** [SmallPeaches/DanmakuRender#218]
![1](https://github.com/SmallPeaches/DanmakuRender/assets/162891419/af075d29-7d8b-4257-94fe-6d78193289f6)

**Comment by q1518001822** [comment]
你自己问题 自己找 作者说了别找骂

**Comment by Sora3QwQ** [comment]
直播间看下线路 ，切换流试试
AL（阿里云 - 直播线路3）, TX（腾讯云 - 直播线路5）, HW（华为云 - 直播线路6）, WS（网宿）, HS（火山引擎 - 直播线路14）, AL13（阿里云）, HW16（华为云）, HY(星域云 - 直播线路66)

**Comment by a7606962** [comment]
> 直播间看下线路 ，切换流试试 AL（阿里云 - 直播线路3）, TX（腾讯云 - 直播线路5）, HW（华为云 - 直播线路6）, WS（网宿）, HS（火山引擎 - 直播线路14）, AL13（阿里云）, HW16（华为云）, HY(星域云 - 直播线路66)

感谢  我试试

**Comment by a7606962** [comment]
> 直播间看下线路 ，切换流试试 AL（阿里云 - 直播线路3）, TX（腾讯云 - 直播线路5）, HW（华为云 - 直播线路6）, WS（网宿）, HS（火山引擎 - 直播线路14）, AL13（阿里云）, HW16（华为云）, HY(星域云 - 直播线路66)

还是不行   这几个都试了   还是一直错误.....
