### ISSUE TITLE
这两天老是莫名奇妙的出错，那的问题呀

### ISSUE THREAD

**Issue by a7606962** [SmallPeaches/DanmakuRender#220]
![22](https://github.com/SmallPeaches/DanmakuRender/assets/162891419/f75a08ef-3272-4466-a870-81d5498b4ea9)

**Comment by a7606962** [comment]
[DMR-20240429-1.log](https://github.com/SmallPeaches/DanmakuRender/files/15147473/DMR-20240429-1.log)

**Comment by SmallPeaches** [comment]
你这个主播显示不存在了啊，我查了一下这个之前是danking，现在他用的是新直播间号10188了。

**Comment by a7606962** [comment]
> 你这个主播显示不存在了啊，我查了一下这个之前是danking，现在他用的是新直播间号10188了。

![{14B11FAD-7F05-4a7c-96A4-183DB3E02A2A}](https://github.com/SmallPeaches/DanmakuRender/assets/162891419/f4264a28-792a-46a0-8848-15438155feab)
那这个又是啥原因

**Comment by a7606962** [comment]
> 你这个主播显示不存在了啊，我查了一下这个之前是danking，现在他用的是新直播间号10188了。

Traceback (most recent call last):
  File "E:\DMR\Downloader\__init__.py", line 215, in start_helper
    self.start_once()
  File "E:\DMR\Downloader\__init__.py", line 176, in start_once
    return future.result()
  File "F:\python\lib\concurrent\futures\_base.py", line 439, in result
    return self.__get_result()
  File "F:\python\lib\concurrent\futures\_base.py", line 391, in __get_result
    raise self._exception
  File "F:\python\lib\concurrent\futures\thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "E:\DMR\Downloader\__init__.py", line 164, in video_thread
    self.downloader.start()
  File "E:\DMR\Downloader\ffmpegio.py", line 248, in start
    return self.start_helper()
  File "E:\DMR\Downloader\ffmpegio.py", line 230, in start_helper
    raise RuntimeError(f'{self.taskname} 直播流读取错误, 即将重试.

**Comment by SmallPeaches** [comment]
> > 你这个主播显示不存在了啊，我查了一下这个之前是danking，现在他用的是新直播间号10188了。
> 
> ![{14B11FAD-7F05-4a7c-96A4-183DB3E02A2A}](https://private-user-images.githubusercontent.com/162891419/327943385-f4264a28-792a-46a0-8848-15438155feab.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQ5MDQ3NjgsIm5iZiI6MTcxNDkwNDQ2OCwicGF0aCI6Ii8xNjI4OTE0MTkvMzI3OTQzMzg1LWY0MjY0YTI4LTc5MmEtNDZhMC04ODQ4LTE1NDM4MTU1ZmVhYi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTA1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUwNVQxMDIxMDhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mY2IyODJhZjczMzhjYjUwYjQwNzJhMjNlMWNkYWQwZGUxNTJkZTFmMzFkZWNmOTE1NjhhYTE1OWQyMGQ3MWRkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.yI-1yQrMsLimI3BVE6cJvVWNmv0y4A6YQnrG5TkAD7M) 那这个又是啥原因

这个之前推送了更新，你可以看一下。

**Comment by a7606962** [comment]
> > > 你这个主播显示不存在了啊，我查了一下这个之前是danking，现在他用的是新直播间号10188了。
> > 
> > 
> > ![{14B11FAD-7F05-4a7c-96A4-183DB3E02A2A}](https://private-user-images.githubusercontent.com/162891419/327943385-f4264a28-792a-46a0-8848-15438155feab.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQ5MDQ3NjgsIm5iZiI6MTcxNDkwNDQ2OCwicGF0aCI6Ii8xNjI4OTE0MTkvMzI3OTQzMzg1LWY0MjY0YTI4LTc5MmEtNDZhMC04ODQ4LTE1NDM4MTU1ZmVhYi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTA1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUwNVQxMDIxMDhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mY2IyODJhZjczMzhjYjUwYjQwNzJhMjNlMWNkYWQwZGUxNTJkZTFmMzFkZWNmOTE1NjhhYTE1OWQyMGQ3MWRkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.yI-1yQrMsLimI3BVE6cJvVWNmv0y4A6YQnrG5TkAD7M) 那这个又是啥原因
> 
> 这个之前推送了更新，你可以看一下。

update.py   是运行这个更新吗

**Comment by SmallPeaches** [comment]
这个更新要下载压缩包覆盖安装
