### ISSUE TITLE
佬 V5版本有个stream-gears需要最新版本提示

### ISSUE THREAD

**Issue by ikun1993** [SmallPeaches/DanmakuRender#223]
是否是旧版本的biliuprs就支持了

**Comment by SmallPeaches** [comment]
这个我不太清楚，我现在用`biliuprs 0.1.19+stream-gears 0.1.15`是没有问题的。

**Comment by ikun1993** [comment]
是的 我看到了  是因为突然有课提示库biliuprs 0.1.17不支持  我才想问下  但是我现在运行目前没有问题
