### ISSUE TITLE
请问支持使用A770显卡渲染吗？

### ISSUE THREAD

**Issue by JunPGo** [SmallPeaches/DanmakuRender#226]
看到您使用说明中写了N卡和A卡的渲染参数，想问下支持I卡渲染吗，支持的话参数应该设置什么？感谢大佬！

**Comment by JunPGo** [comment]
![image](https://github.com/SmallPeaches/DanmakuRender/assets/107451696/2da3e7c5-6698-4ab9-a388-92eca6113040)
看了下之前解决了的使用核显的问题，目前能使用A770执行渲染，但是出现这个报错，还麻烦大佬们帮看下原因，感谢！

**Comment by SmallPeaches** [comment]
你先试下更新驱动程序看看？
然后试试控制台试试用ffmpeg转码，然后看看能否调用h264_qsv?
