### ISSUE TITLE
v5链接简介有误

### ISSUE THREAD

**Issue by ikun1993** [SmallPeaches/DanmakuRender#228]
![image](https://github.com/SmallPeaches/DanmakuRender/assets/96544807/e7ba6f7e-83e3-4208-bafb-e83f7db174bc)
![image](https://github.com/SmallPeaches/DanmakuRender/assets/96544807/d1ee0084-dbf8-4bbe-8294-770539f403fe)

实际：https://live.douyin.com/177897637709
但是配置的简介直播地址：{STREAMER.URL}获得的是 https://www.douyin.com/177897637709

**Comment by SmallPeaches** [comment]
下个版本会修复，现在暂时直接填链接吧。

**Comment by ikun1993** [comment]
收到大佬  没试不影响使用我就反馈一下
