### ISSUE TITLE
两个录制引擎有什么区别？请求作者大大解答

### ISSUE THREAD

**Issue by G39949454** [SmallPeaches/DanmakuRender#229]
ffmpeg和streamgears提供的拉流服务有什么区别呢？

**Comment by G39949454** [comment]
![DS~0QD7T(7ZD37_7EM$ED}7](https://github.com/SmallPeaches/DanmakuRender/assets/169589631/3658bfe1-2bfc-49c9-927b-e7cbf519d49b)
还有这个报错信息是什么问题呢？昨天遇到的

**Comment by SmallPeaches** [comment]
1. 使用文档里面有比较明确的说明了，你可以去看看。
2. 如果是偶尔有的话是正常的。
