### ISSUE TITLE
今天一直报错FFmpeg 退出是咋回事啊，之前一直都很正常的

### ISSUE THREAD

**Issue by duxdyu** [SmallPeaches/DanmakuRender#234]
连着运行十天了吧，今天突然一直报错，一两分钟就报这个错
![QQ图片20240522170426](https://github.com/SmallPeaches/DanmakuRender/assets/84559061/f9b8e4c1-e529-4712-9c07-ab601d85c391)
![QQ图片20240522170426](https://github.com/SmallPeaches/DanmakuRender/assets/84559061/e7d5e197-d60f-43e7-8db4-664b46bf7ce7)

**Comment by SmallPeaches** [comment]
B站是吗？你试下其他B站的直播间能不能正常录制，如果可以的话应该是这个直播间的flv流出问题了，你可以考虑切换到v5版本录制fmp4流。

**Comment by duxdyu** [comment]
> B站是吗？你试下其他B站的直播间能不能正常录制，如果可以的话应该是这个直播间的flv流出问题了，你可以考虑切换到v5版本录制fmp4流。

是B站，试了一下别的直播间也偶尔出这个问题，这个直播间这几天也是偶尔出问题，fmp4流更稳定吗？我换一下试试看

**Comment by SmallPeaches** [comment]
因为B站有些直播间的flv流是不可用的，具体情况取决于你录制的直播间
