### ISSUE TITLE
请问怎么修改监测开播时间？阅读文档后没发现有具体配置说明

### ISSUE THREAD

**Issue by natgeoo** [SmallPeaches/DanmakuRender#235]

**Comment by SmallPeaches** [comment]
文档里面的[高阶设置-高级视频录制参数](https://github.com/SmallPeaches/DanmakuRender/blob/v4/docs/usage.md#%E9%AB%98%E9%98%B6%E4%BD%BF%E7%94%A8:~:text=%23%20%E5%BC%80%E6%92%AD%E6%A3%80%E6%B5%8B%E9%97%B4%E9%9A%94%EF%BC%8C%E6%AF%8F%E9%9A%94%E8%BF%99%E6%A0%B7%E4%B8%80%E6%AE%B5%E6%97%B6%E9%97%B4%E6%A3%80%E6%B5%8B%E4%B8%80%E6%AC%A1%E6%98%AF%E5%90%A6%E5%BC%80%E6%92%AD%0A%20%20start_check_interval%3A%2060%0A%20%20%23%20%E4%B8%8B%E6%92%AD%E6%A3%80%E6%B5%8B%E9%97%B4%E9%9A%94%EF%BC%8C%E5%9C%A8%E4%B8%BB%E6%92%AD%E4%B8%8B%E6%92%AD%E4%BD%86%E6%98%AF%E6%9C%AA%E8%B6%85%E8%BF%87%E5%BB%B6%E8%BF%9F%E4%B8%8B%E6%92%AD%E6%97%B6%E9%97%B4%E6%97%B6%E4%BD%BF%E7%94%A8%0A%20%20stop_check_interval%3A%2030)
