### ISSUE TITLE
无法输出重缩放，弹幕版 设置了还是原来的分辨率

### ISSUE THREAD

**Issue by lzd998** [SmallPeaches/DanmakuRender#236]
![QQ截图20240523185653](https://github.com/SmallPeaches/DanmakuRender/assets/137375085/4ae976ea-22c4-4edf-9b67-035d591c8e91)
而且出现这个错误  不知道是什么问题             弹幕版视频能正常渲染出来，但是分辨率没有改变，希望能帮忙解答  谢谢~~

**Comment by lzd998** [comment]
![QQ截图20240523190030](https://github.com/SmallPeaches/DanmakuRender/assets/137375085/f573d508-9ea4-4d77-91b3-23ffa1cdc378)

**Comment by SmallPeaches** [comment]
你先看下日志文件里面的参数正确吗？

**Comment by lzd998** [comment]
没设置好，我的问题，已经正常了

**Comment by lzd998** [comment]
在replay.yml 设置就好了，
