### ISSUE TITLE
开播检测的  start_check_interval: 5 是隔5秒检测一次吗

### ISSUE THREAD

**Issue by G39949454** [SmallPeaches/DanmakuRender#238]
开播检测的  start_check_interval: 5 是隔5秒检测一次吗，还是5分钟呢

**Comment by G39949454** [comment]
![4ZO{$9D(_)V7DT @6%9)%%I](https://github.com/SmallPeaches/DanmakuRender/assets/169589631/4a50f8ff-c3c0-410e-afd5-fb4ea935ec92)
我这样加进去可以吗，下面需要空出一行吗，感谢作者

**Comment by SmallPeaches** [comment]
单位是秒，但是设置这么短的间隔小心被封IP喔。

**Comment by G39949454** [comment]
啊，那我还是把这段去掉吧，默认是60秒吗，作者大哥
