### ISSUE TITLE
渲染报错 更新驱动也没有效果

### ISSUE THREAD

**Issue by y-ucheng** [SmallPeaches/DanmakuRender#239]
[h264_nvenc @ 00000297c5f420c0] Driver does not support the required nvenc API version. Required: 12.2 Found: 12.1
[h264_nvenc @ 00000297c5f420c0] The minimum required Nvidia driver for nvenc is (unknown) or newer
[vost#0:0/h264_nvenc @ 00000297c5f41e00] Error while opening encoder - maybe incorrect parameters such as bit_rate, rate, width or height.
[vf#0:0 @ 00000297c5ef04c0] Error sending frames to consumers: Function not implemented
[vf#0:0 @ 00000297c5ef04c0] Task finished with error code: -40 (Function not implemented)
[vf#0:0 @ 00000297c5ef04c0] Terminating thread with return code -40 (Function not implemented)
[vost#0:0/h264_nvenc @ 00000297c5f41e00] Could not open encoder before EOF
[vost#0:0/h264_nvenc @ 00000297c5f41e00] Task finished with error code: -22 (Invalid argument)
[vost#0:0/h264_nvenc @ 00000297c5f41e00] Terminating thread with return code -22 (Invalid argument)
[out#0/mp4 @ 00000297c5f05f00] Nothing was written into output file, because at least one of its streams received no packets.

![A0198142C0BE013D0E0337308E14BE88](https://github.com/SmallPeaches/DanmakuRender/assets/73329435/6b23ffbf-9211-4768-901f-a10913368139)

**Comment by SmallPeaches** [comment]
你是什么显卡？

**Comment by y-ucheng** [comment]
> 你是什么显卡？

我是N卡 3060

**Comment by y-ucheng** [comment]
> 你是什么显卡？

不过已经解决掉了 更新完后发现还有更新的 然后再更新之后后面才行
