### ISSUE TITLE
虎牙 弹幕下载线程异常退出，正在重试。。。

### ISSUE THREAD

**Issue by prettyby** [SmallPeaches/DanmakuRender#241]
虎牙 弹幕下载线程异常退出，正在重试。。。

![ebe9e5c53063f2e0d6bf0c32c36cb662](https://github.com/SmallPeaches/DanmakuRender/assets/153463728/ac4f8b3e-6ee5-4ca2-a99f-5a0f2f9328cd)

附日志
[DMR-20240530-4.log](https://github.com/SmallPeaches/DanmakuRender/files/15496972/DMR-20240530-4.log)

**Comment by a7606962** [comment]
应该是哪里出问题了   我也是一直报错

**Comment by aleaner9** [comment]
+1，今天录虎牙有问题

**Comment by aleaner9** [comment]
我暂时把虎牙弹幕录制关了，无弹幕版还是正常的

**Comment by prettyby** [comment]
> 我暂时把虎牙弹幕录制关了，无弹幕版还是正常的

4点虎牙更新接口
别的录制无弹幕版的软件（收费的）在5点陆续更新
虽然这个不更新也一样能录制无弹幕
但是我挺希望他收费的 不然用习惯了
作者哪天不更了 直接傻掉。。。

**Comment by prettyby** [comment]
请问这个该如何更新？
我之前尝试把更新内容复制近.py文件中，但是会闪退
如果可以的话建议做到update中，直接更新
或者打个包更新也好啊

![image](https://github.com/SmallPeaches/DanmakuRender/assets/153463728/1f9cdda5-f60f-46ee-a549-486c362e424d)

**Comment by prettyby** [comment]
> 请问这个该如何更新？ 我之前尝试把更新内容复制近.py文件中，但是会闪退 如果可以的话建议做到update中，直接更新 或者打个包更新也好啊
> 
> ![image](https://private-user-images.githubusercontent.com/153463728/335245322-1f9cdda5-f60f-46ee-a549-486c362e424d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTcwODExNTEsIm5iZiI6MTcxNzA4MDg1MSwicGF0aCI6Ii8xNTM0NjM3MjgvMzM1MjQ1MzIyLTFmOWNkZGE1LWY2MGYtNDZlZS1hNTQ5LTQ4NmMzNjJlNDI0ZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTMwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUzMFQxNDU0MTFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01ODIxZWNkZjYzNDg1MDIyZGQ1ZGYzZTQwOWY4ODg0ZjliNTEwMzU3ZmRiMDlkZTgwODU0NjZkZmJhYzY4MmVmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.LLTe-dmIuFseEJRBTR-bGyKN7LCjXvJE_-hfJLd4niE)
