### ISSUE TITLE
请问出现这个报错是因为什么，关于utf-8

### ISSUE THREAD

**Issue by aleaner9** [SmallPeaches/DanmakuRender#242]
我最近也没改config
![11](https://github.com/SmallPeaches/DanmakuRender/assets/131841843/fcd5efa5-3360-463d-a5f7-bb845a82b58b)

**Comment by aleaner9** [comment]
好像仅限虎牙，可能是虎牙的问题

**Comment by SmallPeaches** [comment]
应该是你调了什么电脑的或者是Python的默认编码设置？这里其他人没有汇报有问题。

**Comment by aleaner9** [comment]
我试了下，录虎牙没开播主播显示这个，已开播主播显示那个弹幕下载线程异常退出

**Comment by Sora3QwQ** [comment]
虎牙的弹幕貌似炸了 不知道虎牙改了什么

**Comment by Sora3QwQ** [comment]
![20240530235848](https://github.com/SmallPeaches/DanmakuRender/assets/76860912/32ba0c18-41f9-4a9f-9527-c02860ce6e2e)

**Comment by aleaner9** [comment]
作者刚修复了，把新的包下载下来就好了
