### ISSUE TITLE
用了快半年，几个可能有用的功能建议

### ISSUE THREAD

**Issue by aleaner9** [SmallPeaches/DanmakuRender#243]
（有些可能是我设置问题）
1. 设置1小时分段，断网等原因导致视频分段，希望第二、三段标题自动更改为[······日xx点-2（带弹幕版）]、[······日xx点-3（带弹幕版）]，当前是类似[[正在录制]xxx-20240530-001758-Part000（带弹幕版）]这样的命名。
2. 我用的7000系A卡，有时候电脑需要临时重启，导致有些视频没渲染完，render only好像默认是N卡h264_nvenc渲染，希望可选h264_amf渲染。
3. 接2，为了把没渲染完的视频渲染完，我用ffmpeg手动渲染了一下，发现av1_amf同体积清晰度和色彩好像更好一点，速度也没变慢。改config发现av1_amf渲染出来是乱码。希望config能使用av1_amf渲染。
4. 希望新增把弹幕版和无弹幕版自动放到同一个视频分P的功能，把弹幕版放前面分p，无弹幕版放后面分p.
5. 我一般睡觉前估算时间手动设置个定时关机，如果可以的话，希望软件添加一个可选的渲染、上传完全部视频后自动关机的功能。
非常感谢作者，软件非常好用。
非常感谢作者，软件非常好用。
非常感谢作者，软件非常好用。

**Comment by SmallPeaches** [comment]
1. 这个是由于你标题重命名冲突导致的，你只设置了小时没有设置分钟，那么同一个小时的文件就冲突了自然会命名失败，建议还是在文件名里面加上分钟数。
2. render only读取的是replay.yml的配置文件（v5是global.yml），你改这个就可以了。
3. 我这个渲染本质上也是命令行调用ffmpeg，如果渲染失败的话你可以查一下日志里面的ffmpeg命令，看看是哪里出问题了。
4. 这个功能在v5已经实现了。
5. 暂时没有这个计划，主要是我这个做的是长时间自动化录播，要自动关机没什么用。

**Comment by aleaner9** [comment]
收到，谢谢作者
