### ISSUE TITLE
更新了最新的5.30 但还是提示弹幕报错

### ISSUE THREAD

**Issue by prettyby** [SmallPeaches/DanmakuRender#244]
昨晚更新了5.30 测试了几个虎牙游戏直播间 卡尔 吕德华 都没问题
关机睡觉。。。
今天提示 “弹幕下载线程异常退出，正在重试...”
但 弹幕文件 自动渲染一切正常，只是这个提示看着很慌张。。。

![41d27a79883e725d7da479900e88f6ae](https://github.com/SmallPeaches/DanmakuRender/assets/153463728/63085eee-275f-4d04-baf1-93ae16bf5721)

**Comment by prettyby** [comment]
请问这个该如何更新呢？
找到对应的行 复制进去替换保存么 ？

![image](https://github.com/SmallPeaches/DanmakuRender/assets/153463728/0c53bfe3-283c-4456-a537-a0b2da9e3e6e)

**Comment by SmallPeaches** [comment]
下载压缩包覆盖就行
