### ISSUE TITLE
关于高级渲染参数的问题

### ISSUE THREAD

**Issue by roustar31** [SmallPeaches/DanmakuRender#245]
在高级渲染参数中尝试加入ffmpeg的锐化滤镜，但是手动渲染并未生效（V4根目录下的replay.yml已修改）：
![sshot-2024-05-31- 1](https://github.com/SmallPeaches/DanmakuRender/assets/11770850/0fd01f49-782e-47c9-b60c-b4735a62e9f1)
查看ffmpeg命令行发现并未加入锐化滤镜：
![sshot-2024-05-31- 2](https://github.com/SmallPeaches/DanmakuRender/assets/11770850/09761889-7b34-44a6-a31e-b166d1e9ec94)
这是我写法有误还是其他原因？

**Comment by SmallPeaches** [comment]
缩进不对吧，你查一下日志看看配置文件有没有被正确读取？

**Comment by roustar31** [comment]
配置文件正确读取了，但还是不生效。麻烦能不能给个例子。

**Comment by roustar31** [comment]
自己解决了，果然是缩进有误，谢谢！
