### ISSUE TITLE
您好！弹幕渲染存在BUG

### ISSUE THREAD

**Issue by haha12323** [SmallPeaches/DanmakuRender#248]
昨天更新5.30版本后，弹幕ASS文件可以正常录制了，但是好像无法进行渲染，弹幕版直播回放打不开，请求大佬修复！

**Comment by SmallPeaches** [comment]
应该是驱动没更新导致的，你更新下驱动就好了

**Comment by haha12323** [comment]
> 应该是驱动没更新导致的，你更新下驱动就好了
感谢回复！请问更新驱动如何操作，以下是BUG附图：
![bug](https://github.com/SmallPeaches/DanmakuRender/assets/149855176/ff942c78-8c8f-4ba5-9d2b-f561d8820d85)
![bug2](https://github.com/SmallPeaches/DanmakuRender/assets/149855176/b55d22fc-c23c-4f8d-bf04-9a16784d36a6)
![bug3](https://github.com/SmallPeaches/DanmakuRender/assets/149855176/ea9ac8a3-51a0-4311-a1c5-fd7d60d86786)

**Comment by SmallPeaches** [comment]
更新方法可以直接百度搜索：更新显卡驱动。

**Comment by haha12323** [comment]
> 更新方法可以直接百度搜索：更新显卡驱动。

更新驱动后已经恢复正常弹幕渲染！十分感谢！！
