### ISSUE TITLE
关于对BIGO平台的支持

### ISSUE THREAD

**Issue by justdoiting** [SmallPeaches/DanmakuRender#249]
测试发现不支持bigo直播

 平台 ('bigo', 'cn'): https://www.bigo.tv/cn/907494595 可能不受支持，即将使用默认API.

在别人的blog发现了对bigo的简单实现，希望可以添加支持

https://blog.gocos.cn/archives/248.html

多谢

**Comment by SmallPeaches** [comment]
streamlink应该已经有支持了，暂时没有单独的支持计划。
