### ISSUE TITLE
你好 佬  我写的一个项目用到了你的api 

### ISSUE THREAD

**Issue by ikun1993** [SmallPeaches/DanmakuRender#250]
佬你好 我昨天朋友需要一个同屏多播  然后我写了个项目直接复制了你的api  告知你下  因为我没看到你的项目许可协议  希望能够授权 麻烦了

https://github.com/biliup-start/VideoPlayer

**Comment by SmallPeaches** [comment]
可以的

**Comment by ikun1993** [comment]
感谢大佬
