### ISSUE TITLE
更新最新版之后，渲染带弹幕的视频部分无法播放

### ISSUE THREAD

**Issue by bbabz** [SmallPeaches/DanmakuRender#256]
自动完录制视频之后，正常生成视频及弹幕文件，但是渲染视频，部分能渲染成功并正常播放，部分显示渲染成功但播放会报错。

重新用render_only渲染，
![2](https://github.com/SmallPeaches/DanmakuRender/assets/173221034/09a32597-0efc-4800-9800-9bd631e4a8a5)
依旧无法播放
<img width="362" alt="1" src="https://github.com/SmallPeaches/DanmakuRender/assets/173221034/e3e1ce66-de4c-4aa4-be58-8c5d14dfd0a8">

**Comment by bbabz** [comment]
显卡驱动已经正常更新为最新版本

**Comment by SmallPeaches** [comment]
你试下把原视频转码再渲染看看？

**Comment by bbabz** [comment]
把原视频转码是指？把flv格式转换成MP4格式，再渲染嘛

**Comment by SmallPeaches** [comment]
对，你先用格式工厂之类的软件转码后再试试渲染看看
