### ISSUE TITLE
a卡 x9 390x 只能用cpu渲染。用h264_amf 最后视频点开只有声音。 输出flv改成mp4也不行 ffmpeg改成python也不行

### ISSUE THREAD

**Issue by lostconstant** [SmallPeaches/DanmakuRender#259]

**Comment by SmallPeaches** [comment]
你先更新一下显卡驱动，如果驱动最新也不能渲染的话大概率是显卡不支持硬件编码功能。

**Comment by lostconstant** [comment]
> 你先更新一下显卡驱动，如果驱动最新也不能渲染的话大概率是显卡不支持硬件编码功能。

我试了一下 render_only  是成功了

**Comment by SmallPeaches** [comment]
也许是你两个的编码器不一样？render only 调用的是全局参数的编码器。

**Comment by lostconstant** [comment]
> 也许是你两个的编码器不一样？render only 调用的是全局参数的编码器。

解决了 看来 default也要改

**Comment by lostconstant** [comment]
谢谢了
