### ISSUE TITLE
Found duplicated MOOV Atom Skipped it

### ISSUE THREAD

**Issue by see-more** [SmallPeaches/DanmakuRender#262]
**直播录制**
日志一直出现<code>Found duplicated MOOV Atom Skipped it</code>录制类型为MP4或flv时无法自动合成带字幕版视频
![image](https://github.com/SmallPeaches/DanmakuRender/assets/107225647/754d2522-bed5-4c3b-9fdb-721c08c6e47a)
修改下载类型为mkv时可以正常渲染
![image](https://github.com/SmallPeaches/DanmakuRender/assets/107225647/5ae2108d-efce-4430-a2b7-117d5564930f)

**Comment by SmallPeaches** [comment]
按道理来说这个不影响最终视频生成的，如果你录制mp4和flv在渲染时会提示什么？

**Comment by see-more** [comment]
**flv**和**mp4**都会出现<code>Found duplicated MOOV Atom Skipped it</code>，然后我搜了一下这个说是mkv不会出现这个问题 然后改成mkv就没这个输出了

**Comment by SmallPeaches** [comment]
你不是说不录mkv就渲染不了吗？那在渲染时会报错什么？

**Comment by see-more** [comment]
录制mp4或者flv的时候 上传到视频网站显示解码错误 然后我尝试录制一分钟的小段flv mp4 然后下载到本地使用vlc打开 会黑屏 我认为是这个Found duplicated MOOV Atom Skipped it的问题

**Comment by see-more** [comment]
下载直播和渲染弹幕两个过程 
- **格式为mp4或flv** 
下载直播的时候会出现<code>Found duplicated MOOV Atom Skipped it</code>并且下载下来的视频不能正常打开，渲染这一步也无法正常渲染
- **格式为mkv**
可以正常下载mkv格式，并正常渲染投稿

**Comment by SmallPeaches** [comment]
这样的话猜想应该是主播推流格式并不完全被flv和MP4兼容，你把直播间发来给我试下看看？
