### ISSUE TITLE
弹幕渲染后还是原视频 无弹幕

### ISSUE THREAD

**Issue by zww94** [SmallPeaches/DanmakuRender#268]
有ass文件，里面也有内容，渲染出来后，却没有弹幕

![1234](https://github.com/SmallPeaches/DanmakuRender/assets/118886012/1c23cf48-fdba-48d7-8fca-4558e60ac508)

[DMR-20240704(1).log](https://github.com/user-attachments/files/16100185/DMR-20240704.1.log)

**Comment by SmallPeaches** [comment]
配置文件这里没看出来问题，你试下用vlc播放看看有没有弹幕？

**Comment by zww94** [comment]
> 配置文件这里没看出来有问题，你试下用vlc播放看看有没有弹幕？

试了 还是没有弹幕 只有视频

**Comment by SmallPeaches** [comment]
从这里看并没有看出来问题，你试着用默认参数录一下看看？

**Comment by SmallPeaches** [comment]
如果你播放都没有弹幕的话大概率是弹幕和视频不匹配
