### ISSUE TITLE
无法渲染弹幕到视频中

### ISSUE THREAD

**Issue by PengOvO** [SmallPeaches/DanmakuRender#272]
版本：DanmakuRender-5-[2024.05.30](https://github.com/SmallPeaches/DanmakuRender/releases/tag/2024.05.30)
GPU：Intel(R) UHD Graphics，驱动程序版本：31.0.101.5186

已根据 V5 [使用文档](https://github.com/SmallPeaches/DanmakuRender/blob/v5/docs/usage.md)，将弹幕渲染参数调整为 vencoder: h264_qsv，但无法自动渲染弹幕到视频中，也无法通过 render_only.py 手动渲染弹幕到视频中。

本人是小白用户，望各位大佬帮忙解答~

附图和 log 如下：

![自动渲染失败](https://github.com/user-attachments/assets/e5615d56-d086-4e9d-80bc-a357463bb3cc)

![渲染视频无法打开](https://github.com/user-attachments/assets/e099ea2d-ff6b-4d1e-b2eb-03b02f45343f)

![手动渲染失败](https://github.com/user-attachments/assets/98b732a1-6d0a-46f7-8cef-74073e24dbfd)

[DMR-dryrun-20240712-5.log](https://github.com/user-attachments/files/16196457/DMR-dryrun-20240712-5.log)

**Comment by A-v-ery** [comment]
请问这个问题解决了嘛？我也遇到了一样的问题

**Comment by SmallPeaches** [comment]
这个是因为编码器没设置好导致的，根据自己的情况改好了就没问题了
