### ISSUE TITLE
使用 render_only 手动渲染，显示：渲染错误

### ISSUE THREAD

**Issue by PengOvO** [SmallPeaches/DanmakuRender#275]
版本：[DanmakuRender-5](https://github.com/SmallPeaches/DanmakuRender/tree/v5)
GPU：Intel(R) UHD Graphics，驱动程序版本：31.0.101.5186

已根据 V5 [使用文档](https://github.com/SmallPeaches/DanmakuRender/blob/v5/docs/usage.md)，将弹幕渲染参数调整为 vencoder: h264_qsv，可以自动渲染弹幕到视频中，但无法通过 render_only.py 手动渲染弹幕到视频中，提示：渲染错误。

本人是小白用户，望各位大佬帮忙解答~

附图和文件如下：

render_only 渲染错误
![渲染错误](https://github.com/user-attachments/assets/4c7ff9a1-b9b8-4f60-8868-d37bd99cd110)

DMR/Config/default.yml 文件
[default.txt](https://github.com/user-attachments/files/16201166/default.txt)

@SmallPeaches

**Comment by SmallPeaches** [comment]
你这个文件呢？是不是把它误删了？

**Comment by PengOvO** [comment]
在这呢，没有删除。大佬麻烦看下，我有没有改错内容~
@SmallPeaches 

DMR/Config/default.yml 文件
[default.zip](https://github.com/user-attachments/files/16202014/default.zip)

![default](https://github.com/user-attachments/assets/4842c56c-c2bf-434e-a213-eeff98c1b17f)

**Comment by SmallPeaches** [comment]
现在这个错误和你改没改配置文件没关系，关键在程序找不到这个文件。
你试一下在render_only所在的文件夹里面用控制台输入`python render_only.py`启动？

**Comment by PengOvO** [comment]
大佬，在render_only所在的文件夹里面用控制台输入 python render_only.py 启动就可以了，但是一旦双击就不行了。之前我就是一直双击启动，才显示渲染错误。

这是啥原因造成的呢，可以修复不？

@SmallPeaches

**Comment by SmallPeaches** [comment]
这应该是由于你双击打开的时候，程序的当前工作路径没有被正确设置导致的，所以相对路径找不到这个文件。
这个情况我也没见过，理论上来说双击打开的时候程序的工作路径就是文件路径，未来我改一下让他自动适应路径吧。

**Comment by PengOvO** [comment]
原来如此。

感谢大佬解答，辛苦了~
@SmallPeaches
