### ISSUE TITLE
抖音聊天室直播流尺寸过小导致弹幕模糊,如何正确设置单独主播渲染参数

### ISSUE THREAD

**Issue by natgeoo** [SmallPeaches/DanmakuRender#276]
抖音
![微信截图_20240714013247](https://github.com/user-attachments/assets/6b6f6cff-7ae0-4d16-8aa0-2d2224a99e57)
为什么render_only对主播配置文件中渲染参数不生效，对globa配置文件才生效，调整渲染倍数到7倍从直播流250x250放大到1700x1700弹幕仍然模糊
![微信截图_20240714013655](https://github.com/user-attachments/assets/8691e618-df19-4c9c-9843-b320c6a8f934)

**Comment by SmallPeaches** [comment]
render only设计这样是因为你可能对不同的主播设置了不同的上传策略，这个时候就会造成混乱，所以说它只读取global的配置。
至于为什么这么糊应该是默认的缩放顺序不对，你可能需要参考https://stackoverflow.com/questions/34221046/ffmpeg-filter-complex-wih-speedup-and-subtitles-and-scaling 使用自定义filter complex实现。
