### ISSUE TITLE
自动上传经常失败

### ISSUE THREAD

**Issue by cms666** [SmallPeaches/DanmakuRender#277]
[DMR-20240715.log](https://github.com/user-attachments/files/16241653/DMR-20240715.log)
这几天自动上传经常失败，往往上传了一两个任务之后就不会自动上传了，CTRL+c之后才能自动上传

**Comment by a7606962** [comment]
一样  最近上传老是卡死

**Comment by foeris** [comment]
https://member.bilibili.com/preupload?r=ping
选择适合你的上传线路

**Comment by SmallPeaches** [comment]
只能切换上传线路咯，或者用上传超时让它强制重传

**Comment by cms666** [comment]
@SmallPeaches 请问怎么强制重传呢？

**Comment by cms666** [comment]
@foeris 感谢大佬，我试试

**Comment by foeris** [comment]
5版本不确定有没有超时强制重传，用默认线路在log里看既没有上传也不会失败
