### ISSUE TITLE
v5 下载视频 不自动上传

### ISSUE THREAD

**Issue by zww94** [SmallPeaches/DanmakuRender#283]
视频下载后不自动上传，10分钟后 又重复下载。视频是已经下载下来了
日志如下
[DMR-20240721.log](https://github.com/user-attachments/files/16322819/DMR-20240721.log)

**Comment by SmallPeaches** [comment]
看起来像是视频没下载下来？你是不是手动删除了temp文件夹的内容？

**Comment by zww94** [comment]
> 看起来像是视频没下载下来？你是不是手动删除了temp文件夹的内容？

未删除 ，我看是下载会在temp 文件里面自动创建，下载完成后，又移动到我配置的视频下载文件夹里面。 然后又重复下载。

**Comment by zww94** [comment]
视频是已经下载下来了

**Comment by zww94** [comment]
[DMR-20240728.log](https://github.com/user-attachments/files/16402040/DMR-20240728.log)
这是日志

**Comment by SmallPeaches** [comment]
我这个设计不是拿来下载单个视频的，一般是填写https://space.bilibili.com/123456 这样的链接，下载单个视频推荐用yutto下载。
