### ISSUE TITLE
遇到了{检查更新失败, 'tag_name'}请问该怎么解决呢？

### ISSUE THREAD

**Issue by zhangsky9** [SmallPeaches/DanmakuRender#285]
![微信截图_20240722184658](https://github.com/user-attachments/assets/df7a4cd5-16a4-4241-a447-a53678800c0c)
![微信截图_20240723150628](https://github.com/user-attachments/assets/75efe757-7048-4f51-8789-fc8fe593169b)

今天重装了系统，下载v5使用，这个检查更新失败的问题已经没了，但是打开main.py运行，cmd窗口会闪退

**Comment by zhangsky9** [comment]
[DMR-20240723(4).log](https://github.com/user-attachments/files/16351464/DMR-20240723.4.log)
还有就是打开main.py了啥也不显示就是一块黑屏，这是日志

**Comment by SmallPeaches** [comment]
检查更新失败没影响的，如果闪退可以用控制台启动看看报错信息。
