### ISSUE TITLE
V5最新版油管视频下载错误

### ISSUE THREAD

**Issue by 108muu** [SmallPeaches/DanmakuRender#286]
大佬能帮忙看看吗？我网没问题不知道是不是我哪里设置错了
<img width="864" alt="屏幕截图 2024-07-24 180844" src="https://github.com/user-attachments/assets/a43a44da-b155-42c8-ae42-d9e025be1048">
[DMR-油管.txt](https://github.com/user-attachments/files/16360610/DMR-.txt)

**Comment by SmallPeaches** [comment]
我试了下是因为你这个主播有18+内容，必须登录才能下载

**Comment by 108muu** [comment]
> 我试了下是因为你这个主播有18+内容，必须登录才能下载

怎么登陆呢？现在v5还不支持吗？

**Comment by SmallPeaches** [comment]
使用额外参数输入到ytdlp，可以参考https://github.com/yt-dlp/yt-dlp

**Comment by SmallPeaches** [comment]
使用额外参数输入到ytdlp，可以参考https://github.com/yt-dlp/yt-dlp
