### ISSUE TITLE
部署完成后报utf-8错误

### ISSUE THREAD

**Issue by nicaicai666** [SmallPeaches/DanmakuRender#287]
error:root:'utf-8' codec can't decode byte 0xd3 in position 129: invalid continuation byte
Traceback (most recent call last):
  File "Y:\DanmakuRender-5\DMR\LiveAPI\huya.py", line 77, in onair
    liveline = base64.b64decode(liveLineUrl).decode('utf-8')
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xd3 in position 129: invalid continuation byte
debug:DMR.engine:{'source': 'downloader', 'target': 'replay/克烈', 'event': 'liveend', 'request_id': None, 'msg': '直播 已结束', 'dtype': None, 'data': None}

**Comment by SmallPeaches** [comment]
理论上对录制没有影响，未来会修复
