### ISSUE TITLE
录制突然出问题

### ISSUE THREAD

**Issue by G39949454** [SmallPeaches/DanmakuRender#289]
大佬，今天录制突然出现了问题，是这样的。我晚上挂着在录制，用浏览器边看边录，突然直播转圈卡住，录制也断了，我重新打开录制还是录制不了，然后我发现我连B站都打不开了，然后重启了一下电脑就好了，可以录了。我打开日志上面是这个，我不太懂，大佬您能帮我分析一下吗
![08 Q%W大佬，今天录制突然出现了问题，是这样的。我晚上挂着在录制，用浏览器边看边录，突然直播转圈卡住，录制也断了，我重新打开录制还是录制不了，然后我发现我连B站都打不开了，然后重启了一下电脑就好了，可以录了。我打开日志上面是这个，我不太懂，大佬您能帮我分析一下吗
{(MZFJG$}$~SK1H](https://github.com/user-attachments/assets/a3e38b4c-fbfc-46d0-ae5c-47b6c51e82e8)

**Comment by SmallPeaches** [comment]
看起来是你电脑断网了，如果是家庭网络每天是会固定时间重新拨号掉线一次，理论上一两分钟就会恢复的。
