### ISSUE TITLE
关于弹幕补偿设置

### ISSUE THREAD

**Issue by prettyby** [SmallPeaches/DanmakuRender#290]
弹幕延迟补偿（秒），一般情况下弹幕比视频慢，设置这个强行把弹幕提前，不同直播间不一样
  dm_delay_fixed: 0.0

这里如果希望慢一点，可以设置负数么？比如 -0.5 -1
如果可以 格式是   dm_delay_fixed: -0.5 吗？

**Comment by SmallPeaches** [comment]
可以的
