### ISSUE TITLE
py.exe 报错 key“error” 闪退

### ISSUE THREAD

**Issue by prettyby** [SmallPeaches/DanmakuRender#291]
更新了压缩包之后，打开py.exe 报错 key“error” 闪退

![image](https://github.com/user-attachments/assets/d4949e23-2a59-4c84-a253-68a4976fe35f)

![9862f9ed3bec3fbd264ac043968cd029](https://github.com/user-attachments/assets/c135c23a-3dc5-4c76-be92-eb6ed8334360)

**Comment by SmallPeaches** [comment]
修复了

**Comment by prettyby** [comment]
更新了以后 点开以后一直没反应 不录制 也不闪退

先更新
![image](https://github.com/user-attachments/assets/e76f8bdc-6fe6-4333-bdd2-16d6fccb83ad)

更新好以后无反应
![image](https://github.com/user-attachments/assets/5c53847d-4bfb-485c-b10e-325d8ebf8078)

**Comment by SmallPeaches** [comment]
你是不是使用了旧版的配置文件？

**Comment by prettyby** [comment]
> 你是不是使用了旧版的配置文件？

之前的问题已经全部解决了
补充一个问题global.yml和DMR-XXX..yml
如果有共同的设置 比如弹幕字体大小一类的设置
优先级是如何的呢 ？

**Comment by SmallPeaches** [comment]
优先是录制配置的，再是global的，最后是default的

**Comment by prettyby** [comment]
V5这个版本目前有两个问题
1.虎牙会产生非常多的1KB 2KB的文件（平均4小时直播会产生3、4个），我测试了游戏主播（基本不会卡），户外主播（偶尔卡），都有这个问题，我是按照1小时分段一次，感觉每次录制满1小时，录制下一段就会出现这个1、2KB的文件！
抖音测试了几个主播，这种就出现相对比较少 4、5个小时只有1、2个 甚至没有！（同样也是1小时1分段）

![image](https://github.com/user-attachments/assets/19057921-375d-4deb-a8f9-159983db0c3c)

2.自动渲染总是失败，需要手动渲染才可以！

![弹幕报错](https://github.com/user-attachments/assets/ad063557-c5fc-4a62-8344-3e3c8c3998f2)

**Comment by prettyby** [comment]
> V5这个版本目前有三个问题 1.虎牙会产生非常多的1KB 2KB的文件（平均4小时直播会产生3、4个），我测试了游戏主播（基本不会卡），户外主播（偶尔卡），都有这个问题，我是按照1小时分段一次，感觉每次录制满1小时，录制下一段就会出现这个1、2KB的文件！ 抖音测试了几个主播，这种就出现相对比较少 4、5个小时只有1、2个 甚至没有！（同样也是1小时1分段）
> 
> ![image](https://private-user-images.githubusercontent.com/153463728/354917068-19057921-375d-4deb-a8f9-159983db0c3c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI3OTgwOTMsIm5iZiI6MTcyMjc5Nzc5MywicGF0aCI6Ii8xNTM0NjM3MjgvMzU0OTE3MDY4LTE5MDU3OTIxLTM3NWQtNGRlYi1hOGY5LTE1OTk4M2RiMGMzYy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODA0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgwNFQxODU2MzNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mOTU1YWJhM2NlNDNlM2E5MDdiYmQwN2Y5MTk3NWIzOWIyZTgwZDU3NDVlMzQ5MzQ1ZmU1OGQ0NzAyNjI0MWI2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.oUybvJFHDE6_gbZB9NIWI6w3RV5jwZCVOxKoFPiespw)
> 
> 2.自动渲染总是失败，需要手动渲染才可以！
> 
> ![弹幕报错](https://private-user-images.githubusercontent.com/153463728/354917031-ad063557-c5fc-4a62-8344-3e3c8c3998f2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI3OTgwOTMsIm5iZiI6MTcyMjc5Nzc5MywicGF0aCI6Ii8xNTM0NjM3MjgvMzU0OTE3MDMxLWFkMDYzNTU3LWM1ZmMtNGE2Mi04MzQ0LTNlM2M4YzM5OThmMi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODA0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgwNFQxODU2MzNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kOWEzZDQ5MjE2ZDY4ODk3MjUyYjkzOTc4ZGYxODFhZDE1MjhkZTA4MzJmZDk2ZWI0MWIzNGI3OGZkOTA3ZTI5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.ja5Q5-AzyRDcwRpaD_Vx_Dq1c94Y9xsOwEYXuQm73Ko)

3.虎牙平台，弹幕持续时间20秒，弹幕延迟补偿-5，录播分段时间1小时，这样设置，还是会有弹幕提前出来，这个问题一直V4 V5一直都有！

**Comment by prettyby** [comment]
4. 关于这个参数，以下所有含该参数的地方全部改成了5M
结果是手动渲染5M，自动渲染依旧还是15M

视频编码器参数，默认恒定码率15Mbps
vencoder_args: [-b:v, 5M]

V5的DanmakuRender\DMR\Config\default.yml
DanmakuRender\configs\global.yml
DanmakuRender\configs\default.yml

V4的DanmakuRender\configs\default.yml
DanmakuRender\replay.yml
DanmakuRender\DMR\Config\replay_config.yml
DanmakuRender\DMR\Config\default_config.yml

**Comment by SmallPeaches** [comment]
1. 这个问题正在定位，未来会修复。
2. 这里没看到自动渲染的报错情况，你找一下日志文件中提示渲染失败的日志来看看？
3. 我猜应该是你单独主播配置那里修改了码率，而那个配置文件优先级是最高的。如果检查了没有，你可以看下日志文件的内部显示的日志，检查各部分配置文件是否正确。

**Comment by SmallPeaches** [comment]
1. 这个问题正在定位，未来会修复。
2. 这里没看到自动渲染的报错情况，你找一下日志文件中提示渲染失败的日志来看看？
3. 弹幕是完全按照本地时钟走的，如果你出现前面能对齐而后面不能对齐，那么大概率是直播流少了而不是弹幕少了，可以看下直播流哪里出现了缺失。
4. 我猜应该是你单独主播配置那里修改了码率，而那个配置文件优先级是最高的。如果检查了没有，你可以看下日志文件的内部显示的日志，检查各部分配置文件是否正确。
