### ISSUE TITLE
[功能请求]希望能添加渲染错误重试的功能！

### ISSUE THREAD

**Issue by haha252** [SmallPeaches/DanmakuRender#297]
RT，渲染出错-＞重试渲染（可以设定重试次数的那种）
爱你！

**Comment by SmallPeaches** [comment]
渲染是本地进行的，如果错误一般是参数配置错了或者是视频有问题，没有重试的必要。

**Comment by haha252** [comment]
> 渲染是本地进行的，如果错误一般是参数配置错了或者是视频有问题，没有重试的必要。

收到。目前已经解决了在amd老旧（集成）显卡上渲染出错的问题。方法是把解码器改成d3d11va，这样可以直接DirectX11来解码，防止DXVA设备创建失败
