### ISSUE TITLE
原视频转码经常音画不同步

### ISSUE THREAD

**Issue by cms666** [SmallPeaches/DanmakuRender#298]
原视频转码后的视频上传B站经常提示音画不同步，弹幕视频却没有出现过这样的问题，都是设置的1.5倍缩放。渲染没报错，请问大佬有可能是什么问题呢？

**Comment by cms666** [comment]
V5版本

**Comment by SmallPeaches** [comment]
你本地看会音画不同步吗？如果本地不会建议问问B站客服。
