### ISSUE TITLE
大佬斗鱼的弹幕录制不好用诶

### ISSUE THREAD

**Issue by y1haoL** [SmallPeaches/DanmakuRender#3]
无论录多长的视频，弹幕文件都只会生成一个 604字节的ass

**Comment by SmallPeaches** [comment]
喔？你把logs文件夹里面对应的日志文件发给我看看

**Comment by y1haoL** [comment]
yihaoLi
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "SmallPeaches/DanmakuRender"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年9月15日(星期四) 晚上6:10
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [SmallPeaches/DanmakuRender] 大佬斗鱼的弹幕录制不好用诶 (Issue #3)





 
喔？你把logs文件夹里面对应的日志文件发给我看看

**Comment by SmallPeaches** [comment]
你这个回复看不到东西啊，不过我建议你先试试用Python3.7录制，很有可能是因为Python版本导致录制错误

**Comment by y1haoL** [comment]
果然3.7版本正常了，我是看B站的专栏写的是让下载3.10。

发自我的iPhone

**Comment by SmallPeaches** [comment]
当初我用Python 3.10和asyncio的库是没有问题的，不知道是asyncio的库出问题了还是3.10的版本改进了协程处理，那个录制斗鱼弹幕的协程无法被正常调度，导致录不到弹幕，现在先用Python 3.7版本咯

**Comment by y1haoL** [comment]
感谢大佬耐心解答

发自我的iPhone

**Comment by y1haoL** [comment]
大佬，又发现一个问题。


python main.py -u https://www.douyu.com/85829 -s 3600 --fontsize 50，这是我使用的口令，渲染出来的带弹幕版MP4文件显示只有13秒。
在potplayer到13秒之后也能播放，但进度条只有13秒的，还没上传过B站，不知道上传后怎样。


我把文件拖到mkvtoolnix导出成mkv就一切正常了。



yihaoLi
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "SmallPeaches/DanmakuRender"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年10月14日(星期五) 下午4:58
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [SmallPeaches/DanmakuRender] 大佬斗鱼的弹幕录制不好用诶 (Issue #3)





 
当初我用Python 3.10和asyncio的库是没有问题的，不知道是asyncio的库出问题了还是3.10的版本改进了协程处理，那个录制斗鱼弹幕的协程无法被正常调度，导致录不到弹幕，现在先用Python 3.7版本咯

**Comment by SmallPeaches** [comment]
正常的，这个只是写的时候没写全，内容是在的。你如果用VLC player播放就没问题的。
