### ISSUE TITLE
安装 python 包报错【ERROR: Package u'aiohttp' requires a different Python: 2.7.14 not in '>=3.4.2'】

### ISSUE THREAD

**Issue by latv666** [SmallPeaches/DanmakuRender#30]
我的电脑 python 2.7.14 和 python 3.8.5 并存
安装 python 包时提示 ERROR: Package u'aiohttp' requires a different Python: 2.7.14 not in '>=3.4.2'
请问如何解决?

**Comment by SmallPeaches** [comment]
并存的话默认调用 python 指令的默认路径，你可能需要手动用 pip3 install 来安装包

**Comment by latv666** [comment]
> 并存的话默认调用 python 指令的默认路径，你可能需要手动用 pip3 install 来安装包

感谢回复,已经用 pip3 install -r requirements.txt 解决问题
