### ISSUE TITLE
弹幕是否增加用户名以及保存为txt格式

### ISSUE THREAD

**Issue by xhynice** [SmallPeaches/DanmakuRender#300]
只需要纯文本记录用户的名字和聊天信息即可.....
礼物信息 点赞和关注
我看到有的项目有完整的解析 可以参考一下.....

**Comment by SmallPeaches** [comment]
弹幕显示用户名已经在开发了，礼物信息暂无计划。

**Comment by haha252** [comment]
> 弹幕显示用户名已经在开发了，礼物信息暂无计划。

或者可以搞一个红色加粗的弹幕就行？没必要特效什么的

**Comment by Migflyway** [comment]
很好加，改两个代码就行。

**Comment by Migflyway** [comment]
DanmakuRender-5\DMR\LiveAPI\danmaku\douyin\__init__.py
`for msg in payload_package.messagesList:
            now = datetime.now()
            if msg.method == 'WebcastChatMessage':
                chatMessage = ChatMessage()
                chatMessage.ParseFromString(msg.payload)
                data = json_format.MessageToDict(chatMessage, preserving_proto_field_name=True)
                # print(data)
                name = data['user']['nickName']
                content = data['content']
                msg_dict = {"time": now, "name": name, "content": content, "msg_type": "danmaku", "color": "ffffff"}
                # print(msg_dict)
            elif msg.method == 'WebcastGiftMessage':
                chatMessage = GiftMessage()
                chatMessage.ParseFromString(msg.payload)
                data = json_format.MessageToDict(chatMessage, preserving_proto_field_name=True)
                # print(data)
                name = data['user']['nickName']
                # content = f"送给{data['toUser']['nickName'],data['gift']['name']}"
                if 'toUser' in data:
                    content = f"送给{data['toUser']['nickName']} {data['gift']['name']}"
                else:
                    content = f"送给主播 {data['gift']['name']}"
                msg_dict = {"time": now, "name": name, "content": content, "msg_type": "danmaku", "color": "ff0000"}
            else:
                msg_dict = {"time": now, "name": "", "content": "", "msg_type": "other", "raw_data": msg}
            msgs.append(msg_dict)`

**Comment by Migflyway** [comment]
DanmakuRender-5\DMR\Downloader\Danmaku\asswriter.py

`        content = danmu.content.replace('\n',' ').replace('\r',' ')
        dm_info +=  danmu.uname+"："+content
`
