### ISSUE TITLE
请问下弹幕密度那里应该填多少才能起到不重叠的效果呢

### ISSUE THREAD

**Issue by myallure0322** [SmallPeaches/DanmakuRender#302]
![1](https://github.com/user-attachments/assets/307f02a1-56a8-47a5-bbba-a2bbc6814740)
![3](https://github.com/user-attachments/assets/6ae34471-7bc1-4e6c-8843-eec9fe656a3a)
DanmakuFactory里面关于这个选项是-1这个数值，不知道应该填多少...

**Comment by SmallPeaches** [comment]
目前由于获取的弹幕长度不准确，所以说还不能做到完全不重叠，你可以试着一点一点调大让他尽量不重叠。

**Comment by myallure0322** [comment]
> 目前由于获取的弹幕长度不准确，所以说还不能做到完全不重叠，你可以试着一点一点调大让他尽量不重叠。

好的，谢谢
主要是因为最近看到了更新了可以加上弹幕id的，想试一下，结果发现如果加上弹幕id的话会很容易重叠了
