### ISSUE TITLE
不支持快手吗

### ISSUE THREAD

**Issue by natgeoo** [SmallPeaches/DanmakuRender#305]
![image](https://github.com/user-attachments/assets/9a4eca2d-cb97-4e2a-907d-a5925c702d80)

**Comment by SmallPeaches** [comment]
没有自带支持快手，如果streamlink不支持的话就用不了喔

**Comment by Eyion** [comment]
能自动监控录制吗？
是否支持视频号和腾讯会议

**Comment by SmallPeaches** [comment]
> 能自动监控录制吗？ 是否支持视频号和腾讯会议

可以自动录，视频号和腾讯会议不行。
