### ISSUE TITLE
虎牙平台录制清晰度问题

### ISSUE THREAD

**Issue by 108mua** [SmallPeaches/DanmakuRender#306]
虎牙观众多的直播间或者是大主播（不清楚具体条件），会被虎牙压缩画质，比如主播OBS推的蓝光15M或者蓝光20M，观众端和录制下来都是码率跟着画面复杂度变，比如黑神话悟空就是平均10M码率，狼人杀这种画面基本静止的平均就1M码率，有没有办法录制没有被虎牙压缩的源呢？

**Comment by SmallPeaches** [comment]
不行喔，我这个是获取的直播的流，直播间看不到就是没有了
