### ISSUE TITLE
抖音主播切换画质导致花屏

### ISSUE THREAD

**Issue by natgeoo** [SmallPeaches/DanmakuRender#307]
抖音直播中主播主动切换到画质导致录像文件花屏有解决办法吗，切换瞬间情况如图
![微信截图_20240904225645](https://github.com/user-attachments/assets/0e05bc6e-51ba-4981-b5f7-ab231149293f)

**Comment by Migflyway** [comment]
发现多次了，切换清晰度后，后面全是花屏

**Comment by SmallPeaches** [comment]
试试streamgears录制引擎看看？

**Comment by natgeoo** [comment]
> 试试streamgears录制引擎看看？

你好之前有提问过，streamlink并不支持抖音，刚刚尝试切换了也是无法录制
![28d7e502dab64b6249a9c36966e2148](https://github.com/user-attachments/assets/94021c79-9365-40e7-a8ea-f2b51ba98b99)

**Comment by SmallPeaches** [comment]
streamgears和streamlink不是一个东西喔，你仔细看看说明文档
