### ISSUE TITLE
有没有可能做一个定时开启的设计

### ISSUE THREAD

**Issue by 108mua** [SmallPeaches/DanmakuRender#308]
有些赛事直播间都是一直放录像，比赛快开始才切回直播，所以必须准时准点手动开启程序，感觉可以优化一下这方面的使用体验

**Comment by SmallPeaches** [comment]
暂时没有相关计划，如果需要的话可以全录+手动切割

**Comment by 108muu** [comment]
> 暂时没有相关计划，如果需要的话可以全录+手动切割

好的，剪辑倒是小事主要不方便自动上传。。
