### ISSUE TITLE
虎牙户外直播时切换清晰度或连麦,画面花屏

### ISSUE THREAD

**Issue by latv666** [SmallPeaches/DanmakuRender#31]
虎牙户外直播切换清晰度或者连麦时,录制的视频会花屏

![image](https://user-images.githubusercontent.com/1801723/226584388-18794ba3-4ca6-4c66-a7a1-ffc917535f11.png)

**Comment by SmallPeaches** [comment]
目前是有这样的bug，暂时只能等视频自然分段然后才会正常

**Comment by latv666** [comment]
> 

意思就是每次分段相当于重启录制?

如果 segment 设置为 30 秒,因为信号问题断播 10 分钟,那么会不会生成 20 个 0KB 的无效文件?

**Comment by latv666** [comment]
另外弹幕前面可以加上用户的 ID 吗? 比如

`不想上班：主播你好`

**Comment by SmallPeaches** [comment]
分段不是重启录制，出问题的主要原因是视频里面的参数变了，编码器按原来的参数播肯定出问题，分段之后都是新参数就没问题了
分段可以设置个30分钟，这样出问题了可以把损失最小化，设置30秒你上传之后全是些30s的片段怎么看hhh
这个加用户名字的暂时没这个功能

**Comment by latv666** [comment]
> 分段不是重启录制，出问题的主要原因是视频里面的参数变了，编码器按原来的参数播肯定出问题，分段之后都是新参数就没问题了 分段可以设置个30分钟，这样出问题了可以把损失最小化，设置30秒你上传之后全是些30s的片段怎么看hhh 这个加用户名字的暂时没这个功能

分段 30 秒是为了避免意外断电断网死机,像行车记录仪一样
ffmpeg 在 29 分钟断电,录像可以正常播放吗? 还是必须渲染后才可以正常播放?
临时查看的话可以用 potplayer 高级播放里的合并播放,才发现连字幕都可以无缝播放,没问题的话再合并

仔细看进度条,白条就是每段视频的标志
![image](https://user-images.githubusercontent.com/1801723/226664281-f09c1a14-8b42-4136-ae40-87a3fcbc6684.png)

**Comment by SmallPeaches** [comment]
mp4格式意外断电不能播放，ts和flv格式是可以的。
如果你只是本地播当然可以分很细，但是需要上传的时候可是一段一个分P，就不方便看了

**Comment by latv666** [comment]
> mp4格式意外断电不能播放，ts和flv格式是可以的。 如果你只是本地播当然可以分很细，但是需要上传的时候可是一段一个分P，就不方便看了

ts/flv 不方便剪辑,我之前用过类似的工具,这两个格式会丢时间轴,没法拖动,这个工具会丢吗?
上传前用 losslesscut 无损合并,不用重新编码,另外有时候视频超长,比如 20 小时的那种,连油管都得分成两段(12+8)

**Comment by SmallPeaches** [comment]
如果你不想用自动上传的话就没啥问题了，分一两分钟吧，不过有个小bug是目前分段最多999

**Comment by latv666** [comment]
> 如果你不想用自动上传的话就没啥问题了，分一两分钟吧，不过有个小bug是目前分段最多999

好的,谢谢,我的录像只传到油管自用,因为没钱买硬盘
另外分段到 999 的话是停止录制,还是重新编号开始录制?

**Comment by SmallPeaches** [comment]
这个不知道，没测试过（当初没想到会分这么多段）
