### ISSUE TITLE
渲染弹幕版视频如何自定义增加i帧关键帧方便播放器拖动进度条预览

### ISSUE THREAD

**Issue by natgeoo** [SmallPeaches/DanmakuRender#317]

**Comment by SmallPeaches** [comment]
可以参考这里：https://www.cnblogs.com/blackhumour2018/p/9427665.html

**Comment by natgeoo** [comment]
> 可以参考这里：https://www.cnblogs.com/blackhumour2018/p/9427665.html

已成功，分享配置怎么写的
globa里在此加入
    # 视频编码器参数，默认恒定码率15Mbps
    vencoder_args: [-b:v, 1.1M, -g, '20']

意思是每隔20帧加入1帧关键帧
