### ISSUE TITLE
功能建议:可自动切换ffmpeg命令调用双显卡同时渲染弹幕视频

### ISSUE THREAD

**Issue by natgeoo** [SmallPeaches/DanmakuRender#319]
如自动切换命令参数
- `-hwaccel_device 0`：指定硬件加速设备为 GPU 0。
- `-hwaccel cuvid`：使用 NVIDIA 的 CUVID 硬件加速解码。
- `-gpu 0`：指定编码时使用 GPU 0。

**Comment by SmallPeaches** [comment]
自动切换太复杂了，你可以考虑用不同任务手动设置不同的GPU
