### ISSUE TITLE
强制分辨率未生效

### ISSUE THREAD

**Issue by latv666** [SmallPeaches/DanmakuRender#32]
下面是我的录制参数,录制的视频文件是 2k 分辨率,而不是 1080p,不知道哪个参数错了

`replay:
  - url: https://www.huya.com/sineike
    segment: 30
    resolution: [1920,1080]`

**Comment by SmallPeaches** [comment]
这个强制分辨率不是指录制分辨率，而是指弹幕分辨率，一般情况下不用改，录制分辨率只能是最高。

**Comment by latv666** [comment]
好的,谢谢
