### ISSUE TITLE
[录制问题]录制抖音直播时遇到录制中断，所有任务都停止了，没有断网，能否看看日志？

### ISSUE THREAD

**Issue by Sunshinerainbowlittlehorse** [SmallPeaches/DanmakuRender#320]

**Comment by Sunshinerainbowlittlehorse** [comment]
[DMR-20241025(8).txt](https://github.com/user-attachments/files/17524877/DMR-20241025.8.txt)

**Comment by SmallPeaches** [comment]
我看了下你一次性录制的比较多，出故障之后一直重试然后被风控，抖音那边不返回数据了，建议录制特别多主播的时候改长一点重试时间

**Comment by x1nxxx** [comment]
大佬你好，我纯萌新，请问重试时间该如何设置？昨天录制时我也是跟贴主一模一样的问题。

**Comment by Sunshinerainbowlittlehorse** [comment]
可以了，谢谢解惑
