### ISSUE TITLE
抖音直播录制画质不清晰

### ISSUE THREAD

**Issue by PUNGU1N** [SmallPeaches/DanmakuRender#322]
v5主播源1080p60帧录制到本地只有1080p45帧画质很低，换v4测试录制画质是正常的。
昨天出现的，小白看不懂，感谢老师~
![屏幕截图 2024-11-06 023613](https://github.com/user-attachments/assets/d3d49046-dda3-405b-ab24-179a6d9fe98b)
![屏幕截图 2024-11-06 023636](https://github.com/user-attachments/assets/8cefb02b-9fc3-485b-ad9d-6f8b1bd41480)
![屏幕截图 2024-11-06 023659](https://github.com/user-attachments/assets/200fae46-4ce9-4692-bb01-41f92c993cc6)
![屏幕截图 2024-11-06 023722](https://github.com/user-attachments/assets/53e90bd2-8632-4896-8a95-6641b6072755)

**Comment by SmallPeaches** [comment]
你重启v5之后也不正常吗？录制其他主播正常吗？

**Comment by PUNGU1N** [comment]
你好，我今晚新测试了三个直播间。v4（2024.1.30)录制都是正常的。v5我原本在用的是七月份的版本，新测试了两个1080P主播录制出来还是45帧(确认主播原画为60帧），原画720p主播录制是正常720P60帧。更新最新版v5还是一样的问题，只有45帧率，画面很模糊。平时录制的flv文件1小时约有5gb大小，出现问题后视频大小只有2.5gb左右了_(:з)∠)_麻烦啦
