### ISSUE TITLE
[请教]如何限速？

### ISSUE THREAD

**Issue by TeslaLyon** [SmallPeaches/DanmakuRender#33]
在尝试添加快手平台的直播录制，现在只支持一个主播录制，快手平台对获取直播流的 html 页面有访问限制，但是对直播流貌似没有访问限制。

**Comment by SmallPeaches** [comment]
你指的限速是哪种限速？默认情况下liveapi里面的onair函数一分钟才访问一次，应该不会触发限制吧？
