### ISSUE TITLE
虎牙录制画面卡顿

### ISSUE THREAD

**Issue by 6180ecilahc** [SmallPeaches/DanmakuRender#334]
录制的视频画面时不时卡顿，文件大小是平时的一半，渲染后的视频帧率只有三十多还带小数点。

**Comment by 6180ecilahc** [comment]
![屏幕截图 2024-12-06](https://github.com/user-attachments/assets/81c90868-5fe6-4522-9ef3-1b33707227af)
第一个视频画面卡顿，第二个正常，从第三个视频开始码率突破了我设置的10Mbps

**Comment by 6180ecilahc** [comment]
![屏幕截图 2024-12-06](https://github.com/user-attachments/assets/b979690f-b013-4ba0-810c-111d1b2d4fc8)
第一个视频画面卡顿，第二个正常，从第三个视频开始码率直接拉满了

**Comment by SmallPeaches** [comment]
建议试试v5
