### ISSUE TITLE
期待docker版

### ISSUE THREAD

**Issue by SouL87a** [SmallPeaches/DanmakuRender#38]
不知道有没有

**Comment by SmallPeaches** [comment]
可能暂时还没有，也许你可以自己做一个？

**Comment by SouL87a** [comment]
很难受 我是搞嵌入式的 自己做这些属实不懂，随便问题下，我在nas的虚拟机里面运行，支持核显硬解码？ 看主页似乎没说明，之说了可以gpu解码

**Comment by SmallPeaches** [comment]
能不能用核显编解码取决于CPU种类吧，你可能要去官网查一下文档才知道。

**Comment by sanwecn** [comment]
安装NCT后设置容器runtime就能使用宿主gpu了
https://github.com/NVIDIA/nvidia-docker

**Comment by SouL87a** [comment]
> 安装NCT后设置容器runtime就能使用宿主gpu了 https://github.com/NVIDIA/nvidia-docker

不错的解决方法，不过我是用的nas核显硬解，可以通过编辑配置文件，来调用，只不过效率不高，但是比但cpu软解强多了
