### ISSUE TITLE
大佬有没有考虑过增加HEVC编码格式

### ISSUE THREAD

**Issue by NoColorPiggg** [SmallPeaches/DanmakuRender#39]
效率应该会比h264高不少

**Comment by SmallPeaches** [comment]
可以的，把编码器改成 hevc_nvenc 就可以了（不过部分编码器参数可能不兼容）
但是有个地方要提醒的是hevc的编码速度慢很多，它只是编码出来的文件相对小一些，如果是用于上传的话完全没必要。

**Comment by NoColorPiggg** [comment]
好的 感谢

发自我的iPhone
