### ISSUE TITLE
录制时出现问题

### ISSUE THREAD

**Issue by RAINighty** [SmallPeaches/DanmakuRender#42]
```
HTTPSConnectionPool(host='m.douyu.com', port=443): Max retries exceeded with url: /312212 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001CE2DE757C0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))
NoneType: None
```
以及如果录制时遇到错误重新开始录制，后续渲染几乎不用GPU，CPU利用率反倒提升（经常出现CPU占用率20%左右GPU利用率50%左右，极端情况下出现GPU利用率0%）

**Comment by SmallPeaches** [comment]
第一个问题应该是网络问题，正常情况下应该对录制没有影响。
第二个问题可能是文件破损之后GPU加速不行了？也许你可以试试用ts格式的文件作为录制文件

**Comment by RAINighty** [comment]
> 第一个问题应该是网络问题，正常情况下应该对录制没有影响。 第二个问题可能是文件破损之后GPU加速不行了？也许你可以试试用ts格式的文件作为录制文件

好的。而且我发现通过远程桌面传输文件会使GPU重新开始工作，很奇怪
这是日志文件
[DMR-20230401.log](https://github.com/SmallPeaches/DanmakuRender/files/11135992/DMR-20230401.log)

**Comment by SmallPeaches** [comment]
感觉可能是你这个GPU不支持某些特定参数导致的问题，你试下更新驱动程序，然后把编码器参数改成`['-b:v',15M]`试试？

**Comment by RAINighty** [comment]
> 感觉可能是你这个GPU不支持某些特定参数导致的问题，你试下更新驱动程序，然后把编码器参数改成`['-b:v',15M]`试试？

更新驱动后问题依然存在。刚开始的文件渲染速度很快，越到后面速度越慢，最后GPU利用率变为0%。编码器参数不是默认`[-b:v,15M]`吗

**Comment by SmallPeaches** [comment]
默认参数里面还有些对GOP进行修改的操作，你把它删掉试试

**Comment by RAINighty** [comment]
> 默认参数里面还有些对GOP进行修改的操作，你把它删掉试试

请问是哪些参数？不太懂

**Comment by SmallPeaches** [comment]
你在default.yml里面，把编码器参数从`[-b:v,15M, -g, 300, -keyint_min, 300, -sc_threshold, 0]`改成`[-b:v,15M]`

**Comment by RAINighty** [comment]
似乎我自行使用ffmpeg进行压制也会出现gpu利用率越来越低的情况（如一个半小时的录播，压制到一小时时就已经利用率为0%了）
![WW9 5)@FR6VZ$T)KX($X_BI](https://user-images.githubusercontent.com/97167694/230072453-5846b6e2-0e3f-4e8f-b611-e9f1fc03b5d6.png)
渲染时任务管理器的截图

**Comment by RAINighty** [comment]
或许和这个有关系
![(GL }~1MVJ~F7(SH9)CL5Q1](https://user-images.githubusercontent.com/97167694/230075632-b0f78c20-1183-48a7-855f-595721a8861c.png)

**Comment by RAINighty** [comment]
理解了，是CPU的瓶颈导致的，用AMD12核CPU就不会存在这种情况，那台机器是i5-10400 6核CPU

**Comment by SmallPeaches** [comment]
好了就好。
不过我个人还是偏向于驱动或者是环境没设置好，因为就算是纯CPU编码，也不至于出现你那种0.1倍速的情况吧，我之前8代i7+1060基本上都能4-5倍速
