### ISSUE TITLE
运行时出错

### ISSUE THREAD

**Issue by SouL87a** [SmallPeaches/DanmakuRender#43]
![image](https://user-images.githubusercontent.com/44329481/230771628-824bcede-c16b-4935-a6a1-d7799074ab8f.png)
`C:\DanmakuRender-4>python main.py
Traceback (most recent call last):
  File "C:\DanmakuRender-4\main.py", line 1, in <module>
    from tools.check_env import check_pypi, check_ffmpeg, check_update, check_biliup
  File "C:\DanmakuRender-4\tools\check_env.py", line 6, in <module>
    import requests
ModuleNotFoundError: No module named 'requests'`
已手动添加ffmpeg等到tools文件夹

**Comment by SouL87a** [comment]
手动安装 python库 可解决
但是似乎有点bug，有时候没法正常运行，并且
![image](https://user-images.githubusercontent.com/44329481/230774480-29d1e76b-e260-4dde-92de-dcf86e3de74e.png)
编码器部分，我使用的是核显，应该这样写吗？
`vencoder: h264_qsv 
hwaccel_args: []
`
hwaccel_args这一项内容保留括号 ？

**Comment by SmallPeaches** [comment]
第一个好像是bug，我之后修一下。
第二个可以括号和留空都行。

**Comment by SouL87a** [comment]
> 第一个好像是bug，我之后修一下。 第二个可以括号和留空都行。

核显硬解似乎有点问题，分配了两个cpu核心，渲染的时候cpu满载，但是核显占用只有40%左右(物理机是i3-7100 24G，Unraid系统，虚拟机win10)
`vencoder: h264_qsv  
hwaccel_args: [] `
只改了这两条内容

**Comment by SmallPeaches** [comment]
CPU满载但是集显不满是很正常的（就是CPU瓶颈了），主要是两个原因：
一是因为hwaccel_args设置了空，就是没用硬件解码（主要是我不知道集显硬解怎么弄）。
二是因为弹幕的渲染用的是video filter，它只能用CPU处理。

**Comment by SouL87a** [comment]
> h264_qsv

我似乎找到了写法，这一段用的是ffmpeg解码的吧。
可以参考jellyfin的硬件支持列表
![image](https://user-images.githubusercontent.com/44329481/230876878-e006b3c5-c3ce-4dfd-9282-e264c35b3dbc.png)
https://jellyfin.org/docs/general/administration/hardware-acceleration/
一般显卡都支持了。包括amd intel的核显。
附带intel vaapi和qsv解码 官方数据文档`https://www.intel.com/content/dam/www/public/us/en/documents/white-papers/quicksync-video-ffmpeg-install-valid.pdf`
`http://trac.ffmpeg.org/wiki/Hardware/QuickSync`
-hwaccel vaapi/qsv/amf 等等
通过ffmpeg -hwaccels可以看到支持的方式
![image](https://user-images.githubusercontent.com/44329481/230877453-a43840a2-a1ba-468c-95b0-f78ddf228a3d.png)
 [附带别人的实验文档](https://www.cnblogs.com/xlfqrxlf/p/16879357.html)。

但是我不知道你这个代码怎么写的  
hwaccel_args: [-hwaccel,qsv,-noautorotate]
我直接把cuda改成qsv就行？

最后最后最后
还有个小bug
![1}EQUK5S{1NHL~A0R_7T1TQ](https://user-images.githubusercontent.com/44329481/230877902-06a02ad3-a0b8-437d-94a7-976c1069a0dc.png)
这个bug似乎是我通过局域网共享文件直接运行导致的，我挂载到本地后正常，似乎也不是bug，winddwos的问题？

感谢开发者精心开发，很不错的软件。当然能减小一点性能占用就无敌了（似乎字幕渲染后文件变得比想象中大，无字幕3.5G 有字幕 5.1-5.6G 大小）

**Comment by SmallPeaches** [comment]
感谢分享。这里的hwaccel_args会被作为参数传递到ffmpeg，参数位置在`-i`之前，然后`-noautorotate`主要是保证N卡解码竖版视频正常，qsv也许不需要？
这个小bug感觉是网络问题？好像没有人报告过。
然后视频文件大的问题你可以通过修改编码器参数来改进，我默认是ABR 15Mbps，你可以根据需要改VBR改低码率，改高preset这样来减少文件体积。

**Comment by SmallPeaches** [comment]
至于性能占用的问题，我不清楚你是说录制的时候占用大还是渲染的时候占用大，如果是录制占用大的话可能是bug（目前没发现内存泄漏）。如果是渲染占用大的话很正常，你只要看它渲染够快就行了。
