### ISSUE TITLE
下播后程序停住没有输出结束信息

### ISSUE THREAD

**Issue by qsje** [SmallPeaches/DanmakuRender#44]
录制一开始一切正常，但主播下播了，分片就停住了，没有输出info信息，没有输出直播结束的信息，到第二天主播开播了程序没有继续录制，只能手动重启程序

**Comment by SmallPeaches** [comment]
从日志来看在录了20分钟之后就卡住了，我猜想可能是你用Windows运行的时候点到powershell然后主程序暂停了？你重新录几次试试？

**Comment by qsje** [comment]
应该不是这个原因，因为我是放在服务器上的，而且连续两天出现了这个情况。我再尝试看看。
