### ISSUE TITLE
录制的时候FFmpeg出异常中断

### ISSUE THREAD

**Issue by Marshallwjz** [SmallPeaches/DanmakuRender#45]
关闭了自动渲染弹幕，但是录制的时候会异常中断
[DMR-20230418.log](https://github.com/SmallPeaches/DanmakuRender/files/11254147/DMR-20230418.log)

**Comment by SmallPeaches** [comment]
这个好像是获取的流有问题，已经推送了一个更新，你更新一下试试

**Comment by Marshallwjz** [comment]
怎么更新啊大佬，重新装吗还是直接运行会自动更新

**Comment by SmallPeaches** [comment]
就重新下载一次然后覆盖原来的就行，保留replay.yml和default.yml

**Comment by Marshallwjz** [comment]
可以的，不会出错了现在

**Comment by Marshallwjz** [comment]
刚说完就中断，好像光录制不会有什么，要是用biliup同步上传就容易掉

**Comment by SmallPeaches** [comment]
如果你用我这个上传的话应该是在直播结束才上传的，你是另外开了个上传吗？

**Comment by Marshallwjz** [comment]
是另外开了个bili-up传的

**Comment by SmallPeaches** [comment]
如果你录很久都没问题，一开biliup就卡了，大概率是网速不够了
