### ISSUE TITLE
steam-gears 录制的 flv 时长不对

### ISSUE THREAD

**Issue by latv666** [SmallPeaches/DanmakuRender#46]
steam-gears 在户外直播的连麦开始和结束后会自动分段,视频可以播放,也可以上传到油管转码

但是用 potplayermini64 播放的时候,进度条显示的时长不对,文件属性里的时长也不对,如图(图片最上面是油管截图,下面是播放器和文件信息截图)

另外这个引擎不能录制弹幕吗?

下面是我的配置文件

`  - url: https://www.huya.com/195802
    engine: streamgears   # 使用streamgears作为下载引擎
    vid_format: flv       # 使用streamgears作为下载引擎时，录制格式只能是flv
    output_name: '195802_直播录像_{YEAR}{MONTH}{DAY}{HOUR}{MINUTE}{SECOND}'
    auto_render: false
    output_dir: ./直播回放/测试`

![image](https://user-images.githubusercontent.com/1801723/235460403-4cb00cde-8dac-4e58-9ddb-87eb20266c8c.png)

**Comment by SmallPeaches** [comment]
没弹幕应该是因为你没开自动渲染，然后时长有问题是正常的（因为stream-gears在分段的时候并没有重置时间戳）

**Comment by latv666** [comment]
我开起了自动渲染,也没有录制弹幕
时长问题已经找到修复工具了

不能录制弹幕的问题我找到原因了,之前我的配置文件里有虎牙和抖音的参数,顺序是

虎牙 1
抖音
虎牙 2
虎牙 3

这是四个都可以录制弹幕,但是昨天更新了脚本,用同样的配置文件,排在抖音下面的虎牙 2、虎牙 3 就不能录制弹幕,把抖音放到最下面就可以录制弹幕,比如

虎牙 1
虎牙 2
虎牙 3
抖音

**Comment by SmallPeaches** [comment]
不录弹幕这个bug已经推送更新了

**Comment by latv666** [comment]
更新后经常报错,比如
ffmpeg 异常退出
录制遇到错误,即将重试
推流信息变化,即将重试

**Comment by SmallPeaches** [comment]
如果是经常出现推流信息变化,即将重试的话，建议停用检测流变化的功能。
这个检测流变化的对于电脑直播的东西比较稳定，如果是手机户外直播的话很容易预判

**Comment by latv666** [comment]
> 如果是经常出现推流信息变化,即将重试的话，建议停用检测流变化的功能。 这个检测流变化的对于电脑直播的东西比较稳定，如果是手机户外直播的话很容易预判

好的,谢谢,关闭检测后恢复正常
另外 default.yml 和 replay.yml 是后者有参数优先,没参数就用前者吗?

**Comment by SmallPeaches** [comment]
是的，replay.yml的参数是优于default.yml的，一般情况下改replay.yml就行
