### ISSUE TITLE
centos 中ffmpeg  一直异常退出能看看什么原因吗

### ISSUE THREAD

**Issue by zany0505** [SmallPeaches/DanmakuRender#48]
[DMR-20230509.log](https://github.com/SmallPeaches/DanmakuRender/files/11427865/DMR-20230509.log)

**Comment by SmallPeaches** [comment]
它显示没有 rw_timeout参数，也许是你这个ffmpeg的版本太老了？
你先试着升级一下ffmpeg，如果还是不行的话在配置文件里面把ffmpeg stream args的 `-rw_timeout 10000000`删掉，或者使用streamgears下载引擎。
