### ISSUE TITLE
B站录制经常中断

### ISSUE THREAD

**Issue by qin-js** [SmallPeaches/DanmakuRender#49]
使用ffmpeg时一分钟一断，使用streamgears一到五分钟一断，平台是win10，请问是为什么呢？
[DMR-20230510.log](https://github.com/SmallPeaches/DanmakuRender/files/11443889/DMR-20230510.log)

**Comment by SmallPeaches** [comment]
这个看起来是B站的流提前中断了，但是我昨天晚上试了一下我这边录制没问题，猜想可能是CDN的问题，你试着把cdn改一下，改成0-2中的不同数字看看

**Comment by qin-js** [comment]
感谢解答。昨晚我试了改成5不行，今天改成1就没问题了
