### ISSUE TITLE
可否设置成边录制边上传

### ISSUE THREAD

**Issue by yepwaibin** [SmallPeaches/DanmakuRender#50]
录制完成一个片段之后，能否不用等到录制结束后再统一上传。边录制边上传，上传到同一视频下的分p，这个可以设置吗

**Comment by qsje** [comment]
我也希望可以增加这个功能，边录边传一方面提高效率节省时间，一方面传完了就能删掉，节省硬盘空间

**Comment by SmallPeaches** [comment]
之前有考虑过，但是遇到了一些问题。以后会考虑这个功能的
