### ISSUE TITLE
macOS 视频编码器无法调用到h264_amf 

### ISSUE THREAD

**Issue by zhongyangynag** [SmallPeaches/DanmakuRender#56]
Unknown encoder 'h264_amf'

**Comment by Mallknow** [comment]
运行 `./ffmpeg -codecs` 可以列出当前支持的编码器，确保当前 ffmpeg 版本支持**硬件加速**。

**Comment by SmallPeaches** [comment]
macOS有自己的一套硬件加速方案的，可以参考 https://zhuanlan.zhihu.com/p/40006235
