### ISSUE TITLE
希望能支持网易cc

### ISSUE THREAD

**Issue by zxcec** [SmallPeaches/DanmakuRender#59]
real-url弹幕：https://github.com/wbt5/real-url/blob/master/danmu/danmaku/cc.py

real-url视频：https://github.com/wbt5/real-url/blob/master/cc.py

目前我在用的弹幕下载是这个项目的[danmu.py](https://github.com/Dark-Sword-22/danmuG/blob/main/danmu.py)

**Comment by SmallPeaches** [comment]
最近比较忙，支持新的平台估计要等很长一段时间。
但是如果你会写Python的话可以考虑自己实现，只需要继承BaseAPI，实现里面的方法就可以了

**Comment by zxcec** [comment]
好像支持了，先关闭了
