### ISSUE TITLE
录制出错，直播回放文件夹中只有一堆1kb不到的.ass文件

### ISSUE THREAD

**Issue by BEIJUUUUU** [SmallPeaches/DanmakuRender#6]
[这里有垫狐星儿-20221103-133431.log](https://github.com/SmallPeaches/DanmakuRender/files/9932268/-20221103-133431.log)

**Comment by SmallPeaches** [comment]
你这个是在海外录制的吗？感觉应该是ip被暂时屏蔽了，你试试过段时间再录或者拿到自己的电脑上试试录制看看

**Comment by BEIJUUUUU** [comment]
> 你这个是在海外录制的吗？感觉应该是ip被暂时屏蔽了，你试试过段时间再录或者拿到自己的电脑上试试录制看看

是在海外，我明天再试试
