### ISSUE TITLE
安装失败

### ISSUE THREAD

**Issue by zxcec** [SmallPeaches/DanmakuRender#66]
![屏幕截图 2023-06-08 101452](https://github.com/SmallPeaches/DanmakuRender/assets/51906392/bc6776b5-6848-421f-ac9f-47ea7692ea72)
我试过台式机和笔记本都会出现这个报错，但是刚创建的虚拟机就不会报错

**Comment by yaobiao131** [comment]
```pip
pip uninstall protobuf
pip install protobuf==4.23.2
```

**Comment by SmallPeaches** [comment]
> ```
> pip uninstall protobuf
> pip install protobuf==4.23.2
> ```

这是默认安装的版本都有问题还是说它这个有问题？

**Comment by zxcec** [comment]
> > ```
> > pip uninstall protobuf
> > pip install protobuf==4.23.2
> > ```
> 
> 这是默认安装的版本都有问题还是说它这个有问题？

默认安装包就会有问题，使用上面的指令就可以用了。虚拟机是第一次按python，笔记本和台式机是之前安装python3.8.8

**Comment by yunbaitech-weiweixiaokeai-ml** [comment]
@

> > > ```
> > > pip uninstall protobuf
> > > pip install protobuf==4.23.2
> > > ```
> > 
> > 
> > 这是默认安装的版本都有问题还是说它这个有问题？
> 
> 默认安装包就会有问题，使用上面的指令就可以用了。虚拟机是第一次按python，笔记本和台式机是之前安装python3.8.8

可以的,谢谢大佬

**Comment by yaobiao131** [comment]
> > ```
> > pip uninstall protobuf
> > pip install protobuf==4.23.2
> > ```
> 
> 这是默认安装的版本都有问题还是说它这个有问题？

应该是默认安装版本太低了，protobuf在某个版本改了python的api，你可以在requirements.txt锁定一下版本吧

**Comment by SmallPeaches** [comment]
> > > ```
> > > pip uninstall protobuf
> > > pip install protobuf==4.23.2
> > > ```
> > 
> > 
> > 这是默认安装的版本都有问题还是说它这个有问题？
> 
> 应该是默认安装版本太低了，protobuf在某个版本改了python的api，你可以在requirements.txt锁定一下版本吧

已经推送更新了，不过我猜想是他之前的Python有这个protobuf的包了，我自己直接安装是没问题的
