### ISSUE TITLE
更新后，录制视频的码率更低了？貌似更模糊了点..

### ISSUE THREAD

**Issue by TenOenBiao** [SmallPeaches/DanmakuRender#67]
4月之前更新的貌似正常：1080p 8000k码率的直播。 2小时未压缩弹幕的录播文件大小在6.85GB左右，码率也在8000k左右浮动。
5月31之后更新的：同样条件下。录播文件在2.5GB左右，码率2-4000左右。

**Comment by TenOenBiao** [comment]
换了个直播间，录了几分钟，发现这个问题不见了。2个版本的文件居然一样大，码率也差不多了。。。

**Comment by SmallPeaches** [comment]
你录制的是B站吗？B站的直播如果看的人多叔叔会二压的，想录原画必须开播就开始录

**Comment by TenOenBiao** [comment]
好像b站确实是这样，感谢
