### ISSUE TITLE
可以原画质渲染输出吗

### ISSUE THREAD

**Issue by jth445600** [SmallPeaches/DanmakuRender#70]
大佬，能不能设置，渲染弹幕，和原视频的画质一样输出。也就是说只是添加弹幕，不改变原视频或很少改变原视频的画质
@SmallPeaches

**Comment by TenOenBiao** [comment]
画质无损应该不太可能，但是自动渲染确实比手动用ShanaEncoder压制要模糊的多。相比渲染速度，我也期待更少的画质损失(☆▽☆)

**Comment by SmallPeaches** [comment]
要追求画质可以把编码器参数改成`-cq, 27`，代价是50-100Mbps的超高码率，就看你准备拿这个视频来做什么了

**Comment by jth445600** [comment]
@SmallPeaches 我都是上传到b站，之前用biliup没有弹幕的原视频上传，很清晰和直播一样清晰，就很受欢迎呀

**Comment by jth445600** [comment]
渲染速度慢无所谓，让他在后台慢慢跑呗

**Comment by yunbaitech-weiweixiaokeai-ml** [comment]
@SmallPeaches 意思就是说, 只是给视频添加字幕, 当时这是改变视频流的, 怎么设置呀大佬

**Comment by SmallPeaches** [comment]
> @SmallPeaches 我都是上传到b站，之前用biliup没有弹幕的原视频上传，很清晰和直播一样清晰，就很受欢迎呀

我记得用默认参数的话效果还是可以的，我试过录apex都没啥问题

**Comment by SmallPeaches** [comment]
> 要追求画质可以把编码器参数改成`-cq, 27`，代价是50-100Mbps的超高码率，就看你准备拿这个视频来做什么了

简单的说如果单纯是追求画质，那么用这个就没问题。这个参数的含义是保证画质渲染，会让程序不考虑码率，然后保证视频的质量为27（越小越好，不过27已经很小了）。默认是恒定码率渲染，也就是说不管画面怎么丰富都保证码率为15M。

**Comment by yunbaitech-weiweixiaokeai-ml** [comment]
@SmallPeaches 我用默认的在本地看很清楚的,就是上传到B站就不行了

**Comment by SmallPeaches** [comment]
这个问题在GitHub的readme上面有解释，然后也提高了解决方案可以参考

**Comment by SmallPeaches** [comment]
这个问题在GitHub的readme上面有解释
