### ISSUE TITLE
录制CC直播遇到错误

### ISSUE THREAD

**Issue by BEIJUUUUU** [SmallPeaches/DanmakuRender#71]
![QQ截图20230611231912](https://github.com/SmallPeaches/DanmakuRender/assets/113653343/8c3ce8a2-a7ef-4318-aaf5-64c7e7328f22)

**Comment by yaobiao131** [comment]
稍后修复。已经解决了，还没有推送pr

> ![QQ截图20230611231912](https://user-images.githubusercontent.com/113653343/244947502-8c3ce8a2-a7ef-4318-aaf5-64c7e7328f22.png)

**Comment by BEIJUUUUU** [comment]
> 稍后修复。已经解决了，还没有推送pr
> 
> > ![QQ截图20230611231912](https://user-images.githubusercontent.com/113653343/244947502-8c3ce8a2-a7ef-4318-aaf5-64c7e7328f22.png)

感谢！

**Comment by yaobiao131** [comment]
> > 稍后修复。已经解决了，还没有推送pr
> > > ![QQ截图20230611231912](https://user-images.githubusercontent.com/113653343/244947502-8c3ce8a2-a7ef-4318-aaf5-64c7e7328f22.png)
> 
> 感谢！

已经推送pr等待合并，你可以用我的分支测试下 https://github.com/yaobiao131/DanmakuRender

**Comment by BEIJUUUUU** [comment]
可以正常开始录制了，非常感谢！
