### ISSUE TITLE
cuda版本问题

### ISSUE THREAD

**Issue by yunbaitech-weiweixiaokeai-ml** [SmallPeaches/DanmakuRender#73]
[Parsed_subtitles_0 @ 00000219ccc906c0] libass API version: 0x1700000
[Parsed_subtitles_0 @ 00000219ccc906c0] libass source: commit: 0.17.0-39-g04a208d5d200360d2ac75f8f6cfc43dd58dd9225
[Parsed_subtitles_0 @ 00000219ccc906c0] Shaper: FriBidi 1.0.12 (SIMPLE) HarfBuzz-ng 7.0.1 (COMPLEX)
[Parsed_subtitles_0 @ 00000219ccc906c0] Using font provider directwrite (with GDI)
[h264_nvenc @ 00000219ccbba800] Driver does not support the required nvenc API version. Required: 12.0 Found: 11.1
[h264_nvenc @ 00000219ccbba800] The minimum required Nvidia driver for nvenc is 522.25 or newer

**Comment by SmallPeaches** [comment]
更新驱动就行

**Comment by yunbaitech-weiweixiaokeai-ml** [comment]
@SmallPeaches 
FFmpeg换成旧版本了, 又出现这个错误了
```
Unrecognized hwaccel: cuda.
Supported hwaccels: d3d11va dxva2 qsv cuvid
```

**Comment by SmallPeaches** [comment]
那就把硬件加速参数的cuda改成 d3d11va dxva2 qsv cuvid 中的一个
