### ISSUE TITLE
功能建议

### ISSUE THREAD

**Issue by yunbaitech-weiweixiaokeai-ml** [SmallPeaches/DanmakuRender#76]
自动上到b站之后,删除源视频和弹幕视频 @SmallPeaches

**Comment by yunbaitech-weiweixiaokeai-ml** [comment]
大佬,我觉得可以借鉴`biliup`的做法， 在上传到b站之后，采取下一步的动作， 比如邮件提醒，自动移动到某个位置，或者copy到rclone挂载的网盘， 还有删除

**Comment by SmallPeaches** [comment]
这个未来可以考虑
