### ISSUE TITLE
如何录制电视直播?

### ISSUE THREAD

**Issue by claviering** [SmallPeaches/DanmakuRender#77]
地址：https://www.gdtv.cn/tvChannelDetail/53, 逆向接口 https://gdtv-api.gdtv.cn/api/tv/v2/tvChannel/53 拿到的 playUrl 播放不了，浏览器打开提示 403，不知道那里出问题，请教一下你，代码在 https://github.com/claviering/codedemo/blob/main/python/gdtv.py

**Comment by SmallPeaches** [comment]
应该是header不对吧，浏览器下载文件是用默认header的，就会显示403

**Comment by claviering** [comment]
构造了一样的请求头，去请求m3u8的地址，还是403

<img width="825" alt="image" src="https://github.com/SmallPeaches/DanmakuRender/assets/16227832/740613b9-07c8-4435-bd92-9b723a495c89">

**Comment by SmallPeaches** [comment]
请求流的header不一定和请求流地址的header相同，所以说这里要用浏览器看直播，然后看看它是怎么请求流的

**Comment by claviering** [comment]
我再研究一下
