### ISSUE TITLE
文件损坏 渲染出错

### ISSUE THREAD

**Issue by NoColorPiggg** [SmallPeaches/DanmakuRender#78]
大佬 帮我看下这个日志呗 不知道为什么文件分段失败 然后就损坏了 也无法渲染 文件名是：狂鸟丶楚河-90327-20230709-214813-Part002

[新建 文本文档.txt](https://github.com/SmallPeaches/DanmakuRender/files/11997531/default.txt)

**Comment by SmallPeaches** [comment]
这个有些时候会有这样的问题，可以把录制格式从mp4改成flv

**Comment by NoColorPiggg** [comment]
> 这个有些时候会有这样的问题，可以把录制格式从mp4改成flv

再帮我看下这个日志呗大佬，我把录制格式调成了flv，但是录制出来的视频无论是渲染前还是渲染后都会隔几秒卡一下，不知道为什么（声音不会卡，画面和弹幕会卡）。

[DMR-20230712.log](https://github.com/SmallPeaches/DanmakuRender/files/12026001/DMR-20230712.log)

**Comment by SmallPeaches** [comment]
这个卡指的是哪种卡？整体帧数低，还是说有掉帧情况？
然后录制其他直播间有没有问题？
如果是其他直播间没问题，但是只有这个直播间有问题的话你可以试试用streamgears录制引擎

**Comment by NoColorPiggg** [comment]
就是每次卡半秒左右，声音是正常的，画面和弹幕就卡住了，半秒后就正常了。
就像打游戏丢包一样，游戏角色卡住，下一秒直接闪现。

**Comment by NoColorPiggg** [comment]
要不要我把原始视频和渲染后的都上传到阿里云盘上，应该可以结合日志分析一下。（我对比过渲染前和渲染后的卡的位置一模一样）

**Comment by SmallPeaches** [comment]
我刚刚看了日志文件，日志是没问题的，渲染前后卡的位置一样说明是视频流丢失了。
但是不清楚具体是什么造成的丢失，所以让你试试录制其他主播，或者换用streamgears试试（不用录很久，录个两三分钟就行）

**Comment by NoColorPiggg** [comment]
尝试了一下 换引擎也会卡 我现在再换回六月份的版本试试
[DMR-20230712.log](https://github.com/SmallPeaches/DanmakuRender/files/12026292/DMR-20230712.log)

https://www.aliyundrive.com/s/CureYXWNbN5  这是阿里云盘的分享链接

**Comment by NoColorPiggg** [comment]
尝试了一下 6月20日的版本并不会卡顿 默认引擎 flv格式

**Comment by SmallPeaches** [comment]
那我这边检查一下
