### ISSUE TITLE
录制出错

### ISSUE THREAD

**Issue by BEIJUUUUU** [SmallPeaches/DanmakuRender#8]
[6655-20221215-232128.log](https://github.com/SmallPeaches/DanmakuRender/files/10238323/6655-20221215-232128.log)

**Comment by BEIJUUUUU** [comment]
今早重启电脑又试了试，还是显示 HTTP error 403 Forbidden
[星弥Hoshimi-20221216-101646.log](https://github.com/SmallPeaches/DanmakuRender/files/10242121/Hoshimi-20221216-101646.log)

**Comment by SmallPeaches** [comment]
我刚刚看了一下，应该是B站直播流的API有些变动，我看看要怎么解决

**Comment by BEIJUUUUU** [comment]
> 我刚刚看了一下，应该是B站直播流的API有些变动，我看看要怎么解决

感谢(๑>؂<๑）
