### ISSUE TITLE
使用的最新的代码斗鱼弹幕渲染后颜色还是白色

### ISSUE THREAD

**Issue by redkins** [SmallPeaches/DanmakuRender#80]
我看到最新版本修复了斗鱼的弹幕颜色,因为一直弹幕颜色都是白色,我以为这次修好了.

ass文件如下:

[Script Info]
Title: ./直播回放\［{YEAR}-{MONTH}-{DAY}　{HOUR}-{MINUTE}-{SECOND}］［{STREAMER}］［{TITLE}］.flv的弹幕文件, https://www.douyu.com/593392, Powered by DanmakuRender: https://github.com/SmallPeaches/DanmakuRender.
ScriptType: v4.00+
Collisions: Normal
PlayResX: 2560
PlayResY: 1440
Timer: 100.0000

[V4+ Styles]
Format: Name, Fontname, Fontsize, PrimaryColour, SecondaryColour, OutlineColour, BackColour, Bold, Italic, Underline, StrikeOut, ScaleX, ScaleY, Spacing, Angle, BorderStyle, Outline, Shadow, Alignment, MarginL, MarginR, MarginV, Encoding
Style: R2L,Microsoft YaHei,48,&H99ffffff,,&H99000000,,-1,0,0,0,100,100,0,0,1,1.0,0,1,0,0,0,0

[Events]
Format: Layer, Start, End, Style, Name, MarginL, MarginR, MarginV, Effect, Text
Dialogue: 0,00:00:0.00,00:00:16.00,R2L,,0,0,0,,{\move(2896,68,-336,68)}{\1c&H99ffffff&}哥细水长流啊
Dialogue: 0,00:00:0.55,00:00:16.55,R2L,,0,0,0,,{\move(3496,122,-936,122)}{\1c&H99ffffff&}那不就是之前的名字

**Comment by Mallknow** [comment]
**斗鱼的弹幕颜色取决于观众的房间等级**，大多弹幕颜色为白色为正常情况，下面是弹幕颜色根据等级的设置：
|  等级  |  颜色  |  RGB代码  |
| :-----: | :-----: | :-----------: |
|小于6级|白色|#ffffff|
|6级|浅蓝色|#00ccff|
|9级|浅绿色|#66ff00|
|12级|粉色|#f6447f|
|15级|橙色|#ff6600|
|18级|紫色|#cc00ff|
|21级及以上|红色|#ff2e2e|

**Comment by Mallknow** [comment]
我检查一下。

**Comment by redkins** [comment]
拉取了最新的代码.但是发现无法拉取字幕ass文件.

 File "G:\DanmakuRender-4\DanmakuRender\DMR\Downloader\asswriter.py", line 127, in add
    dm_info += '{\\alpha&H%s\\1c%s&}'%(self.opacity, BGR2RGB(dm['color']))
NameError: name 'dm' is not defined

**Comment by Mallknow** [comment]
是我疏忽了，没仔细看最新代码将代码中 `dm['color']` 更改为 `danmu.color` 即可。

**Comment by redkins** [comment]
经测试,弹幕颜色显示正常了.谢谢
还有就是之前的版本弹幕可以选择忽略过量弹幕,但是新的配置文件被取消了,能加回来吗?
```yaml 
# 指定过量弹幕的处理方法，
# 可选ignore（忽略过量弹幕）或者override（强行叠加弹幕），默认override
overflow_op: ignore
```

**Comment by SmallPeaches** [comment]
新版用`margin_w`替代了，`margin_w`设置为-1就是override，默认是有0.05倍宽度间距的（相当于多的弹幕被过滤了）
