### ISSUE TITLE
可以修改编码器预设吗？

### ISSUE THREAD

**Issue by 108muu** [SmallPeaches/DanmakuRender#81]
如图，有没有办法渲染时用high预设呢？
![屏幕截图(28)](https://github.com/SmallPeaches/DanmakuRender/assets/139286483/c803fe1c-83b8-4fe6-aa77-da54de66c8f7)

**Comment by Mallknow** [comment]
可以在 `default.yml` 配置文件中的 `vencoder_args` 项通过添加 `-profile:v high` 和 `-pix_fmt yuv420p` 两个参数更改。

**Comment by 108muu** [comment]
成功了，但后面这个-pix_fmt yuv420p有什么用呢？要一起添加吗？

**Comment by 108muu** [comment]
> 可以在 `default.yml` 配置文件中的 `vencoder_args` 项通过添加 `-profile:v high` 和 `-pix_fmt yuv420p` 两个参数更改。

成功了，但后面这个-pix_fmt yuv420p有什么用呢？要一起添加吗？

**Comment by Mallknow** [comment]
> 成功了，但后面这个-pix_fmt yuv420p有什么用呢？要一起添加吗？

可以不添加，默认的也是 `yuv420p`
