### ISSUE TITLE
如何提升渲染速度

### ISSUE THREAD

**Issue by xiaopangfeel** [SmallPeaches/DanmakuRender#84]
我使用的是一个老机器当录制机器，显卡是950。我看电脑在渲染时gpu占用只有30%-40%，是否可以在提升弹幕渲染时的速度

**Comment by SmallPeaches** [comment]
你看下CPU占用多少，再看下渲染的速度大概有多快？

**Comment by xiaopangfeel** [comment]
我看了一下cpu占用也在30%左右，渲染一个小时的片段用一个小时40分钟左右

**Comment by SmallPeaches** [comment]
那是有点慢了，不过我也没研究过低版本显卡的渲染问题，你只能先多试试不同编码器和码率了

**Comment by xiaopangfeel** [comment]
好的，我可以直接用render_only.py文件进行转码测试嘛

**Comment by SmallPeaches** [comment]
可以的
