### ISSUE TITLE
录制虎牙平台 主播被b类黑屏一段时间，下一次分段后没有视频流只有音频

### ISSUE THREAD

**Issue by 108muu** [SmallPeaches/DanmakuRender#85]
封装用的ts，文件大小也很大，但就是点开来没有视频

**Comment by SmallPeaches** [comment]
我还没见过这种被警告断流的情况。
文件大小是正常的话大概率是流损坏了或者没被检测出来。
你可以把视频和当时的日志文件传网盘发给我看看？

**Comment by 108muu** [comment]
> 我还没见过这种被警告断流的情况。 文件大小是正常的话大概率是流损坏了或者没被检测出来。 你可以把视频和当时的日志文件传网盘发给我看看？

链接：https://pan.baidu.com/s/1M88_-ZQrRbsdjFT127xMcw?pwd=7j7p 
提取码：7j7p

**Comment by SmallPeaches** [comment]
看了一下日志，初步判断应该是因为被黑屏断流了，然后重新推流之后流信息发生变化导致的。
可以试下用streamgears引擎录制，或者是开那个检测流变化

**Comment by 108muu** [comment]
好吧
