### ISSUE TITLE
登录问题

### ISSUE THREAD

**Issue by laotang8** [SmallPeaches/DanmakuRender#88]
# 登录信息保存的cookies路径，默认<上传器名字>.json
    cookies: ~

（如果要上传到b站，你这条信息时什么意思啊，比如我的cookies.json文件在C盘，是不是    {  cookies:C:/cookies.json  }是不是这样填写啊，能再讲具体一点吗

**Comment by SmallPeaches** [comment]
如果你提前准备了登录cookies，就指向文件所在的位置（Windows里面可以直接右键复制文件路径）
如果你没准备，那么就直接留空，程序启动时会要求你登录的
