### ISSUE TITLE
录制出现问题了

### ISSUE THREAD

**Issue by laotang8** [SmallPeaches/DanmakuRender#89]
我没有更改过任何参数的情况下，录制的时候FFmpeg异常退出

**Comment by SmallPeaches** [comment]
你有没有控制台报错的截图，或者是日志文件？
如果只是偶尔一次的话原因很多，有可能是主播推流断了一下，或者是网络卡了一下，只要整体录制的视频没问题就行了。
经常出现的话导致不能录制的话，就要试试其他直播间，或者是改用streamgears录制引擎试试，不同人的情况不一样，也没办法全部用一种套路。
