### ISSUE TITLE
软件启动失败

### ISSUE THREAD

**Issue by BEIJUUUUU** [SmallPeaches/DanmakuRender#91]
PS E:\各种录播\DanmakuRender-4> python main.py
Traceback (most recent call last):
  File "main.py", line 57, in <module>
    config = Config(default_config, replay_config)
  File "E:\各种录播\DanmakuRender-4\DMR\Config\__init__.py", line 40, in __init__
    name = GetStreamerInfo(rep['url'])[1]
TypeError: 'NoneType' object is not subscriptable
PS E:\各种录播\DanmakuRender-4>

**Comment by BEIJUUUUU** [comment]
releases版也是这样

PS E:\各种录播\DanmakuRender-2023.6.15> python main.py
存在可用更新, 如果出现问题请前往 https://github.com/SmallPeaches/DanmakuRender 获取更新.
Traceback (most recent call last):
  File "main.py", line 57, in <module>
    config = Config(default_config, replay_config)
  File "E:\各种录播\DanmakuRender-2023.6.15\DMR\Config\__init__.py", line 30, in __init__
    name = GetStreamerInfo(rep['url'])[1]
TypeError: 'NoneType' object is not subscriptable
PS E:\各种录播\DanmakuRender-2023.6.15>

**Comment by SmallPeaches** [comment]
这个应该是获取主播信息失败了，你看看logs文件夹日志文件有什么提示吗？

**Comment by BEIJUUUUU** [comment]
> 这个应该是获取主播信息失败了，你看看logs文件夹日志文件有什么提示吗？

我重新下载了一次软件，配置好主播信息打开就是这样，log文件夹都没有生成，我换个主播试试

**Comment by BEIJUUUUU** [comment]
还是不行

**Comment by SmallPeaches** [comment]
你试下其他平台的主播，如果还是不行的话把你录制的主播发给我来试试

**Comment by BEIJUUUUU** [comment]
我试了试其他平台，没问题，就B站的不行

**Comment by BEIJUUUUU** [comment]
应该是啊B改了东西

**Comment by SmallPeaches** [comment]
还真是叔叔改API了，我研究一下
