### ISSUE TITLE
日志2

### ISSUE THREAD

**Issue by laotang8** [SmallPeaches/DanmakuRender#94]
日志
[DMR-20230807.log](https://github.com/SmallPeaches/DanmakuRender/files/12292016/DMR-20230807.log)

**Comment by SmallPeaches** [comment]
从日志文件来看渲染的参数是没有问题的。
你试下把default.yml里面的编码器从h264_amf改成libx264，先试一下CPU编码能不能正常工作。
如果CPU编码可以，那么大概率是显卡的驱动程序没安装好；如果CPU都不能正常工作，那就要怀疑FFmpeg是不是出问题了。

**Comment by yaobiao131** [comment]
Duration: 05:01:01.51, start: 17012.515000, bitrate: 147 kb/s
Stream #0:0: Subtitle: text
Stream #0:1: Audio: aac (LC), 44100 Hz, stereo, fltp
Stream #0:2: Video: h264 (High), yuv420p(tv, bt709, progressive), 1920x1080 [SAR 1:1 DAR 16:9], 60 fps, 60 tbr, 1k tbn
[vost#0:0 @ 0000028dade20840] **Unknown encoder 'None'**

编码器没配置正确
