### ISSUE TITLE
新手问题

### ISSUE THREAD

**Issue by kyuuchi123** [SmallPeaches/DanmakuRender#95]
今天刚装， 斗鱼 虎牙 哔哩哔哩 都没法录。 最新版本 ffmpeg 在 tools， python 3.9.13。

每个平台都是一个问题。。

[DMR-20230809.log](https://github.com/SmallPeaches/DanmakuRender/files/12301948/DMR-20230809.log)

**Comment by SmallPeaches** [comment]
ffprobe.exe没放到tools文件夹里面
