### ISSUE TITLE
最近录制哔哩哔哩时弹幕量非常少，换到旧版本也一样！

### ISSUE THREAD

**Issue by diaodesan** [SmallPeaches/DanmakuRender#96]
以下是ass文件，就是一组弹幕与另一组间隔时间太长了，配置文件都是默认的，之前用旧版本还可以，现在新旧都是这个问题，总体弹幕少了很多，其它平台正常！我到直播间里看弹幕量也正常
麻烦大佬分析了，感谢！
![QQ截图20230813193627](https://github.com/SmallPeaches/DanmakuRender/assets/142130975/603e85d9-95df-48c7-b259-0340b47b8bd1)

**Comment by kaoyishu** [comment]
确实，而且只有b站弹幕有问题，零零散散的，录不下来

**Comment by SmallPeaches** [comment]
这个问题已经发现了，但是还没找到原因，你们用其他的录播软件有出现这个问题吗？

**Comment by voveer** [comment]
弹幕的ws又加了风控了

**Comment by SmallPeaches** [comment]
> 弹幕的ws又加了风控了

那现在大佬解决了吗

**Comment by SmallPeaches** [comment]
> 弹幕的ws又加了风控了

那现在有大佬解决了吗

**Comment by BEIJUUUUU** [comment]
录播姬的弹幕获取倒是没有问题
