### ISSUE TITLE
自动上传报[DEBUG]: uploader 塘坊索尔_dm_video_0 buffer tasks empty.

### ISSUE THREAD

**Issue by zany0505** [SmallPeaches/DanmakuRender#97]
日志：uploader 塘坊索尔_dm_video_0 buffer tasks empty.
[DEBUG]: uploader 塘坊索尔_src_video_0 buffer tasks empty.

这是哪里的原因呀

**Comment by SmallPeaches** [comment]
这个是说你当前的视频缓冲区是空的（如果你不用实时上传，那么视频会先存着等直播结束之后一起传）
你是在正常使用还是在测试的时候发现这个问题的？
自动上传能正常工作吗？

**Comment by zany0505** [comment]
测试发现的，这个会等多久如果直播结束也等吗？

**Comment by SmallPeaches** [comment]
如果是dryrun.py测试的话不应该出现这个问题。你是用main.py测试的吗（如果是这样的话看看是不是因为视频太短了）？
正常情况下是等主播直播结束之后，把单场直播所有的分P一次性上传。

**Comment by zany0505** [comment]
好像是这样的
