### ISSUE TITLE
新版本后台挂机卡死

### ISSUE THREAD

**Issue by zxcec** [SmallPeaches/DanmakuRender#99]
之前使用6.20可以在后台同时录两个主播，新版本8.23录制三个主播会卡死两个主播
python和ffmpeg都是从github推荐版本重新安装的
[DMR-20230828.log](https://github.com/SmallPeaches/DanmakuRender/files/12455235/DMR-20230828.log)

**Comment by SmallPeaches** [comment]
这个卡住是怎么个卡住了？检测不到主播开播还是说无法正常下载上传？

**Comment by zxcec** [comment]
检测不到主播开播。
具体是第一个主播开播后在后台录制但是在命令行上没有显示，第二第三个主播开播就后台无法自动开始录制。
我按f5后第一个主播录制的信息会出现在命令行，第二第三主播也会开始录制。

第一个主播开播在log文件的1850行左右
第二第三个主播开播在log文件的2400行左右，我是在20:10按得f5

**Comment by zxcec** [comment]
我一般后台会挂其他录播软件防止单个软件掉线，但是以前录两个cc主播也可以自动开始录制，现在添加一个抖音主播后程序就变成后开播的cc主播和抖音主播自动录不上

**Comment by SmallPeaches** [comment]
猜想是你一不小心点到控制台里面然后画面暂停了？看这里的log有几行是乱序的

**Comment by zxcec** [comment]
按你说的操作后暂时没有复现，感谢！
